### ISSUE TITLE
list errors in an output panel

### ISSUE THREAD

**Issue by fnkr** [SublimeLinter/SublimeLinter3#115]
The error list in [AtomLinter](https://atom.io/packages/linter) looks much better than SublimeLinter's.

SublimeLinter:
[![SublimeLinter](https://fs.fnkr.net/LdifCunV/raw)](https://fs.fnkr.net/LdifCunV)

AtomLinter:
[![AtomLinter](https://fs.fnkr.net/KczF7LLo/raw)](https://fs.fnkr.net/KczF7LLo)
![AtomLinter](https://raw.githubusercontent.com/AtomLinter/linter-jscs/master/example.gif)

**Comment by jrsinclair** [comment]
One thing I really like about the Atom linter display is that it tells you which linter is producing the error. This is really handy if you are running multiple linters (like jshint and jscs in the example above).

**Comment by eaviles** [comment]
@braver is this up to grabs? Or do you know if someone is already working on this feature?

**Comment by groteworld** [comment]
@eaviles no it's up for grabs

**Comment by braver** [comment]
The SL4 beta provides this feature, check it out!  https://github.com/SublimeLinter/SublimeLinter3#sublimelinter-4-beta
