### ISSUE TITLE
Feature: Ability to set working directory for linter

### ISSUE THREAD

**Issue by luke-tsekouras-sirca** [SublimeLinter/SublimeLinter3#150]
I'm using `pylint`, and I'm having trouble trying to get it to work with a particular `pylintrc` because of some `init-hooks` which adds a few folders to the python path to include extra modules in the project.  They rely on the current working directory being the root of the project.  At the moment the working directory looks to be set to the directory of the file being linted.  

I believe the `working_directory` option was available for SublimeLinter 2, so why is it not available for SublimeLinter 3?

**Comment by braver** [comment]
Seems like #325 already addresses this. If not, let me know, or it will come up by itself again. 🤷‍♂️
