### ISSUE TITLE
Don't disable linter if not installed globally

### ISSUE THREAD

**Issue by andrewdeandrade** [SublimeLinter/SublimeLinter3#157]
NodeLinter supports running local binaries installed by npm. Unfortunately, if the binary isn't also installed globally, then SublimeLinter will disable it entirely and not try looking for it again until SublimeText is restarted.

**Comment by tschaub** [comment]
@malandrew see #179 for a proposed solution to this.  Thanks for getting `NodeLinter` in.  I'm happy to help get it working.

**Comment by braver** [comment]
Since #179 is merged I think we can close this. If I'm wrong, let me know and we'll bring it back.
