### ISSUE TITLE
New linter suggestion : Bandit (a Python code security analyzer)

### ISSUE THREAD

**Issue by NotSqrt** [SublimeLinter/SublimeLinter3#159]
cf recent announcement on https://wiki.openstack.org/wiki/Security/Projects/Bandit
(seen on reddit at https://www.reddit.com/r/Python/comments/2ndtva/introducing_bandit_a_python_code_security_analyzer/ )

It should be a fairly easy to integrate linter (simple executable, probably not dependant on a python version).

I guess it would provide some traction to that interesting project.

If someone wants to work on it before I have the time to do it myself, please proceed !

**Comment by groteworld** [comment]
Closing with merges of #518
