### ISSUE TITLE
linter for jade templating engine

### ISSUE THREAD

**Issue by tardyp** [SublimeLinter/SublimeLinter3#16]
Please find linter for jade templates:

https://github.com/tardyp/SublimeLinter-jade

Its very basic, as the original jade tool does not provide too much diagnostics, but that is better than nothing.

This is a request for inclusion in official linters.

**Comment by benedfit** [comment]
It's early days, but I'm working on a Jade Linter that will pick up parser errors and allow users to force style conventions; https://github.com/benedfit/jadelint

I can keep you posted on how is progressing if you're interested?

**Comment by grotewold** [comment]
Please do! Once you feel ready you should consider creating a plugins or it  as well.

**Comment by benedfit** [comment]
I've created the plugin for an early version of the linter (more rules to lint against still under development) in #309

**Comment by grotewold** [comment]
Closed thanks to @benedfit
