### ISSUE TITLE
Zombie processes

### ISSUE THREAD

**Issue by malandrew** [SublimeLinter/SublimeLinter3#160]
With Node 10.26 on Linux, lots of zombie linter processes eventually cause SublimeText to hang and die.
This is with the NodeLinter plugin and SublimeLinter-contrib-lint-trap. This isn't happening on OS X with Node 10.33. And I am having no issues with lint-trap in the syntastic plugin.

As a workaround, some sort of timeout relative to the number of lines in the current buffer would be appropriate to help kill an unresponsive process. 

My only hypothesis here is that there may be something going on where stdin is not being closed after piping to the linter. 

I did find these old tickets that seem related:
https://github.com/SublimeLinter/SublimeLinter3/issues/30
https://github.com/SublimeLinter/SublimeLinter-for-ST2/issues/339

**Comment by malandrew** [comment]
I can't seem to reproduce this. If anyone else has this issue, please provide details on how to reproduce.

**Comment by skj3gg** [comment]
Is this still an issue?

**Comment by skj3gg** [comment]
Will reopen if issue occurs again.
