### ISSUE TITLE
Error/warning colours

### ISSUE THREAD

**Issue by dankini** [SublimeLinter/SublimeLinter3#165]
Hi, wonder if someone can enlighten me with a strange issue.
ST3 v3059
SublimeLinter v3.4.24

Have noticed when I open exact same file the text highlighting code colours are a lottery.  They seem to change indiscriminently between yellow and red.  No apparent reason, no apparent pattern to it.

Best illustrated with two images of same simple bit of code:
First, error codes correctly highlighted in red
![st3red](https://cloud.githubusercontent.com/assets/10128713/5356720/62670a98-7f97-11e4-958a-5cfcea30865f.png)
Second, error codes incorrectly highlighted in yellow
![st3yellow](https://cloud.githubusercontent.com/assets/10128713/5356726/720cbbb4-7f97-11e4-81c6-951691deca39.png)
Another example showing incorrect colouring
![st3yellow2](https://cloud.githubusercontent.com/assets/10128713/5356783/64dc109c-7f98-11e4-972a-e34ae20e463f.png)

At one point I thought a pattern was emerging whereby if I opened by double-clicking file from system it showed errors as yellow  but if I opened from within ST (File>Open File...) it correctly showed errors in red.  But that doesn't seem to be the case now and it just seems to be random.

Can confirm relevant user settings as:
"error_color": "D02000"
"warning_color": "DDB700"

Have removed sublimelinter package and reinstalled but no joy.

Any ideas please?

**Comment by braver** [comment]
I don't think overlapping linters like this, where they agree on what's wrong but not on the severity level, is very common or something we want to really support.
