### ISSUE TITLE
New Linter: SublimeLinter-contrib-twiglint

### ISSUE THREAD

**Issue by maxgalbu** [SublimeLinter/SublimeLinter3#170]
Hi, I've created a new plug-in for [twig](https://github.com/twigphp/Twig), a PHP template engine. It uses [twig-lint](https://github.com/asm89/twig-lint).

https://github.com/maxgalbu/SublimeLinter-contrib-twiglint

**Comment by maxgalbu** [comment]
Done and done!

**Comment by skj3gg** [comment]
Added, should be up in less than an hour. Thanks!
