### ISSUE TITLE
ENHANCEMENT: show error / warning on hover

### ISSUE THREAD

**Issue by cshanejennings** [SublimeLinter/SublimeLinter3#178]
On linters in other IDE's (such as IntelliJ, netbeans, etc)  I've seen a lot of linters that will display the associated lint message when the user hovers over the gutter icon.  Would something like this be possible in SublimeLinter?

**Comment by skj3gg** [comment]
AFAIK, SublimeText still does not have a tooltips API. Though it is a largely requested change by plugin writers. I agree this would be great to have!

I'm closing this issue, but not because I don't like the idea (quite on the contrary), it's just a cleanliness thing as this is request is not possible to fulfill. I will open this again as soon as a tooltip API is added.

Thanks!

**Comment by GarethLewin** [comment]
As of build 3070 there are tooltips now. I'm only adding this here because a google of "sublime linter tooltips" hit this issue.

**Comment by jawshooah** [comment]
Reopening this since, as @GarethLewin points out, it's something we can realistically accomplish with recent builds of ST3.

**Comment by bradens** [comment]
:+1: !

**Comment by bastianl** [comment]
would love this functionality as well.

**Comment by leesei** [comment]
FYI, [facelessuser/ScopeHunter](https://github.com/facelessuser/ScopeHunter) has implemented tooptip showing a decent panel with links that perform various action.

**Comment by GarethLewin** [comment]
Wow that's perfect. I will try to learn sublime plugin dev and try to merge the two, but hopefully someone with experience will get it done before then :)

**Comment by mrdanadams** [comment]
+1

**Comment by clijiac** [comment]
waiting for further info on this feature.
BTW:a quick hack is add this after line 403,it will always show a popup on the error line
```py
                    view.show_popup('<div class="content">' +''.join(line_errors) +'</div>',location=-1, max_width=600)
```

**Comment by am80l** [comment]
+1

**Comment by fclaussen** [comment]
+1

**Comment by toddjames** [comment]
I just want to add onto @clijiac's comment that the file to modify if you want to use this solution (which isn't too bad for now, in my opinion) is Sublime Text 3\Packages\SublimeLinter\sublimelinter.py

**Comment by corysimmons** [comment]
![image](https://cloud.githubusercontent.com/assets/224636/12925225/483acf44-cf2b-11e5-9990-ee5cf86d3a51.png)

**Comment by MattDMo** [comment]
The code base has changed slightly since @clijiac's original comment was posted, so I'll clarify the changes. First, open `Packages/SublimeLinter/sublimelinter.py` and scroll down to about [here](https://github.com/SublimeLinter/SublimeLinter3/blob/master/sublimelinter.py#L387-L406) (the region surrounding lines 390-405 or so. It should look similar to this:
```python
                    if plural:
                        # Sum the errors before the first error on this line
                        index = lines.index(lineno)
                        first = sum(counts[0:index]) + 1

                        if len(line_errors) > 1:
                            last = first + len(line_errors) - 1
                            status = '{}-{} of {} errors: '.format(first, last, count)
                        else:
                            status = '{} of {} errors: '.format(first, count)
                    else:
                        status = 'Error: '

                    status += '; '.join(line_errors)
                else:
                    status = '%i error%s' % (count, plural)

                view.set_status('sublimelinter', status)
            else:
                view.erase_status('sublimelinter')
```
Now, edit it to look like this:
```python
                    if plural:
                        # Sum the errors before the first error on this line
                        index = lines.index(lineno)
                        first = sum(counts[0:index]) + 1

                        if len(line_errors) > 1:
                            last = first + len(line_errors) - 1
                            status = '{}-{} of {} errors: '.format(first, last, count)
                        else:
                            status = '{} of {} errors: '.format(first, count)
                    else:
                        status = 'Error: '

                    status += '; '.join(line_errors)
                    # new stuff
                    view.show_popup('<div class="content">' + ''.join(line_errors) + '</div>',
                                    location=-1,
                                    max_width=600)
                    # end new stuff
                else:
                    status = '%i error%s' % (count, plural)
                view.set_status('sublimelinter', status)
            else:
                view.erase_status('sublimelinter')
```
The additional `view.show_popup()` line (I split it into several lines to comply with `pep8`/`pep257` formatting) should go directly after this line:
```python
                    status += '; '.join(line_errors)
```
Save the file, and you should now get plain black-and-white popups when you click on each highlighted error.

**Comment by TonyMilton** [comment]
++

**Comment by tommybananas** [comment]
There currently doesn't seem to be a way to figure out the mouse position. Although the tooltip is a nice addition to the api, it isn't the problem or solution.

**Comment by tbremer** [comment]
@MattDMo You should also include a `view.hide_popup()` call in the `else` statement:

```python
 if errors:
    …
    else:
        view.erase_status('sublimelinter')
        view.hide_popup()
```

**Comment by tbremer** [comment]
I know this Ticket is for a mouse on hover, but it seems like tooltips would be a great feature that many IDE's already implement. The API seems stable enough.

Is it possible that we could have an `enhancement` issue for tooltips on line and _if_ a mouse API is implemented we can update later?

**Comment by woble** [comment]
https://github.com/Microsoft/TypeScript-Sublime-Plugin/ has a very good implementation of Sublime tooltips. Perhaps someone with enough knowledge can get inspired by it.

**Comment by donysukardi** [comment]
![image](https://cloud.githubusercontent.com/assets/410792/15022172/f73053c4-125c-11e6-8631-cae49b49fe0d.png)

[Tern for Sublime](https://github.com/ternjs/tern_for_sublime/blob/master/utils/renderer.py) plugin does this very well, might wanna check out their implementation of the tooltip on hover

**Comment by chriscorwin** [comment]
I have styled the popup a bit better, putting each error in their own `p` so they are on separate lines,  and added the hide stuff mentioned by @tbremer 

![screenshot 2016-06-24 11 32 47](https://cloud.githubusercontent.com/assets/362417/16342370/bfafaccc-39ff-11e6-8de0-0454343e6d6d.png)


Also, 🐴 for extra whimsey. 

:D

```python
            if errors:
                lines = sorted(list(errors))
                counts = [len(errors[line]) for line in lines]
                count = sum(counts)
                plural = 's' if count > 1 else ''

                if lineno in errors:
                    # Sort the errors by column
                    line_errors = sorted(errors[lineno], key=lambda error: error[0])
                    line_errors = [error[1] for error in line_errors]

                    if plural:
                        # Sum the errors before the first error on this line
                        index = lines.index(lineno)
                        first = sum(counts[0:index]) + 1

                        if len(line_errors) > 1:
                            last = first + len(line_errors) - 1
                            status = '{}-{} of {} errors: '.format(first, last, count)
                        else:
                            status = '{} of {} errors: '.format(first, count)
                    else:
                        status = 'Error: '

                    status += '; '.join(line_errors)
                    # new stuff
                    view.show_popup('<style>html { background-color: #002b36; margin: 0px; color: #839496; } body { background-color: #002b36; margin: 5px; border: none; font-size: 11px; color: #839496; } div { margin: 0px; word-wrap:break-word; } a { color: #2aa198; } .error_line { color: #839496; margin: 4px 5px 8px; }</style> <div><p class="error_line">☞ ' + '</p><p class="error_line"> 🐴 '.join(line_errors) + '</p></div>',
                                    location=-1,
                                    max_width=400)
                    # end new stuff
                else:
                    status = '%i error%s' % (count, plural)
                view.set_status('sublimelinter', status)
            else:
                view.erase_status('sublimelinter')
                # new stuff
                view.hide_popup()
                # end new stuff
```

**Comment by groteworld** [comment]
I'm going to close this issue and merge the conversation into #471. On hover discussions are starting there now that the APIs are out, but I don't want to bother the lot of people in this thread that aren't interested in the sausage making. If you would like, please subscribe to notifications or add to the discussion in #471

**Comment by Kristinita** [comment]
@MattDMo , how I can select SublimeLinter messages? I applied your patch and I see, for example:

![MattDMo](http://i.imgur.com/F5XWLvo.png)

But I don't can select "is taken" maybe passivevoice, that copy and paste it.

Thanks.

**Comment by kyluca** [comment]
It looks like support for these tooltips has finally landed with #552 (#510)! :tada:  Now to customise the theme :sunrise:

**Comment by dsl101** [comment]
These are great. And what would be even better is if you could copy text from the tooltip. Use case: ESLint shows the rule which triggered the warning in the tooltip, and if you want to disable it for just that line, you can put `// eslint-disable-next-line <name-of-rule>` above the offending line, or `// eslint-disable-line <name-of-rule>` at the end of the line. Being able to copy the rule name from the tooltip would make this much easier.

For bonus points, make a configurable 'button' in the tooltip which does this by magic :).

**Comment by Kristinita** [comment]
@dsl101 ,

> And what would be even better is if you could copy text from the tooltip.

[**#1649**](https://github.com/SublimeTextIssues/Core/issues/1649).

Thanks.

**Comment by dsl101** [comment]
Tx for the link. In this specific case, I guess it would be the responsibility of the ESLint plugin, but since the popup appears to be HTML, copying the text '`// eslint-disable-line <name-of-rule>`' wouldn't be hard, but automatically pasting that at the end of the line would be trickier. Sublimelinter would need some kind of API to allow plugins to pass in actions? Maybe all that already exists, but if not, I can see it's a lot of work...

**Comment by MicroDroid** [comment]
My slightly improved version MattDMo's solution

```Python
view.show_popup('<div class="content">'
                + '<ul style="margin:8px; padding-left: 18px">' + ''.join(map(lambda e: '<li>' + e + '</li>', line_errors)) + '</ul></div>',
                location=-1,
                max_width=600)
```

![image](https://user-images.githubusercontent.com/8523135/31733018-01d80ad6-b443-11e7-90a2-c476e730659d.png)

**Comment by F1LT3R** [comment]
This is great, I'm so glad tooltips landed in Sublime. This makes like much easier.

I really liked the idea of being able to copy the error text. That would be really useful when collaborating with others who have failed to get their linters, etc set up correctly.

Also... I find it a bit cumbersome to have to have to use the mouse to see the tooltip. It would be great to be able to see the tip automatically when the cursor was on top of the error (even if it meant the cursor being over the error and hitting a key combo like <kbd>Cmd</kbd> + <kbd>E</kbd>).

**Comment by braver** [comment]
> I really liked the idea of being able to copy the error text. That would be really useful when collaborating with others who have failed to get their linters, etc set up correctly.

You can also find the error text in the "All Results" output panel and copy it from there.

> It would be great to be able to see the tip automatically when the cursor was on top of the error

You can call up the popup with the errors for the current line with a command, and if you want with a keybinding: https://github.com/SublimeLinter/SublimeLinter/blob/master/keymaps/Default%20(OSX).sublime-keymap#L9

The statusbar also contains the information that's in the tooltip.
