### ISSUE TITLE
"Unexpected reserved word"

### ISSUE THREAD

**Issue by andywillis** [SublimeLinter/SublimeLinter3#181]
SublimeLinter automatically produces an "unexpected reserved word" error for JS ES6 keywords like `export` and `import`. Note this is basic SublimeLinter without any plugins enabled (like jshint).

![screen shot 2015-01-28 at 13 12 06](https://cloud.githubusercontent.com/assets/1903595/5938281/47c127f6-a6f1-11e4-97ea-7b87d76c0f64.png)

Note that it only produces the error for the first keyword instance, not any of the following keywords.

**Comment by skj3gg** [comment]
To clarify you have `SublimeLinter` for SublimeText 3 installed, but not `SublimeLinter-jshint`?

Can you turn debug on and paste your console output after you restart SublimeText?

**Comment by hmps** [comment]
@andywillis Are you using JSCS? They have several issues reported that relates to ESPrima. See https://github.com/jscs-dev/node-jscs/issues/165.

**Comment by andywillis** [comment]
OK. That's interesting. I can have SublimeLinter-jscs disabled, but it still runs...

@hmps, you were right - it's a JSCS error. I'll take a look at that thread, the error is reproduced below for completeness.

```
<?xml version="1.0" encoding="utf-8"?>
<checkstyle version="4.3">
    <file name="/var/folders/wv/5tvt7grd74s4_c0mnf_xxwc80000gq/T/SublimeLinter3-awillis/home.js">
        <error line="5" column="2" severity="error" message="Unexpected reserved word" source="jscs" />
    </file>
</checkstyle>
```
