### ISSUE TITLE
Background mode doesn't work properly for java editing

### ISSUE THREAD

**Issue by rawngum** [SublimeLinter/SublimeLinter3#185]
Hi everyone, 

Im having trouble to get sublimelint work properly in background mode, looked for previous issues in the deprecated google group but nothing fit mine.

When i m editing a java file  with obvious errors in background mode, i click on show all errors
![capture d ecran 2015-02-02 a 13 39 13](https://cloud.githubusercontent.com/assets/6368288/6000668/ebafe328-aae0-11e4-8018-7b7d6d053023.png)

 if i save my file, errors are shown 
![capture d ecran 2015-02-02 a 13 41 44](https://cloud.githubusercontent.com/assets/6368288/6000694/426c5070-aae1-11e4-9684-9309ab635cdc.png)
I m correcting one, the other disappear 
![capture d ecran 2015-02-02 a 13 43 32](https://cloud.githubusercontent.com/assets/6368288/6000713/82b0887c-aae1-11e4-80f6-c76fd87a033b.png)

I have to save the file again to get the last error appear 
![capture d ecran 2015-02-02 a 13 44 50](https://cloud.githubusercontent.com/assets/6368288/6000731/b3694904-aae1-11e4-8a80-3a229a77cf2f.png)

It s not very handy, and if i understand right it's not the way the background mode is supposed to work, isn't it ?

Thank you for your help,
Cheers

Rwangum

**Comment by skj3gg** [comment]
What version of SublimeText and SublimeLinter are you using, and what Java linter are you using? This will help me resolve your problem.

**Comment by rawngum** [comment]
I m using sublime text 3 build 3065, sublimLinter v3.4.30 and sublimelinter-javac v1.1.8 .

-- 
Swan BENOIT

06.58.88.28.55

Le 2 février 2015 à 17:25:29, Blake Grotewold (notifications@github.com) a écrit:

What version of SublimeText and SublimeLinter are you using, and what Java linter are you using? This will help me resolve your problem.

**Comment by skj3gg** [comment]
That explains it. https://github.com/SublimeLinter/SublimeLinter-javac#important

**Comment by rawngum** [comment]
Ok, thanks.




-- 
Swan BENOIT

06.58.88.28.55

Le 2 février 2015 à 18:46:07, Blake Grotewold (notifications@github.com) a écrit:

That explains it. https://github.com/SublimeLinter/SublimeLinter-javac#important
