### ISSUE TITLE
AttributeError since build 3069

### ISSUE THREAD

**Issue by anlutro** [SublimeLinter/SublimeLinter3#186]
Since the last dev build (3069), linters haven't been working. The console shows the following error:

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 240, in on_pre_save
    callback.on_pre_save(v)
  File "/home/andreas/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 420, in on_pre_save
    if view.window().active_view() == view and self.is_settings_file(view):
AttributeError: 'NoneType' object has no attribute 'active_view'
```

Not sure if this is a SublimeLinter or core issue.

**Comment by skj3gg** [comment]
With the info given, I wasn't able to reproduce this. I got SL-jshint to properly lint in 3069. That error is saying that ST3 api call `view.window()` is returning a `None` instead of the active window so it doesn't have the function `active_view()` to call.

Any more information about what linter you're trying and steps to reproduce would be appreciated.

**Comment by anlutro** [comment]
I got home and the linter seems to be working fine on my other computer, even though the configs should be synced exactly and the OS is the same. I'll have to investigate further.

**Comment by skj3gg** [comment]
It happens, let me know!

**Comment by skj3gg** [comment]
I'm going to close this unless there is further issue?

**Comment by anlutro** [comment]
I completely forgot about this, sorry! So far I've only seen the issue on my work PC and can't remember if it happened again yesterday or today. I'll set up a reminder for myself to check again tomorrow and close or update the issue then.

**Comment by skj3gg** [comment]
Sounds good, let me know.

**Comment by anlutro** [comment]
Problem seems to have fixed itself. Weird, but OK!

**Comment by xsleonard** [comment]
Seeing this on the latest stable build 3114

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 231, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 275, in <lambda>
    run_callback('on_pre_save', callback, lambda: callback.on_pre_save(v))
  File "/Users/steve/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 416, in on_pre_save
    if view.window().active_view() == view and self.is_settings_file(view):
AttributeError: 'NoneType' object has no attribute 'active_view'
```

This was in 3-way split view.  The error only occured on a specific python file, which happened to be open in two of the panes.  However, I could not reproduce it.  I have SublimeLinter, SublimeLinter-contrib-eslint and MagicPython installed.

For anyone with the problem: Closing all open files (not only the problematic file(s)) fixed the error.
