### ISSUE TITLE
New Linter for Julia

### ISSUE THREAD

**Issue by tomaskrehlik** [SublimeLinter/SublimeLinter3#189]
I made a [Linter for Julia](https://github.com/tomaskrehlik/SublimeLinter-contrib-julialint), some README on other platforms is incomplete, however, I have no way to test it on other platforms so this is as good as it gets from me.

**Comment by skj3gg** [comment]
Items to change:

1. fix travisCI badge
1. remove [Temporary](https://github.com/tomaskrehlik/SublimeLinter-contrib-julialint#temporary) section

I'm a little nervous about the brittleness of this linter, mainly around the path in the shell scripts `/Applications/Julia-0.3.5.app/Contents/Resources/julia/bin/julia`. The version of Julia will change undoubtedly change. Is it too much to ask users to include this directory in their $PATH and so your linter would only reference `julia -e "using Lint; lintfile(\"$1\")"`

After all have been fixed and considered, Please make a release and a PR to the contrib file in the SL Package Control repo.

**Comment by tomaskrehlik** [comment]
I will fix the things.

Yes, I feel for that concern. If you have any suggestion how to do that in less hacky way, I will greatly appreciate that. However, there are million ways how you can call Julia right now: binaries on windows, bash in linux, binary or bash in julia, so I do not see a unified way. Maybe, Python could search in pre-specified locations upon installation, that are standard, like Program Files in Windows, applications in Mac OS? (Did not see how to do that from documentation...)

Also, what I use right now is running Julia as persistent process that listens on some port and returns only linted output. This is much faster and reliable, however, SublimeLinter seems to be more of a static linter package, am I right?

**Comment by skj3gg** [comment]
> If you have any suggestion how to do that in less hacky way

You could just make it so that the binary has to be findable be in $PATH or windows environment variable PATH?

The SL framework is really for static code analysis tools that can be run periodically or on save. Some that aren't analysers like `javac` and `php` enforce an "on save/load" because they are compiling and returning any lints found on compile

**Comment by tomaskrehlik** [comment]
OK, I have fixed the points that you mentioned. I will think about facilitating the set-up of path, but right now I think that the linter is good to go for most people.

**Comment by skj3gg** [comment]
https://github.com/tomaskrehlik/SublimeLinter-contrib-julialint/blob/master/linter.py#L33 this would override the previously set comment_re

**Comment by jawshooah** [comment]
Just to chime in, I agree that the assumptions made in the OS-specific scripts are very unsafe. We have no way of knowing where the user has Julia installed, and we certainly shouldn't assume a specific version.

@skj3gg has the right idea; we should inform the user in the README that, as with other linters, the `julia` binary must be available in their `PATH`.

**Comment by tomaskrehlik** [comment]
Ah, I see the confusion, sorry. The scripts were there from previous version of the linter before I figured out how to call it from the PATH. The README then only suggests how to add the specific destination to the path. Hopefully it should be fine now.

**Comment by skj3gg** [comment]
Looks great, thanks for your patience! Please submit a PR to the `SublimeLinter/package_control_channel` repository, alphabetically, in the `contrib.json` file

**Comment by skj3gg** [comment]
This has been added.
