### ISSUE TITLE
license

### ISSUE THREAD

**Issue by lunixbochs** [SublimeLinter/SublimeLinter3#193]
Hey, I'm pretty sure your license is invalid: https://github.com/SublimeLinter/SublimeLinter3/commit/637fa524fbbbc86d6eb6c50ba12776879b52a554

I gave explicit permission for the original SublimeLinter (not 3) project to be released as MIT, but SublimeLinter3 is a new fork from my work from *before* I added a proper license.

I believe the literal text of https://github.com/lunixbochs/sublimelint/blob/st3/LICENSE (including attribution) should be the base license here.

**Comment by skj3gg** [comment]
Hey @lunixbochs, sorry for any inconvenience.

does https://github.com/SublimeLinter/SublimeLinter3/commit/66a6d60eb8ad6638ddfd8941b4c27261770347e1
seem to fit what you are looking for?

**Comment by lunixbochs** [comment]
Thanks.

**Comment by skj3gg** [comment]
No, thank you for a great foundation!
