### ISSUE TITLE
New linter for Go: gometalinter

### ISSUE THREAD

**Issue by tylerb** [SublimeLinter/SublimeLinter3#196]
Please see https://github.com/tylerb/SublimeLinter-contrib-gometalinter

**Comment by skj3gg** [comment]
You are missing some flake8/pep257 errors. Any reason you are not using TravisCI?

```
./linter.py:14:1: F401 'dirname' imported but unused
./linter.py:42:35: E231 missing whitespace after ','
./linter.py:50:1: W391 blank line at end of file

./linter.py:47 in public method `cmd`:
        D400: First line should end with '.', not 'g'
```

**Comment by tylerb** [comment]
No reason, simply forgot to set it up. I'll get the lint errors corrected and set up TravisCI. Thanks!

**Comment by skj3gg** [comment]
After those have been resolved, Please make a PR to `SublimeLinter/package_control_channel` in the `contrib.json` file.

Thanks!

**Comment by skj3gg** [comment]
https://github.com/SublimeLinter/SublimeLinter3/blob/master/.travis.yml is the working example of our config

**Comment by tylerb** [comment]
Done and done. Thanks for the info and assistance!
