### ISSUE TITLE
No output when using jscs and jsxhint

### ISSUE THREAD

**Issue by qmmr** [SublimeLinter/SublimeLinter3#198]
SublimeLinter works when I'm in __json__ or __scss__ files but does not work with __jscs__ or __jsxhint__.

Here are [links to my configuration](https://gist.github.com/qmmr/f7756117ebff1677cd73).

The debug mode does not show any errors and I've checked that both jscs and jsxhint are available in the $PATH.

I'm using .zsh and I'm loading nvm in the `.zshenv` file.
The only plugin for `.oh-my-zsh` is `git`.

**Comment by qmmr** [comment]
I found what's going on. I had set file type as `6to5 JavaScript` and because of that SublimeLinter does not know what's going on. I've changed it to `JavaScript` and now it works.

**Comment by skj3gg** [comment]
That would do it, you can add it to the `"syntax_map"` setting in your SL user settings to have it lint `6to5 JavaScript`.
