### ISSUE TITLE
Pass full source file path to the invoked linter

### ISSUE THREAD

**Issue by massimiliano-mantione** [SublimeLinter/SublimeLinter3#199]
I am writing a plugin for a language where the linter needs to access the directory where the source code is placed.
This is because the language can load macros, the loading is usually relative to the location of the source file, and the linter depends on the macros being loaded properly.

So far I have it working with tempfile_suffix = '-' but I'd like to do better.

The linter accepts an argument that specifies the full path of the original source file, while doing the check on a temporary file (it does not read from stdin for now).
This way the linter can process the source taking its "contextual directory" into account, it works perfectly in atom and emacs.
However, I have found no way to pass this argument in SublimeLinter, neither in the "cmd" property nor overriding the "cmd" method.

Did I miss something?

(BTW, the language is "https://github.com/metascript/metascript")

**Comment by braver** [comment]
@massimiliano-mantione it's been quiet here for a while, sorry about that. Did you ever get this to work or do you need changes in SL?
