### ISSUE TITLE
New linter: SublimeLinter-contrib-scalac

### ISSUE THREAD

**Issue by jawshooah** [SublimeLinter/SublimeLinter3#200]
https://github.com/jawshooah/SublimeLinter-contrib-scalac

Sorry this took so long; put it away for a while and just came back to it.

Critiques welcome!

**Comment by jawshooah** [comment]
I've handled classpaths a bit differently than in [SublimeLinter-contrib-java](https://github.com/reekoheek/SublimeLinter-java).

Rather than having the user explicitly specify the classpath for a project as a list of entries in the config, I allow them to specify a `classpath_filename`, which I then search for as I would a config file using `util.find_file()`. The contents of this file are specified in the README.

**Comment by skj3gg** [comment]
Sorry, coming off of holiday, This looks good and I like the use of `rules.json`!

Please submit a PR to the package channel and I'll get that in ASAP

**Comment by jawshooah** [comment]
Excellent! I'm guessing I need to push a release as well, yes? Where do you recommend the version numbering start (1.0, 0.1, 0.0.1, etc)?

**Comment by skj3gg** [comment]
A lot of people push a `1.0` tag. but it's really dependent on the maintainer. I'm pretty methodical about the first pieces of code that I release not being perfect so I start `0.1.0`.

So whatever you like!

**Comment by jawshooah** [comment]
Makes sense to me, I'll go with `0.1.0` then. Trying to train myself to use semantic versioning everywhere anyway. Thanks!

**Comment by skj3gg** [comment]
Ahh, ok, so your releases [have gotten a little unruly](https://github.com/jawshooah/SublimeLinter-contrib-scalac/releases)! It's fine but we need to do a little cleanup or I think Package Control will bark at us (not sure though). You should probably go through and run this command on each tag: 
```
git tag -d 1.0.0
git tag -d 1.0.1
...
git tag -d v0.1.0
```
Then re-add your tag `git tag 0.1.0`

Then re-push the references `git push origin --tags`

Semantic versioning doesn't actually like a `v` in the start of the identifier.

**Comment by jawshooah** [comment]
Sorry about that, it was a result of merging in some changes from SublimeLinter-javac. I've cleaned it up now.

Also didn't realize semver frowned upon the `v` prefix, I'll get rid of that as well.

**Comment by skj3gg** [comment]
NP, its not that semver necessarily frowns on it, but more that it is never specified as valid which leaves room for interpretation but no `v` prefix is known as valid

http://semver.org/
Sections 9 is the real meat and potatoes to follow in this case.

**Comment by jawshooah** [comment]
Gotcha. I think I have everything in order now!

**Comment by skj3gg** [comment]
Thanks!
