### ISSUE TITLE
New linter: SublimeLinter-contrib-glsl

### ISSUE THREAD

**Issue by numb3r23** [SublimeLinter/SublimeLinter3#201]
https://github.com/numb3r23/SublimeLinter-contrib-glsl

I've added a linter interface to the glslangValidator to compile GLSL shaders.

**Comment by skj3gg** [comment]
2 changes. Fix the TravisCI badge and put the correct copyright information. Your wrote and own this code not aparajita. And the year is not right

After those changes are made please make a release and I'll add it to the package channel

**Comment by numb3r23** [comment]
done:)

**Comment by skj3gg** [comment]
please make your `1.0.0` [release](https://github.com/numb3r23/SublimeLinter-contrib-glsl/releases) and confirm that [this](https://github.com/SublimeLinter/package_control_channel/pull/20) looks correct

**Comment by numb3r23** [comment]
Cheers for the link & help, details look fine.

**Comment by skj3gg** [comment]
Should see it added to package control within an hour.
