### ISSUE TITLE
Mark style: can't remove 'fill'

### ISSUE THREAD

**Issue by matthewcc** [SublimeLinter/SublimeLinter3#204]
My mark style seems to have gotten stuck on 'fill'. If I set it to underline or outline, it will show those styles, but only in addition to having a fill. I have been trying to discover if this is a setting I somehow accidentally turned on, but have found nothing.

The fill style goes away if the Sublime error console is open (ctrl + `), but comes back once that is closed. The only error or warning in debug mode is a note about skipping an automatic upgrade. 

I apologize if this is not the result of a bug, but of my own stupidity, however I did not see anything in the documentation or the Google group that explained this, and this seemed to be the only other place to turn to for help.

![sublimelinter-fill](https://cloud.githubusercontent.com/assets/39103/6361441/47bd815e-bc50-11e4-813c-646054612c44.png)

**Comment by skj3gg** [comment]
I'm sorry I can't seem to replicate this issue. When you restart Sublime does it continue to show the fill? Also what is your Lint Mode in?

**Comment by matthewcc** [comment]
Thank you for replying. It did not go away after restarting. I even tried uninstalling and reinstalling Sublime Linter. Then I noticed several days ago it had stopped doing that, and now I can't replicate it either.

I am using SublimeLinter-jshint.

I'm not sure what to make of it, except perhaps there is a conflict somewhere. I'm out of my depth even speculating, but perhaps there are settings from different projects conflicting, or a local preference is conflicting with a global preference. 

I know that is not much help, but at least the issue has gone away. And thanks again for replying.

**Comment by skj3gg** [comment]
It happens more often than not. Thanks for using SL!

I'm going to close this but it can be opened once it is reproducible.
