### ISSUE TITLE
New linter: SublimeLinter-contrib-scalastyle

### ISSUE THREAD

**Issue by jawshooah** [SublimeLinter/SublimeLinter3#205]
https://github.com/jawshooah/SublimeLinter-contrib-scalastyle

This linter provides an interface to [Scalastyle](http://www.scalastyle.org).

**Comment by skj3gg** [comment]
Release and you are ready, thanks!

**Comment by jawshooah** [comment]
@skj3gg Release pushed, ready for landing.

**Comment by skj3gg** [comment]
Wheels down, nice flying!
