### ISSUE TITLE
jshint options aren't registering

### ISSUE THREAD

**Issue by jahmezz** [SublimeLinter/SublimeLinter3#206]
I am having a problem getting SublimeLinter's options to change how JSHint works. I want to automatically register console, document, sessionStorage, etc. as globals with devel: true and browser: true, but any updates I make to SublimeLinter's options do not seem to change JSHint. In-line options work, but not the user settings.

Where do I place these settings? Here is my user settings file.

![options](https://cloud.githubusercontent.com/assets/3815472/6424281/ae4a6a70-beaa-11e4-8b86-e33e9624050f.png)

It would be nice to have a template user settings file so I knew exactly how to input these settings.

**Comment by skj3gg** [comment]
The problem is that this is not howSL-JSHint. The configuration has to be done in the `.jshintrc` file just like in the conmand line. See the SL-JSHint readme for more information on this.
