### ISSUE TITLE
New linter: SublimeLinter-contrib-ruby-lint

### ISSUE THREAD

**Issue by jawshooah** [SublimeLinter/SublimeLinter3#210]
https://github.com/jawshooah/SublimeLinter-contrib-ruby-lint

This linter provides an interface to [ruby-lint](https://github.com/YorickPeterse/ruby-lint).

**Comment by skj3gg** [comment]
:disappointed: I'm sorry this one slipped by me... Everything looks good, the codacy badge is broken though. Please make a release and I'll get this out asap.

**Comment by jawshooah** [comment]
No worries! I've been busy too. Codacy badge works fine for me, what happens when you click it?

**Comment by skj3gg** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/f638e6e98dcd5a4819da12556f6b1b1dd24c3e8e

Thanks!
