### ISSUE TITLE
SublimeLinter not available to install

### ISSUE THREAD

**Issue by zerodburn** [SublimeLinter/SublimeLinter3#211]
Hi, I wanted to try out SublimeLinter today as I heard about it on a blog post. However, when I try and install from packagecontrol I can only see packages which have -language or -contrib-lanugage after SublimeLinter, I can't see the main SublimeLinter package anywhere.

I'm using Sublime Text 3 build 3065 (latest).

**Comment by skj3gg** [comment]
Package Control is pretty fragile and this commonly happens, Make sure you don't have it already installed in your Packages directory. If it isn't there you could try quiting SublimeText and trying again in an hour or so. It is sometimes good to do a clean install of Package Control or even SublimeText itself.

Sorry this happens, but https://packagecontrol.io/packages/SublimeLinter would show something if the package was missing so there is nothing I can do to fix this.

**Comment by jawshooah** [comment]
@zerodburn Is SublimeLinter still not showing up for you after following @skj3gg's suggestions?

**Comment by skj3gg** [comment]
@zerodburn Were you able to install SublimeLinter?

**Comment by haberdashPI** [comment]
I just tried a clean install of sublime text 3 (clearing the Mac OS X's) and still could not install SublimeLinter.
