### ISSUE TITLE
Passive Warnings Setting Per Linter

### ISSUE THREAD

**Issue by doctorallen** [SublimeLinter/SublimeLinter3#212]
I noticed in the documentation it says that each linter can have it's own settings. However when I try to add "passive_warnings" in the annotations linter, it doesn't seem to work.

Is it possible to set passive warnings per linter? If not, it would be a pretty awesome feature.

**Comment by skj3gg** [comment]
No, currently it's an all or nothing on the `passive_warnings` setting. Feel free to consider contributing this though, it wouldn't be too hard to accomplish.

**Comment by doctorallen** [comment]
Forgive me since I've never worked with Python before, but how can I determine which linter provided the error?

I think I figured out where I should be working on this: commands.py:236, but I haven't been able to figure out if there is a linter property. I found the HighlightSet and Highlight classes, but I don't think I see anything in there to determine the linter.

Am I on the right track?

**Comment by braver** [comment]
The SL4 beta provides this feature via filters on the output panel, check it out!  https://github.com/SublimeLinter/SublimeLinter3#sublimelinter-4-beta
