### ISSUE TITLE
clang linter showing errors that compiler doesn't show

### ISSUE THREAD

**Issue by ryanrudzitis** [SublimeLinter/SublimeLinter3#214]
I am using the clang linter in Sublime Text 3.

The linter is showing the warning "implicit declaration of foo is invalid in C99". The compiler doesn't catch this.

The linter is also showing the error "unknown type name foo". Again, the compiler doesn't report this and the program runs fine.

Is there anything I can do to get the linter to stop showing these invalid warnings and errors?

**Comment by jawshooah** [comment]
`SublimeLinter-clang` runs `clang` with some options you may not be using in your standard build. Try running [this command](https://github.com/nirm03/SublimeLinter-clang/blob/master/linter.py#L36) on the file and see if you get the same warnings.

This issue probably should have been filed on the linter repo, btw.

**Comment by jawshooah** [comment]
Hmm, seems the maintainer hasn't been active in quite some time. @skj3gg, is there any way to transfer ownership of the linter?

**Comment by ryanrudzitis** [comment]
@jawshooah sorry, I probably should have mentioned that I am using gcc to compile. Running that command that you lined to doesn't make a difference.

**Comment by skj3gg** [comment]
No I have no control over it, it is a contrib linter run by @nirm03. if you haven't already you should checkout [troubleshooting](https://github.com/nirm03/SublimeLinter-clang/blob/master/README.md#troubleshooting) and settings documentation for that linter's README

**Comment by jawshooah** [comment]
Regardless, if there are specific warnings you want to ignore, you can use the [`ignore_match`](http://www.sublimelinter.com/en/latest/linter_settings.html#ignore-match) linter setting.

**Comment by jawshooah** [comment]
@ryanrudzitis Are you still having trouble with `ignore_match` set appropriately?

**Comment by ryanrudzitis** [comment]
Yeah I still have the problem. 



Ryan Rudzitis

**Comment by jawshooah** [comment]
Could you post a minimal snippet of code that gives you the error, along with the ST console log output? (Might be helpful to set `debug` to `true` in the SublimeLinter settings)

Also the specific `gcc` flags you're using to compile by hand?

**Comment by ryanrudzitis** [comment]
Actually... I had closed all the C files that I was working with last night. I opened them back up in Sublime Text and the errors are not there anymore. Weird.

**Comment by skj3gg** [comment]
It happens a lot. Glad this was "resolved" for you.
