### ISSUE TITLE
SublimeLinter-jolint

### ISSUE THREAD

**Issue by thesave** [SublimeLinter/SublimeLinter3#220]
Hi,

I would like to submit the plugin for jolint, a linter for the Jolie language.

Repository:  https://github.com/thesave/SublimeLinter-jolint

Thank you for your time

**Comment by skj3gg** [comment]
Since your aren't initializing them, lines 31-36 of `linter.py` are not needed. Additionally line 19 should be removed, or at least given more context. After that, please make your `1.0.0` release and I'll add it to our `package_control_channel`

**Comment by thesave** [comment]
I think I made the right changes.
Thanks.

**Comment by skj3gg** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/bd0fdeea449073c1211a4185b3bbd3bbaed8c301

Should be in PC in less than an hour.

Thanks!

**Comment by jawshooah** [comment]
Just one other thing: your [`install.txt`](https://github.com/thesave/SublimeLinter-jolint/blob/master/messages/install.txt#L10) appears to have an incorrect URL for your repository.

**Comment by skj3gg** [comment]
I knew I forgot to mention something. Yeah your repository and its url are wrong in your installation message.

**Comment by thesave** [comment]
Thank you very much for noticing it and letting me know.
I just committed the change.

**Comment by jawshooah** [comment]
No problem! You'll also need to push a new release in order for it to show up in Package Control.
