### ISSUE TITLE
New linter: SublimeLinter-contrib-stylint

### ISSUE THREAD

**Issue by jackbrewer** [SublimeLinter/SublimeLinter3#223]
[https://github.com/jackbrewer/SublimeLinter-contrib-stylint](https://github.com/jackbrewer/SublimeLinter-contrib-stylint)

This linter provides an interface to the [Stylint](https://github.com/rossPatton/stylint) linter for Stylus.

![a703d200-cd79-11e4-86ee-a9fc50e43e23](https://cloud.githubusercontent.com/assets/720908/6801570/dfb91de8-d220-11e4-9bf2-c40f9608bb08.gif)

**Comment by vaishal** [comment]
Any chance of reviewing this? Would like to be able to use it.

**Comment by benedfit** [comment]
:+1:

**Comment by skj3gg** [comment]
Linters that inherit from NodeLinter must override one more variable, which is `npm_name`. This is a string of the projects name in NPM. In this case

```python
npm_name = 'stylint'
```

After that, make a release and I'll add it to the package manager.

**Comment by jackbrewer** [comment]
Thanks for the feedback.

I've [added the variable](https://github.com/jackbrewer/SublimeLinter-contrib-stylint/commit/5cfa0b6da0b744df02ac67b56ea5c57882b93499) as requested and have pushed a 1.0.0 tag.

**Comment by jackbrewer** [comment]
Hi @skj3gg, any chance of this moving along?

**Comment by skj3gg** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/2a771a5834538dcb7db383c4d705a58fce8677a6

Sorry for taking so long. Thank you for your contributions!
