### ISSUE TITLE
"@python" setting does not work properly in multi-drive situation on Windows

### ISSUE THREAD

**Issue by jsza** [SublimeLinter/SublimeLinter3#226]
Assuming these SublimeLinter settings:

```
{
    "@python": "2.7"
}
```

If your Python install is located at `C:\Python27` and you are editing a file on another drive (eg. `D:\foo.py`), it will incorrectly search the root of `D:\` for Python27.

I would like to suggest a new setting for specifying an absolute python executable path.

**Comment by aawilson** [comment]
Seconded, I'm having a devil of a time trying to get SublimeLinter to execute the Python I want (on windows) with the meta config option, and zero luck.

**Comment by alexandrul** [comment]
Could you check if this patch solves your issue? https://github.com/SublimeLinter/SublimeLinter3/pull/401

You can manually apply it to ```<ST# folder>\Data\Packages\SublimeLinter\lint\util.py```

**Comment by aawilson** [comment]
This does solve one issue (which is the one jsza explicitly points out). But my problem is the more general version of it--if I have Python installed at, say, `f:\randomdir\Python`, SublimeLinter has no way for me to indicate that.

**Comment by groteworld** [comment]
Seeing as this one is solved by #401, I am going to close this on it's merge. @aawilson's comments is really a different issue, and a new issue should be made for ability to specify directories other than root for windows python installs.

**Comment by aawilson** [comment]
Sure.
