### ISSUE TITLE
Header file breaks functionality - Linter crashes with IndexError

### ISSUE THREAD

**Issue by kgizdov** [SublimeLinter/SublimeLinter3#228]
Hi,

I have a very strange problem.

**EDIT:** It turns out that if I comment out the include for the header file, the liner works again. Also, if the include points to a header that doesn't exist, the linter works - otherwise it fails... This is a huge blocking bug, I think.

I am using `SublimeLinter` with `cpplint` and `cppcheck` on a C/C++ project. The linters both work in all files except the `main.c` file. What is even more weird is that if I copy the file outside the folder, the linters work. If I rename the file and keep it in the same folder, the linters do not work. If I rename and move, it's fine.

I am completely confused by this. The original error I got was `IndexError: list index out of range` and after I switched the debug mode on I got the following:

    SublimeLinter: cppcheck activated: /usr/bin/cppcheck
    SublimeLinter: cpplint activated: /usr/local/bin/cpplint
    [WakaTime] Initializing WakaTime plugin v3.0.13
    SublimeLinter: found existing Rails syntax, version 1
    SublimeLinter: found existing HTML syntax, version 3
    SublimeLinter: cppcheck: main.c ['/usr/bin/cppcheck', '--template=gcc', '--inline-suppr', '--quiet', '--enable=style', '@']
    SublimeLinter: cppcheck output:
    helper.h:544: performance: Variable 'var' is reassigned a value before the old one has been used.
    helper.h:453: style: The scope of the variable 'px' can be reduced.
    helper.h:453: style: The scope of the variable 'py' can be reduced.
    helper.h:453: style: The scope of the variable 'pz' can be reduced.
    helper.h:453: style: The scope of the variable 'mass' can be reduced.
    helper.h:453: style: The scope of the variable 'totalSpeed' can be reduced.
    helper.h:453: style: The scope of the variable 'relativisticAjust' can be reduced.
    helper.h:454: style: The scope of the variable 'i' can be reduced.
    helper.h:509: style: The scope of the variable 'DistanceSquared' can be reduced.
    helper.h:509: style: The scope of the variable 'force' can be reduced.
    helper.h:207: style: Unused variable: regulator
    helper.h:494: style: Unused variable: distance
    helper.h:539: style: Unused variable: i
    helper.h:597: style: Unused variable: j
    helper.h:598: style: Unused variable: dist2
    /tmp/SublimeLinter3-gizdov/main.cpp:122: style: Variable 'f' is assigned a value that is never used.
    /tmp/SublimeLinter3-gizdov/main.cpp:191: style: Unused variable: r
    /tmp/SublimeLinter3-gizdov/main.cpp:191: style: Unused variable: g
    /tmp/SublimeLinter3-gizdov/main.cpp:191: style: Unused variable: b
    /tmp/SublimeLinter3-gizdov/main.cpp:192: style: Unused variable: pRGB
    /tmp/SublimeLinter3-gizdov/main.cpp:193: style: Unused variable: acel
    /tmp/SublimeLinter3-gizdov/main.cpp:195: style: Unused variable: buf
    /tmp/SublimeLinter3-gizdov/main.cpp:262: style: Unused variable: k
    /tmp/SublimeLinter3-gizdov/main.cpp:392: style: Unused variable: i
    /tmp/SublimeLinter3-gizdov/main.cpp:392: style: Variable 'frame' is assigned a value that is never used.
    SublimeLinter: error in SublimeLinter daemon:
    SublimeLinter: --------------------
    SublimeLinter: Traceback (most recent call last):
      File "/home/gizdov/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 58, in loop
        item = self.q.get(block=True, timeout=self.MIN_DELAY)
      File "./queue.py", line 175, in get
    queue.Empty

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/gizdov/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 66, in loop
        self.lint(view_id, timestamp)
      File "/home/gizdov/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 112, in lint
        self.callback(view_id, timestamp)
      File "/home/gizdov/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 123, in lint
        Linter.lint_view(view, filename, code, hit_time, callback)
      File "/home/gizdov/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 917, in lint_view
        linter.lint(hit_time)
      File "/home/gizdov/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 1387, in lint
        self.highlight.range(line, pos, length=0, error_type=error_type, word_re=self.word_re)
      File "/home/gizdov/.config/sublime-text-3/Packages/SublimeLinter/lint/highlight.py", line 234, in range
        start, end = self.full_line(line)
      File "/home/gizdov/.config/sublime-text-3/Packages/SublimeLinter/lint/highlight.py", line 202, in full_line
        start = self.newlines[line] + char_offset
    IndexError: list index out of range

    SublimeLinter: --------------------

Seems like the linters work, but then the output fails for some reason. I am completely out of my depth here. Any help is much appreciated.

Thanks.

**Comment by jawshooah** [comment]
This seems to be similar to #227. `cppcheck` checks included header files in addition to the linted file itself, which means it requires a full directory context and can't simply lint temporary files.

I'll submit a PR over at [SublimeLinter-cppcheck](https://github.com/SublimeLinter/SublimeLinter-cppcheck) with a fix.

Do you have similar problems when you only have `cpplint` enabled? After some cursory testing, `cpplint` doesn't appear to recurse into header files.

**Comment by NotSqrt** [comment]
The fix for SublimeLinter-cppcheck has been released.

Is this issue still relevant ?

**Comment by kgizdov** [comment]
I'm currently on holiday. I'll test it by the end of the week.

**Comment by kgizdov** [comment]
Seems to be working now. Thanks
