### ISSUE TITLE
Support nested package.json detection for npm modules

### ISSUE THREAD

**Issue by glenjamin** [SublimeLinter/SublimeLinter3#229]
I have a project that looks like this:

```
.eslintrc
package.json
node_modules/.bin/eslint
sub-project
- package.json
- some-js-file.js
```

The general idea is that sub-projects share the parent repository and linting settings to ensure they stay consistent across the major project.

The existing logic to detect node binaries stops at the first package.json it finds. Could it be expanded to continue upwards when looking for a binary?

**Comment by jawshooah** [comment]
Hmm, I've never seen this kind of setup before, and I'm not sure whether it's common enough to justify the added complexity. @skj3gg, what do you think?

**Comment by skj3gg** [comment]
I'd be willing to see this implemented, but I think for the sake of the system, you would have to be in a `.sublime-project` so that we would stop searching in the root of the project. @malandrew may have a better idea for this than I.

**Comment by jawshooah** [comment]
@glenjamin, shouldn't the subproject's `package.json` include the `eslint` dependency? Why split your project into subprojects unless each subproject can operate independently of the superproject?

**Comment by glenjamin** [comment]
They can all run independently, but the build / lint stuff is done as a package.

It's not a great system, but has been working quite well.

I'm open to hearing good suggestions for keeping multiple projects in-sync!

**Comment by jawshooah** [comment]
So each subproject's `package.json` has its own `dependencies`, but only the superproject has `devDependencies`?

**Comment by glenjamin** [comment]
Test dependencies are per-project, but linting & building a deployable is
global.

**Comment by jawshooah** [comment]
Gotcha. I'd be inclined to keep all dependencies local to each subproject, be they for linting, building or testing, but it's not my project :wink: 

I like @skj3gg's suggestion of supporting this kind of setup only within a `.sublime-project`.

**Comment by tommmyy** [comment]
+1

**Comment by benmosher** [comment]
:+1: I'm up for attempting a PR if the powers that be (i.e. whomever has the power to merge) agrees that the behavior can change from:

- search for the nearest `package.json`

to 

- search for the nearest `package.json` with the linter as a dependency, up to the root of the `.sublime-project`

where 'nearest' is defined as closest ancestor, starting with siblings.

**Comment by tnrich** [comment]
+1 for the proposed fix.
I would agree that it might not be the most common project configuration, but I personally expected the linter to follow node-like module loading such that it moves up a level if it can't find a particular package. Is there any reason Sublime Linter wouldn't adhere to node-like conventions? Most of the linter packages I've seen are installed using npm.

**Comment by groteworld** [comment]
@benmosher I'm not against that pull request. :beers:

**Comment by benmosher** [comment]
Sweet, I'll take a stab at it. I'm hoping there might be a simple way to outsource finding the right executable to [`npm-which`].

Or at least emulate the same behavior. 

[`npm-which`]: https://github.com/timoxley/npm-which

**Comment by dozoisch** [comment]
@benmosher ah that would save me a lot of time!

**Comment by benmosher** [comment]
PR'd!

It was not clear to me how to know where the project file was located, so I just replicated the same ancestor search that the `package.json`-finder used. If some can direct me to that, I can amend the PR. Seemed to work pretty well for me as-is, though.

**Comment by e-cloud** [comment]
@benmosher , that's great.
i don't know python. but i could understand what yours code does.
is there one little point missing -- searching for the global installed `node_modules`?

**Comment by e-cloud** [comment]
BTW, @groteworld , could you review this issue and take a look at benmosher's PR?
Expecting a release ASAP! :smile:

**Comment by benmosher** [comment]
I believe I left the parts that normally handle looking in the system `bin` untouched. I could be wrong, though. 😅
