### ISSUE TITLE
I'm sure this would have a fix but have searched everywhere and can't find it.

### ISSUE THREAD

**Issue by garhbod** [SublimeLinter/SublimeLinter3#230]
Getting the following error and yes jshint works fine from command line. 

SublimeLinter: ERROR: could not launch ['C:\Users\UserName\AppData\Roaming\npm\jshint.cmd', '--version'] 

The full dump from startup to error is as follows

DPI scale: 1
startup, version: 3083 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/UserName/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/UserName/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/UserName/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage", "Markdown"]
pre session restore time: 0.27148
startup time: 0.34348
first paint time: 0.34548
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin CSS3.css3_completions
reloading plugin CSS3.rgb_to_hex
reloading plugin CSS3.validator
reloading plugin DocBlockr.**init**
reloading plugin DocBlockr.jsdocs
reloading plugin Emmet.emmet-plugin
reloading plugin LESS.less_completions
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeLinter-csslint.linter
SublimeLinter: csslint linter loaded 
reloading plugin SublimeLinter-jshint.linter
SublimeLinter: jshint linter loaded 
reloading plugin SublimeLinter-json.linter
SublimeLinter: json linter loaded 
reloading plugin SublimeLinter-php.linter
SublimeLinter: php linter loaded 
reloading plugin CSScomb.CSScomb
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: c:\users\ryan\appdata\local\temp\SublimeLinter3-UserName 
SublimeLinter: computed PATH from system:
C:\ProgramData\Oracle\Java\javapath
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Program Files (x86)\ActiveState Komodo Edit 6\
C:\Program Files (x86)\Common Files\Intel\Shared Files\cpp\bin\Intel64
C:\Program Files\Common Files\Microsoft Shared\Windows Live
C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live
C:\windows\system32
C:\windows
C:\windows\System32\Wbem
C:\windows\System32\WindowsPowerShell\v1.0\
C:\Program Files (x86)\Toshiba\Bluetooth Toshiba Stack\sys\
C:\Program Files (x86)\Toshiba\Bluetooth Toshiba Stack\sys\x64\
c:\Program Files (x86)\Common Files\Ulead Systems\MPEG
C:\Program Files (x86)\Windows Live\Shared
C:\Program Files\Microsoft SQL Server\110\Tools\Binn\
C:\wamp\bin\php\php5.5.12
C:\ProgramData\ComposerSetup\bin
C:\Users\UserName\AppData\Roaming\Composer\vendor\bin
C:\Program Files (x86)\Git\cmd
C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86
C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64
C:\Program Files\nodejs\
C:\Users\UserName\AppData\Roaming\npm

SublimeLinter: jshint version query: C:\Users\UserName\AppData\Roaming\npm\jshint.cmd --version 
SublimeLinter: ERROR: could not launch ['C:\Users\UserName\AppData\Roaming\npm\jshint.cmd', '--version'] 
SublimeLinter: reason: [WinError 2] The system cannot find the file specified 
SublimeLinter: PATH: C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\ActiveState Komodo Edit 6\;C:\Program Files (x86)\Common Files\Intel\Shared Files\cpp\bin\Intel64;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Toshiba\Bluetooth Toshiba Stack\sys\;C:\Program Files (x86)\Toshiba\Bluetooth Toshiba Stack\sys\x64\;c:\Program Files (x86)\Common Files\Ulead Systems\MPEG;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\wamp\bin\php\php5.5.12;C:\ProgramData\ComposerSetup\bin;C:\Users\UserName\AppData\Roaming\Composer\vendor\bin;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\nodejs\;C:\Users\UserName\AppData\Roaming\npm 
SublimeLinter: WARNING: no jshint version could be extracted from:

SublimeLinter: found existing HTML syntax, version 3 
SublimeLinter: found existing Rails syntax, version 1 
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2015-03-30 09:09:09, next run at 2015-03-30 10:09:09 or after

**Comment by skj3gg** [comment]
If you don't mind, what's the contents of your `%AppData%\Roaming\npm` directory

**Comment by garhbod** [comment]
![temp](https://cloud.githubusercontent.com/assets/4616198/6953242/62b74eea-d90b-11e4-8ad4-f6495fb28dae.png)

**Comment by braver** [comment]
@garhbod it's been a while... but are you still experiencing issues that we can help you work out?

**Comment by braver** [comment]
🤷‍♂️ We'll re-open if there's news.
