### ISSUE TITLE
Allow patterns in `ignore_match` to occur anywhere in a message

### ISSUE THREAD

**Issue by jawshooah** [SublimeLinter/SublimeLinter3#237]
As discovered in #236, patterns in [`ignore_match`](http://www.sublimelinter.com/en/latest/linter_settings.html#ignore-match) are [matched against messages](https://github.com/SublimeLinter/SublimeLinter3/blob/1e3741fa144ac3348513df17dc9240ed12a07541/lint/linter.py#L1330) using [`re.match()`](https://docs.python.org/2/library/re.html#re.match) instead of [`re.search()`](https://docs.python.org/2/library/re.html#re.search), which means that the pattern must occur _at the beginning_ of the message, rather than anywhere inside it.

I consider this unexpected behavior, and am inclined to switch to `re.search()`. @groteworld, what do you think?

**Comment by braver** [comment]
Guys, if this is still relevant 2.5 years later, let me know, but I'm closing it.
