### ISSUE TITLE
New linter: SublimeLinter-contrib-checkpatch

### ISSUE THREAD

**Issue by BrunoJJE** [SublimeLinter/SublimeLinter3#238]
This provides an interface to linux kernel [checkpatch.pl](http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/scripts/checkpatch.pl)

https://github.com/BrunoJJE/SublimeLinter-contrib-checkpatch

**Comment by skj3gg** [comment]
Thank you for being so patient with me. Please make a release and I will add it to Package Control.

**Comment by BrunoJJE** [comment]
You're welcome.
Tag 1.0.0 added.

**Comment by skj3gg** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/e729281505f78e65ebb8000017185c3d4558012f should see it in PC soon

**Comment by skj3gg** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/e729281505f78e65ebb8000017185c3d4558012f should see it in PC soon
