### ISSUE TITLE
SublimeLinter3 is displaying as "Removed" in package control site

### ISSUE THREAD

**Issue by fallroot** [SublimeLinter/SublimeLinter3#239]
It can be found https://packagecontrol.io/packages/SublimeLinter
So I can't find SublimeLinter in package list of package control and can't install.

**Comment by skj3gg** [comment]
Thanks @fallroot 

Been actually working on this for the last couple hours, hopefully will have this corrected for you soon.

**Comment by sethen** [comment]
Yeah getting the same here -- right in the middle of my dotfiles setup too... D'oh!

**Comment by blinskey** [comment]
For what it's worth -- I don't know how Package Control works -- I just tried to import my Sublime Text settings on a new install and encountered this error with many packages. I opened an [issue](https://github.com/wbond/package_control/issues/926) about this in the Package Control repo.

**Comment by skj3gg** [comment]
Currently all SublimeLinter packages are removed from Package Control and we are working to determine and correcting the issue. I'm sorry for any inconvenience and hope this will be resolved soon.

**Comment by skj3gg** [comment]
UPDATE: It appears the issue is within Package Control and hopefully it will be resolved soon. 

**Additionally, opening issues for every missing package is not necessary and is only causing overhead to manage.**

**Comment by mikulabc** [comment]
Thanks @skj3gg keep us updated :)

**Comment by skj3gg** [comment]
fixed.

https://github.com/wbond/package_control/issues/926
