### ISSUE TITLE
Toggle (enable/disable) specific linter

### ISSUE THREAD

**Issue by alehandrof** [SublimeLinter/SublimeLinter3#240]
I want to create a shortcut that toggles (enables/disables) a specific linter. Is this possible? I have looked through the docs and the issues here and I can't seem to figure it out.

**Comment by skj3gg** [comment]
You can now toggle linters by pressing <kbd>ctrl</kbd>+<kbd>super</kbd>+<kbd>t</kbd> on osx or <kbd>ctrl</kbd>+<kbd>k</kbd> and then <kbd>t</kbd> on linux or windows.

Soon as this release is published to Package Control. [SublimeLinter v3.4.39](https://github.com/SublimeLinter/SublimeLinter3/releases/tag/3.4.39)

**Comment by alehandrof** [comment]
Hey Blake. My original question wasn't very clear. I wasn't asking for a keybinding. I was asking about how to toggle a _specific_ linter. I'm fond of the [writegood](https://github.com/ckaznocha/SublimeLinter-contrib-write-good) linter. It's great when writing, but distracting when editing. I'm looking for a quick way to turn it on and off.

I was hoping that something like this might have worked:

```
{ "caption": "SublimeLinter: Toggle writegood", "command": "sublimelinter_toggle_linter", "args": {"which": "writegood"} },
```

I hope this makes sense. Sorry for not getting back sooner.

As for the keybinding... I think plugins should only provide example keybindings and leave it up to users to configure their own. Too many key conflicts otherwise. I would hate to be the cause of more conflicts in the world :p

**Comment by skj3gg** [comment]
No, you currently can't do that. Sorry for the confusion.

**Comment by jawshooah** [comment]
But feel free to submit a pull request if you'd like to implement the command yourself! :smile:

**Comment by alanjudson** [comment]
ctrl+super+t  - Not sure why - but my completely up-to-date SublimeText3 doesn't have lint toggling, and ctrl+super+t doesn't make any menu pop up?  Anyone else experience this?

**Comment by braver** [comment]
Eh, this is over 3 years old and we did a kinda big update somewhat recently. We don’t have linter toggling anymore, but we do have highlight toggling. @kaste has an add-on that toggles linters, not official or published though.

**Comment by kaste** [comment]
The toggler is maybe good and useful enough to get published. I use it very often. Can we add it to the SublimeLinter package control repo, or however that is named. I would actually appreciate a PR bc since I never did this it will take me probably an hour to get this done.

**Comment by braver** [comment]
@kaste transfer the repo to the SublimeLinter org (or to me) and I’ll make it so.

**Comment by alanjudson** [comment]
Thanks @kaste - it works really well for me :)
