### ISSUE TITLE
support to SublimeText portable

### ISSUE THREAD

**Issue by santospro** [SublimeLinter/SublimeLinter3#242]
Hi, how can I use this plugin in a portable version of SublimeText 3?

Thanks

**Comment by skj3gg** [comment]
If there isn't one already, create a `Packages` directory in `/path/to/portable/sublime/Data`, then clone SublimeLinter into that.

AFAIK, Package Control should still work in portable SublimeText.

**Comment by santospro** [comment]
Yep, thanks skj3gg for answer.
I had understood that SublimeLinter needs nodeJs to work. But I don't have the possibility to install nodeJs in my work computer. 

This is right?

**Comment by skj3gg** [comment]
Yes, that would be a problem.


You may want to search for a "portable node.js", or "running node.js from a usb" (as the concept applies the same).

**Comment by jawshooah** [comment]
To clarify, certain linters like SublimeLinter-jshint and SublimeLinter-csslint require NodeJS simply as a result of using the `jshint` and `csslint` executables, which are themselves scripts to be run in a NodeJS environment.

If you aren't using any linters that require NodeJS, then you don't need NodeJS to use SublimeLinter.

**Comment by skj3gg** [comment]
Thanks Josh!

Yeah, should have stated that's only if you are using a linter that requires node.js
