### ISSUE TITLE
Errors not being reported: SublimeLinter-ruby

### ISSUE THREAD

**Issue by ckib16** [SublimeLinter/SublimeLinter3#243]
Hello,

I've read thru the documentation and cannot seem to find a fix for getting `SublimeLinter` to correctly display errors when using my `SublimeLinter-ruby` linter package. No error are ever reported in any text entered. For example, entering random characters like `xgxgxgxg` shows no error. And the `Sublimelinter ` debug mode output to ST3 console always reports:  
```
SublimeLinter: ruby output:
Syntax OK 
```

[The only ruby linter issue on the deprecated Google Groups](https://groups.google.com/forum/#!searchin/sublimelinter/ruby/sublimelinter/cJahr5uruls/APbEvKHGJy0J) did not address my issue.  Below is my full ST3 console log along with several instances of reporting all syntax ok in a `user.rb` despite obvious errors and random characters being entered. I would appreciate any help that can be offered.  

Thanks,
Chris

------
startup, version: 3083 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/Chris/Library/Application Support/Sublime Text 3/Packages
state path: /Users/Chris/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/Chris/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage", "Markdown"]
pre session restore time: 0.58299
first paint time: 0.672252
startup time: 0.696846
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Alignment.Alignment
reloading plugin All Autocomplete.all_views_completions
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.ure
reloading plugin Browser Refresh.BrowserRefresh
reloading plugin Color Highlighter.ColorHighlighter
reloading plugin Color Highlighter.colors
reloading plugin GitGutter.git_gutter
reloading plugin GitGutter.git_gutter_change
reloading plugin GitGutter.git_gutter_compare
reloading plugin GitGutter.git_gutter_events
reloading plugin GitGutter.git_gutter_handler
reloading plugin GitGutter.git_helper
reloading plugin GitGutter.view_collection
reloading plugin MarkdownEditing.bootstrap
reloading plugin MarkdownEditing.custom_find_under_expand
reloading plugin MarkdownEditing.distraction_free_mode
reloading plugin MarkdownEditing.footnotes
reloading plugin MarkdownEditing.gather_missing_links
reloading plugin MarkdownEditing.indent_list_item
reloading plugin MarkdownEditing.indent_list_multiitem
reloading plugin MarkdownEditing.insert_references
reloading plugin MarkdownEditing.jumpToMarker
reloading plugin MarkdownEditing.lint
reloading plugin MarkdownEditing.list_markdown_references
reloading plugin MarkdownEditing.numbered_list
reloading plugin MarkdownEditing.paste_as_link
reloading plugin MarkdownEditing.paste_as_reference
reloading plugin MarkdownEditing.quote_indenting
reloading plugin MarkdownEditing.switch_list_bullet_type
reloading plugin MarkdownEditing.underlined_headers
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeLinter-ruby.linter
SublimeLinter: ruby linter loaded 
reloading plugin ColorPicker.sublimecp
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: /var/folders/b2/frmrc69500gftppkpdfvz_1c0000gn/T/SublimeLinter3-Chris 
SublimeLinter: user shell: /bin/bash 
SublimeLinter: computed PATH using /bin/bash:
/Users/Chris/.rvm/gems/ruby-2.1.2/bin
/Users/Chris/.rvm/gems/ruby-2.1.2@global/bin
/Users/Chris/.rvm/rubies/ruby-2.1.2/bin
/usr/local/bin
/usr/local/sbin
~/bin
/usr/local/bin
/usr/local/bin/subl
~/bin
/usr/local/bin
/usr/local/bin/sublime
~/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/opt/sm/bin
/opt/sm/pkg/active/bin
/opt/sm/pkg/active/sbin
/Users/Chris/.rvm/bin
 
SublimeLinter: ENV['GEM_HOME'] = '/Users/Chris/.rvm/gems/ruby-2.1.2' 
SublimeLinter: ruby activated: ['/Users/Chris/.rvm/bin/rvm-auto-ruby'] 
SublimeLinter: found existing HTML syntax, version 3 
SublimeLinter: found existing Rails syntax, version 1 
SublimeLinter: ruby: user.rb ['/Users/Chris/.rvm/bin/rvm-auto-ruby', '-wc'] 
SublimeLinter: ruby output:
Syntax OK 
no command for selector: noop:
Package Control: Skipping automatic upgrade, last run at 2015-04-16 20:16:08, next run at 2015-04-16 21:16:08 or after
SublimeLinter: ruby: user.rb ['/Users/Chris/.rvm/bin/rvm-auto-ruby', '-wc'] 
SublimeLinter: ruby output:
Syntax OK 
SublimeLinter: ruby: user.rb ['/Users/Chris/.rvm/bin/rvm-auto-ruby', '-wc'] 
SublimeLinter: ruby output:
Syntax OK 
SublimeLinter: ruby: user.rb ['/Users/Chris/.rvm/bin/rvm-auto-ruby', '-wc'] 
SublimeLinter: ruby: user.rb ['/Users/Chris/.rvm/bin/rvm-auto-ruby', '-wc'] 
SublimeLinter: ruby output:
Syntax OK 
SublimeLinter: ruby: user.rb ['/Users/Chris/.rvm/bin/rvm-auto-ruby', '-wc'] 
SublimeLinter: ruby output:
Syntax OK 
SublimeLinter: ruby: user.rb ['/Users/Chris/.rvm/bin/rvm-auto-ruby', '-wc'] 
SublimeLinter: ruby output:
Syntax OK

**Comment by jawshooah** [comment]
What's the output when you run `/Users/Chris/.rvm/bin/rvm-auto-ruby -wc user.rb` from the command line?

**Comment by jawshooah** [comment]
Also, in the future, please report any linter-specific issues on [their respective repos](https://github.com/SublimeLinter/SublimeLinter-ruby). This helps to prevent clutter in the core issue tracker, and places the issue closer to its root cause.

**Comment by skj3gg** [comment]
Josh, this may be a good thing to reference in the README, documentation and contributions file. I’m on the road right now, but can do it if you don’t get to it.

**Comment by ckib16** [comment]
Josh - understood, apologies, I did not see the linter-specific repo. I can move this if desired.

The output is:
```
$ /Users/Chris/.rvm/bin/rvm-auto-ruby -wc user.rb
ruby: No such file or directory -- user.rb (LoadError)
```

**Comment by jawshooah** [comment]
You'll have to specify the full path to `user.rb`. That or execute from its parent directory.

**Comment by ckib16** [comment]
Copy that standby 1 second...

**Comment by jawshooah** [comment]
Then there's no problem here. `ruby -wc` isn't picking up on any lint errors, so `SublimeLinter-ruby` has nothing to report.

**Comment by ckib16** [comment]
OK. I guess I misunderstood the error types that the linter will/will not report. Thanks for your time.

**Comment by jawshooah** [comment]
If you're looking for a strict style checker, you can try [RuboCop](https://github.com/bbatsov/rubocop) with  [SublimeLinter-rubocop](https://github.com/SublimeLinter/SublimeLinter-rubocop).
