### ISSUE TITLE
New linter: SublimeLinter-contrib-htmlhint

### ISSUE THREAD

**Issue by mmaday** [SublimeLinter/SublimeLinter3#245]
https://github.com/mmaday/SublimeLinter-contrib-htmlhint

This linter provides an interface to [HTMLHint](http://htmlhint.com/).
![sublimelinter-htmlhint-errors](https://cloud.githubusercontent.com/assets/1237074/7211705/a892047e-e512-11e4-9029-9c0e3f0ad2fa.gif)

**Comment by jawshooah** [comment]
A few comments:

### README.md
The htmlhint link on the first line should point to the [htmlhint](https://github.com/yaniswang/htmlhint) repo.

### linter.py
> ```python
from SublimeLinter.lint import Linter, util, persist
```

You're not using `util`, no need to import it.

 > ```python
cmd = 'htmlhint'
executable = None
```

These should be reversed. That is, set `cmd = None` and `executable = 'htmlhint'`. This doesn't change behavior, but is a good convention to follow since you're not doing anything special with `cmd`.

> ```python
split = super().split_match(match)
...
split = (split[0], split[1], split[2], False, True, split[5], split[6])
```

I'd recommend pattern-matching the output of `super().split_match(match)` as follows for better readability:

```python
match, line, col, error, warning, message, near = super().split_match(match)
...
split = (match, line, col, False, True, message, near)
```

**Comment by skj3gg** [comment]
Any progress on this @mmaday?

**Comment by mmaday** [comment]
@jawshooah I'm finally back after a long vacation.  Thanks for the feedback.  I've cleaned things up.  I honored all your feedback in the code save for the following:
```python
cmd = None
executable = 'htmlhint'
````

This was not working for me.  The linter gets loaded, but it errors out when attempting to run it with the following error message:
````
SublimeLinter: htmlhint linter reloaded 
reloading plugin SublimeLinter-contrib-htmlhint.linter
SublimeLinter: htmlhint version query: /usr/local/bin/htmlhint --version 
SublimeLinter: htmlhint version: 0.9.7 
SublimeLinter: htmlhint: (>= 0.9.0) satisfied by 0.9.7 
SublimeLinter: htmlhint activated: /usr/local/bin/htmlhint 
SublimeLinter: htmlhint linter reloaded 
SublimeLinter: htmlhint: interestSurveyResults.html <builtin> 
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 256, in on_post_save
    callback.on_post_save(v)
  File "/Users/mmaday/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 445, in on_post_save
    self.file_was_saved(view)
  File "/Users/mmaday/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 470, in file_was_saved
    self.lint(vid)
  File "/Users/mmaday/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 123, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/Users/mmaday/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 919, in lint_view
    linter.lint(hit_time)
  File "/Users/mmaday/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1375, in lint
    output = self.run(cmd, self.code)
  File "/Users/mmaday/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1782, in run
    return self.communicate(cmd)
  File "/Users/mmaday/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1805, in communicate
    if '@' in cmd:
TypeError: argument of type 'NoneType' is not iterable
````

Please have a look and let me know what you think.

Thanks,

-Mark

**Comment by jawshooah** [comment]
Argh, that was my mistake, sorry! You did the right thing. Documentation for `cmd` is [here](http://www.sublimelinter.com/en/latest/linter_attributes.html#cmd).

As noted in the [documentation](http://www.sublimelinter.com/en/latest/linter_attributes.html#executable) for `executable`, you don't need to define it at all as long as the first (and only, in this case) element in `cmd` is the executable.

**Comment by mmaday** [comment]
@jawshooah Sounds good. Am I clear to tag and pull on the package control channel?

**Comment by jawshooah** [comment]
Yup, go right ahead.

**Comment by skj3gg** [comment]
Thanks @mmaday for your contribution!
