### ISSUE TITLE
Do linters run in parallel?

### ISSUE THREAD

**Issue by ben-ng** [SublimeLinter/SublimeLinter3#247]
I'm having trouble navigating this project to get the answer I want. It looks like linters run in a separate thread, but if multiple linters run for a single file, do they run in series in that thread, or in parallel in multiple threads?

**Comment by braver** [comment]
@groteworld perhaps you have a short answer for this?

**Comment by groteworld** [comment]
They run in series, this order is defined by what linter registers with the `persist` module of SL3 first. The order of what plugin loads first, and whether that is a parallel race-condition or ordered by some means in serial, is above my knowledge of SublimeTest.

**Comment by braver** [comment]
Neat!
