### ISSUE TITLE
What's the difference between "Disable Linter" and "Disable Linting"?

### ISSUE THREAD

**Issue by callumlocke** [SublimeLinter/SublimeLinter3#248]
![image](https://cloud.githubusercontent.com/assets/250617/7274074/a5de23ec-e8f1-11e4-91e3-747a27121a69.png)

Can you change the wording to clarify what each command does? Maybe "Disable a linter" and "Disable all linting" (if that's what they mean).

**Comment by skj3gg** [comment]
Disable Linting is disabling linting over everything, and you won't see any gutter info or overlays from SL. 

Disable Linter would be disabling of a specific linter. Click it would open up a new palette that allows you to choose which linter to disable.
