### ISSUE TITLE
Allow a dict of regex

### ISSUE THREAD

**Issue by ismell** [SublimeLinter/SublimeLinter3#249]
It would be nice to have different regexp based off the syntax.

e.g)

    regex = {
        'java': r'^.*\.java:(?P<line>\d+):(?P<col>\d+):\s+(?P<message>.*)$',
        'html': r'.....'
    }

**Comment by jawshooah** [comment]
Interesting idea, but what's the use case? Do you have a linter that lints both Java and HTML?

**Comment by ismell** [comment]
We have an internal linter that proxies to one of 40 different linters. This allows us to never have to remember which linter we are supposed to call. e.g)

    lint blah.java
    lint foo.r
    lint a.ps

The problem is that each linter outputs errors in a slightly different format.

**Comment by jawshooah** [comment]
Gotcha. At a glance, it seems like such a change would require some fairly significant refactoring of the base `Linter` class, and I'm not convinced that this is a common enough use case to warrant such a change. @skj3gg, any thoughts?

**Comment by skj3gg** [comment]
Sorry. I don't think this fits a common enough need to be introduced main branch. But this is an open source project so you have all the code  and it would be something that you could do for your internal system.
