### ISSUE TITLE
Demote errors to warnings?

### ISSUE THREAD

**Issue by brocoli** [SublimeLinter/SublimeLinter3#252]
We have the ability to ignore pattern-matched errors, but not to demote them to warnings. This would be useful because we can configure SublimeLinter to show errors on save with passive warnings. This way low-priority problems can be marked, but won't get in the way when saving the file.

The code for implementing this is almost the same as the code for the ignore_match setting. I made a pull request that implements this one month ago (it's sitting there).

**Comment by skj3gg** [comment]
#221 merged. Thanks again!
