### ISSUE TITLE
New linter: SublimeLinter-contrib-slim-lint

### ISSUE THREAD

**Issue by elstgav** [SublimeLinter/SublimeLinter3#262]
https://github.com/elstgav/SublimeLinter-slim-lint

This linter provides an interface to [slim-lint](https://github.com/sds/slim-lint)

**Comment by skj3gg** [comment]
Please fix the 3rd install instruction in the README and make your first release. Thanks!

**Comment by elstgav** [comment]
Done

**Comment by Zyphrax** [comment]
Nice work, looking forward to this one.
@skj3gg could you please add it?

**Comment by jawshooah** [comment]
@Zyphrax Until it has been added to the Package Control registry, you can install it just like any other custom Sublime Text plugin. Clone the repository in your `Packages` directory.

**Comment by Zyphrax** [comment]
@jawshooah Thanks! I knew that installation method for regular Sublime packages, but I didn't know that it would work for Sublime Linters :)

@elstgav Thanks for creating the linter, works great!

**Comment by skj3gg** [comment]
Forgot to update this, this has been pushed. Thanks!

https://github.com/SublimeLinter/package_control_channel/commit/ea09bf76e9436f815c3b08d3d5b6cba90e86a560
