### ISSUE TITLE
Issue with passive_warnings

### ISSUE THREAD

**Issue by paradox41** [SublimeLinter/SublimeLinter3#265]
I have tried reinstalling and restarting sublime to see if this would resolve itself but it hasn't so I am opening an issue here. I also blasted away my user settings (and then reinstalled) with no luck.

Basically, the `passive_warnings` setting doesn't seem to be working. According to [my understanding](http://www.sublimelinter.com/en/latest/global_settings.html?highlight=passive_warnings#passive-warnings) it should prevent the "Quick Panel" from opening whenever there is an error. So far, the quick panel opens every time I save a file and there are errors. This occurs with both the pep8 and jshint linters.

Here is my settings file: https://gist.github.com/paradox41/f91268a1115c2b657879

I will be more than happy to provide any more information if necessary.

**Comment by skj3gg** [comment]
Hey @paradox41,

This brings up the question if you are seeing "warnings" or "errors". `passive_warnings` hides only warnings(yellow) while errors(red) still will show up. If you are seeing warnings in the Quick Panel when `passive_warnings` is on then that would be a bug. This may just be my misunderstanding of you issue though.

**Comment by paradox41** [comment]
Okay, so I think that is my misunderstanding then, I think what I am seeing is an error (red).

Is there any way to stop the quick panel from showing up at all? I guess that is what I'd really like.

Thank you for the clarification though.

**Comment by skj3gg** [comment]
No problem, glad we figured it out! Turn `show_errors_on_save` to false.

Thanks! Going to close this.

**Comment by paradox41** [comment]
Great! Thank you
