### ISSUE TITLE
Auto-detect used linters based on dotfiles

### ISSUE THREAD

**Issue by silverwind** [SublimeLinter/SublimeLinter3#266]
Some of my projects use `jshint`, while other use `eslint` for JavaScript linting. Right now, one solution to this problem of double-linting is to disable unused linters either manually or through a `.sublimelinterrc` in each project's root.

I'm a bit reluctant to pollute my projects (and the projects I contribute to) with another dotfile, and would propose a mechanism which checks for the presence of linter-specific dotfiles (`.eslintrc` and `.jshintrc` in my case), only enable the linters whose dotfiles are present.

This would imply that SublimeLinter has some knowledge about which filenames the linter uses.

**Comment by sindresorhus** [comment]
:+1:

**Comment by braver** [comment]
Such very specific situations is what the existing configuration files are for. You might raise this with the eslint and jshint linter plugins, perhaps they can add a setting that makes them run only if a config file is present. From the SL perspective this is a won't fix though.
