### ISSUE TITLE
Allow async execution of linting on load/save

### ISSUE THREAD

**Issue by twolfson** [SublimeLinter/SublimeLinter3#267]
I am transitioning from ST2 to ST3. I prefer to lint on load/save because background will complain loudly about things I am typing (e.g. I am writing a string but haven't yet finished the end quote).

I am noticing a significant freeze whenever saving a file when the Sublime Linter runs (e.g. half a second). This freeze doesn't happen with background linting. Would it be possible to set up the same queue mechanism used for `background` on `load/save` setups? Or maybe leverage Sublime's `on_post_save_async` hook?

**Comment by twolfson** [comment]
Any word on this? It's been about 3 weeks since opening =/

**Comment by merutak** [comment]
I run it in background mode, and as long as I don't save it's fine; but here too, saving incurs a UI freeze of 1-2 seconds.

**Comment by daboross** [comment]
For me sublime text also freezes when in manual mode as well as when it's set to lint on save. The freezing lasts for 8-11 seconds when building large projects (just as long as the compiler takes to build), and is quite inconvenient with `save_on_focus_lost` set to true in sublime.

**Comment by grotewold** [comment]
https://github.com/SublimeLinter/SublimeLinter3/pull/271 has been merged and I believe it resolves this issue, thank you for your patience.

**Comment by twolfson** [comment]
Woot, thank you =)

**Comment by evenfrost** [comment]
Is it somehow possible to get rid the freeze when `show_errors_on_save` is true?

**Comment by grotewold** [comment]
@evenfrost Good question!

Doing so could increase the amount of stale errors shown in the command palette. This action is, by its very nature, a synchronized task. You're asking the application to respond immediately with the information, but some linters take a while to run causing the freezing.

One way to think about it is imagining that there is someone whose linter takes 30 seconds to run (and for the sake of example, this is ok for them). That is 30 seconds of frozen time but then get the results back on the current state of the file. On the other hand, an asynchronous run of their linter would cause the errors shown to be 30 seconds of coding behind the current state. Not even mentioning additional saves happening within that time.

If you can think of a better solution, I'd be interested to hear it. I'm just stating the methodology behind the current design.

**Comment by evenfrost** [comment]
This makes sense, thanks for the response.

**Comment by grotewold** [comment]
@evenfrost Thank you as well! Questions like that help find the problems in the codebase, and make sure we are thinking of reason why we do things certain ways. :beers: Cheers!
