### ISSUE TITLE
Prevent save on a linting error

### ISSUE THREAD

**Issue by gaearon** [SublimeLinter/SublimeLinter3#268]
I'm using SublimeLinter `save` mode together with code hot reloading solutions like [React Hot Loader](http://gaearon.github.io/react-hot-loader/). I want the file to _not_ save if there's a linting error, as it allows to me to avoid messing up hot reloading in some cases. Is this possible? I'm willing to use a fork if the underlying ST API allows it, or maybe you'd be open to implementing such functionality.

Obviously such option would be off by default, and should probably not be enabled unless "show errors on save" is also enabled.

**Comment by NotSqrt** [comment]
Well, the way the linters work is usually to lint the file after it has been saved ..
(The background mode will send the content of the file to the compatible linters through stdin or a tmp file.)

**Comment by braver** [comment]
This is beyond the scope of SublimeLinter and not something I would encourage. Not allowing users to save files to disk just because a plugin says so introduces a risk (losing changes). I would expect the hot-reloading service to have a provision for this.
