### ISSUE TITLE
New linter: SublimeLinter-contrib-mdl

### ISSUE THREAD

**Issue by roadhump** [SublimeLinter/SublimeLinter3#269]
https://github.com/roadhump/SublimeLinter-contrib-mdl

This linter provides interface to Markdown Lint Tool https://github.com/mivok/markdownlint

**Comment by skj3gg** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/08d20f425dbe8a75f60d16c346dc34acdb7bedaa

Thank you, should be in package control shortly!
