### ISSUE TITLE
Updated linter:SublimeLinter-contrib-bootlint

### ISSUE THREAD

**Issue by pziegler** [SublimeLinter/SublimeLinter3#272]
https://github.com/pziegler/SublimeLinter-contrib-bootlint
the old one doesnt work with latest bootlint. i have created a PR to the original but it hasnt been pulled,not sure if he still maintains it

**Comment by grotewold** [comment]
I'm sorry I kind of ignored this issue. It was a tough decision to make, weather to replace the other one or not. For better or worse, I chose the latter. I'm feel bad that I left you hanging like this, but the number 1 rule of conflict resolution is to not start conflicts. I see your changes were push to master, so I'm closing this, but I wanted to extend an apology to you. I should have been open with you about how I felt about this change.

Thanks for using SublimeLinter, and contributing to this community! I appreciate it.
