### ISSUE TITLE
Per linter settings for error_color, warning_color and mark_style

### ISSUE THREAD

**Issue by IanCaunce** [SublimeLinter/SublimeLinter3#274]
It would be great to be able to customise these settings on a per linter basis as sometimes I run multiple linters on the same code. For example with php, I run the php, phpcs and phpmd linters. If I could customise what colors were displays, I could immediately see which linter caused the issue. 

In the case of the phpmd linter, its errors doesn't always mean that I should change my code but they are displayed with the same severity as a syntax errors generated by the php linter. It makes it hard to differentiate which should be immediately fixed and which are suggestions to be fixed.

**Comment by larseggert** [comment]
+1

**Comment by trobertsonsf** [comment]
+1 this would be SUPER helpful.

**Comment by AllSpeeds** [comment]
Heck yes.  +1

**Comment by bostrom** [comment]
Yes please!

**Comment by braver** [comment]
The SL4 beta provides this feature, check it out!
