### ISSUE TITLE
Sublime Linter CSSlint not working (no lint errors found)

### ISSUE THREAD

**Issue by quiquejbb** [SublimeLinter/SublimeLinter3#275]
Hello, I installed on a Win 8, Sublime 3 , via node.js...however when I run the css lint, it always says there are no lint errors, evethough there are. 

I have placed in the path the following C:/Users/AppData/Roaming/npm/csslint and tried many other paths, but nothing seems to work.

I tested CSS lint via commandline and it works properly...and on Sublime it is enabled...but it still does not find any error...any help much appreciated

**Comment by skj3gg** [comment]
Do you have a debug console output I can look at?

**Comment by quiquejbb** [comment]
I'm trying to see (sorry fairly new at sublime) but upon ctrl-` nothing new shows...

**Comment by braver** [comment]
We definitely need more info to work with. If this still is an issue and you find more debugging output, let me know and we'll look into it.
