### ISSUE TITLE
New Linter: SublimeLinter-contrib-check-source-formatting

### ISSUE THREAD

**Issue by drewbrokke** [SublimeLinter/SublimeLinter3#277]
https://github.com/drewbrokke/SublimeLinter-contrib-check-source-formatting

An interface for the Liferay [check-source-formatting](https://www.npmjs.com/package/check-source-formatting) linter.

**Comment by skj3gg** [comment]
Just fix the TravisCI badge and tag for release. Thanks!

**Comment by drewbrokke** [comment]
Done.  Thank you!

**Comment by drewbrokke** [comment]
Just a friendly reminder - the repo is tagged for release.  Thanks!

**Comment by skj3gg** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/8e36783eb2841ef69d1c916e156aeb03d6848082 Thanks for the reminder and your contribution!
