### ISSUE TITLE
HTML.tmLanguage file needs to be updated

### ISSUE THREAD

**Issue by akrabat** [SublimeLinter/SublimeLinter3#278]
See http://www.sublimetext.com/forum/viewtopic.php?f=2&t=18613&start=30#p68931

Also: http://www.sublimetext.com/forum/viewtopic.php?f=2&t=18634

**Comment by skj3gg** [comment]
Thanks for this! I will need to double check but it may be unnecessary to include both syntax files anymore. Which would help relieve this issue further. Added this to the June Sprint.

**Comment by iamntz** [comment]
Instead of forking and injecting a fixed syntax, you could also fork the official package and patch that.

https://github.com/sublimehq/Packages
