### ISSUE TITLE
Using color schemes in syntax-specific settings

### ISSUE THREAD

**Issue by LeonardoGentile** [SublimeLinter/SublimeLinter3#279]
Hello,
linters are working, meaning that I have a piece of code underlined and a mark on the gutter. The problem is that these have no colors.

The underline is white (I'm using a dark theme color for syntax highlight) and the gutter colors is sometimes white, sometimes blue.
I'm using customized syntax colors, they live in (for example) `/Packages/User/MyColors/Flatland/Flatland Dark.tmTheme` and I usually have different color schemes for different syntaxes (by modifying Preferences/Settings More/Syntax Specific -User`).

I tough that gutter might be conflicting with `modific`, a plugin that puts marks on the gutter when a tracked file is modified. I've disabled it and the the gutter marks turned white instead of blue..

**Comment by grotewold** [comment]
Sorry about the late response, the problem likely exists with the Syntax Specific settings. SL doesn't check those files for syntax color schemes so it doesn't get to do it's typical additions to the color schemes if they don't exist. Since it can't find the color, it comes out as white. Try a language that doesn't have its own color scheme and uses the one in your User Settings.

**Comment by LeonardoGentile** [comment]
Is it possible to require this as a new feature? I have defined custom colors for almost any language I use. Or at least could you point me where to start from for contributing?

**Comment by grotewold** [comment]
So the best place if you wanted to take a crack at it would be to hack at [lint/utils.py#L216](https://github.com/SublimeLinter/SublimeLinter3/blob/7d6450697cbe6847fcf7ee06e8b1666bb2cdf75a/lint/util.py#L216). You'd want to search for syntax specific preference files as well and if it has a color scheme property, take that over the base preference. Not sure this truly fits #104 but it's a step in the right direction, where a color schemes or users can dictate or change the color of SL markers.

**Comment by braver** [comment]
FYI, we're working on a new approach to the entire color scheme thing for Sublime Text > 3148 (i.e. current dev builds), which will fix this: #666

**Comment by braver** [comment]
SL4 no longer messes with your color schemes, check it out!  https://github.com/SublimeLinter/SublimeLinter3#sublimelinter-4-beta
