### ISSUE TITLE
Per-Project enable/disable of linters

### ISSUE THREAD

**Issue by thechriswalker** [SublimeLinter/SublimeLinter3#282]
My use case I have a personal project I want to use `eslint` as the javascript linter and another project that has `jshint` configuration and code-review steps that require that the `jshint` config produces no errors.

I have both linters installed, but I cannot find a way to use `eslint` by default and `jshint` for a single project. I think with the variety of linters/code style tools available for javascript and the need for a shared codebase to use a consistent linter across all contributors, this functionality would be very useful.

I tried to using `@disable: <bool>` in the main config to enable `eslint` and disable `jshint` which works, but the same syntax in the per-project settings is not allowed/honoured.

**edit**: I just found a related issue: #266 which shows a workaround to achieve my result, however, as mentioned in that issue, I would prefer to keep a `.sublimelinterrc` out of the shared projects. Using the project settings seems favourable.

**Comment by jawshooah** [comment]
Did you [read](http://www.sublimelinter.com/en/latest/settings.html#project-settings) the [documentation](http://www.sublimelinter.com/en/latest/settings.html#sublimelinterrc-settings)?

**Comment by thechriswalker** [comment]
@jawshooah Yes. 

The first link goes to the per-project configuration, exactly what I was looking for. Except that as I said in the issue, I could not get this to `@disable: false` one plugin and `@disable: true` another for the same language.

The second link goes to the documentation for the `.sublimelinterrc` also mentioned in initial (well, the initial edit of my) description and how, in a shared codebase I didn't want to add this file and remember not to `git add` it as I would not want to change the `.gitignore` file either.

I thank you for taking the time to post the exact links, they may be useful to others finding this at a later date and I should have included them initially.

My issue is: I do not want to add a file to the shared repository, but I want it to use a different linter than the normal configuration. e.g. disable `eslint`, enable `jshint`.

I tried using the project setting, which seemed like the logical place, and main config like so:

```json
// main sublimelinter settings
{
  ...
  "linters": {
    "jshint": {
      "@disable": true
     },
    "eslint": {
       "@disable": false
    }
  }
  ...
}
```

and 

```json
// sublime project settings
{
  ...
  "settings": {
    "SublimeLinter": {
      "linters": {
        "jshint": {
          "@disable": false
         },
        "eslint": {
           "@disable": true
        }
      }
    }
  }
  ...
}
```

but adding the info to the project file had no discernable effect.

**Comment by jawshooah** [comment]
Ah, you've made a mistake in your project configuration (one that I've made several times myself). The `SublimeLinter` object in the project settings exists at the top level as shown in the documentation, not inside the `settings` object. So your project settings should look like this:

```json
// sublime project settings
{
  ...
  "SublimeLinter": {
    "linters": {
      "jshint": {
        "@disable": false
      },
      "eslint": {
        "@disable": true
      }
    }
  },
  ...
}
```

**Comment by thechriswalker** [comment]
Awesome. I was hoping to be proven wrong. Let me test that out and I'll close this issue.

**Comment by skj3gg** [comment]
Is there something specific that the documentation could be better at describing for this? It's definitely a common problem.

**Comment by jawshooah** [comment]
@skj3gg It might be worth it to point out in the [Project settings](http://www.sublimelinter.com/en/latest/settings.html#project-settings) section that the `SublimeLinter` settings object should not be placed inside the `settings` object.

**Comment by Bnaya** [comment]
This is not working for me,
i've tried to set it on the project level and .sublimelinter rc.
my project file:
```
{
    "folders":
    [
        {
            "path": "."
        }
    ],
    "Sublimelinter":
    {
        "linters": {
            "jshint": {
                "@disable": true,
                "args": [],
                "excludes": []
            },
            "jscs": {
                "@disable": true,
                "args": [],
                "excludes": []
            }
        }
    }
}
```

.sublimelinterrc:
```
{
    "linters": {
        "jshint": {
            "@disable": true,
            "args": [],
            "excludes": []
        },
        "jscs": {
            "@disable": true,
            "args": [],
            "excludes": []
        }
    }
}
```

**Comment by benedfit** [comment]
I'm also having issues getting the above `.sublimelinterrc` to work

**Comment by jawshooah** [comment]
Well, for a start, both linters are disabled in the above `.sublimelinterrc`. Have you tried setting `@disable` to `false`?

**Comment by benedfit** [comment]
Based on what was said it would appear that OP has `jshint`, `jscs`and `eslint` enabled globally, and wants to, as do I, disable certain linters in certain projects

e.g. Legacy project, use `jshint` and `jscs`. New project, use `eslint`

Is this possible?

**Comment by benedfit** [comment]
@thechriswalker I managed to get this working by clearing the Sublime linter cache via Tools > SublimeLinter > Clear Caches

**Comment by aubreypwd** [comment]
I just wanted to note for anyone finding this that if you don't have your JSON formatted correctly (in my case trailing commas), your `.sublimelinterrc` won't apply.

**Comment by dgowrie-quovo** [comment]
In case anybody else ends up here due to top SERP result for "sublime text disable linter per project" and similar, noting that [project settings for SublimeLinter](http://www.sublimelinter.com/en/latest/settings.html#project-settings) have a new, flat format following [Sublime Text conventions](https://www.sublimetext.com/docs/3/projects.html).

The old format has been deprecated. Use the following format instead in your sublime project settings e.g `your-project.sublime-project`:

    
```
{
    "settings": {
        "SublimeLinter.linters.eslint.@disable": false, 
        "SublimeLinter.linters.jshint.@disable": true
    }
}
```

**Comment by dgowrie** [comment]
In case anybody else ends up here due to top SERP result for "sublime text disable linter per project" and similar, noting that [project settings for SublimeLinter](http://www.sublimelinter.com/en/latest/settings.html#project-settings) have a new, flat format following [Sublime Text conventions](https://www.sublimetext.com/docs/3/projects.html).

The old format has been deprecated. Use the following format instead in your sublime project settings e.g `your-project.sublime-project`:

    
```
{
    "settings": {
        "SublimeLinter.linters.eslint.@disable": false, 
        "SublimeLinter.linters.jshint.@disable": true
    }
}
```

**Comment by kaste** [comment]
Probably a typo, spell it 'disable' without the @. 🙌
