### ISSUE TITLE
Please get the themes out of this package; they interfere with other themes by the same name

### ISSUE THREAD

**Issue by ssteinerx** [SublimeLinter/SublimeLinter3#283]
Just tried to install Cobalt2 and, no matter what I do, I can't get his version -- SublimeLinter always overrides it.

Please make the themes into a separate package!

Thanks,

Steve

**Comment by skj3gg** [comment]
Hey Steve,

Sorry you're having issues. Are you talking about the color scheme? SublimeLinter simply appends its small additions to any color scheme you are using, but shouldn't affect the actual package. So when `"Packages/User/SublimeLinter/cobalt2.tmTheme"` becomes `"Packages/User/SublimeLinter/cobalt2 (SL).tmTheme"`, thats is still everything that's in `cobalt2.thTheme` plus the few additions that SL need to work. If you are having trouble seeing any changes made in the original `cobalt2.tmTheme`, you can use the `Tools/SublimeLinter/Clear Color Scheme Folder` menu option to clear out the SL version and then it will repull the orginal color scheme.

Hope this helps and sorry for any trouble!
Blake

**Comment by ssteinerx** [comment]
Blake,
  Not sure exactly what's going on but I'll bet a quick chat/email with @wesbos would clear things up.  His Cobalt2 repo is at: https://github.com/wesbos/cobalt2 and when I mentioned this difficulty he mentioned that he depends on SublimeLinter and hasn't quite figured out how to peacefully coexist.

Hit him up!  Nice guy and I'm sure we'd all love to get these playing nicely together.

Thanks, and thanks for a great package!

Steve
ssteinerX@gmail.com

**Comment by micck** [comment]
Ciao everybody,

as I guess, this issue could be related to my problem, I'm just adding my experience here :smiley: 

I'm the author of the Sublime Text [Color Scheme - Perv](https://github.com/FlavourSys/Perv-ColorScheme) and after being lazy for the last two years, I decided to give Sublime Text a go again...

Anyway, long story short: after updating Sublime Text and my usual packages, I started working on the color scheme again.  The first thing I wanted to change was that _SublimeLinter_ created the `../User/SublimeLinter/Your active color scheme (SL).tmTheme"` file(s), as it kind of interferes with hacking said scheme :smiling_imp: 

I read the [docs](http://www.sublimelinter.com/en/latest/); checked the `*(SL).tmTheme`; skimmed through the issues; and peaked (as I have no clue about Python) in the `../SublimeLinter/lint/util.py` files to figure out which additions _SublimeLinter_ is doing and if it really is checking for those in the `*.tmTheme` files.

So, I figured I should add the following section to my `Perv Orange Moonlight.tmTheme` (which already has some outdated(:question:) _SublimeLinter_ scopes :sunglasses: 

```xml
			<!-- Theme additions for SublimeLinter - Updated: 2015-06-22 == Start -->
<!-- ### SublimeLinter checks for the following three scopes -->
			<dict>
				<key>name</key><string>SublimeLinter Error</string>
				<key>scope</key><string>sublimelinter.mark.error</string>
				<key>settings</key>
				<dict>
					<key>foreground</key><string>#D02000</string>
				</dict>
			</dict>
			<dict>
				<key>name</key><string>SublimeLinter Warning</string>
				<key>scope</key><string>sublimelinter.mark.warning</string>
				<key>settings</key>
				<dict>
					<key>foreground</key><string>#DDB700</string>
				</dict>
			</dict>
			<dict>
				<key>name</key><string>SublimeLinter Gutter Mark</string>
				<key>scope</key><string>sublimelinter.gutter-mark</string>
				<key>settings</key>
				<dict>
					<key>foreground</key><string>#EEEEEE</string>
				</dict>
			</dict>
<!-- ### SublimeLinter checks for the above three scopes -->
```

In regards to the `../SublimeLinter/lint/util.py` python code, _SublimeLinter_ checks for the scopes `mark.warning`, `mark.error` and `gutter-mark`.  But apparently something is broken in the code (sorry, cannot help here, still no clue about Python :see_no_evil:) , as even with the above additions to my `.tmTheme` file, _SublimeLinter_ creates a `(SL).tmTheme` file with exactly the above seen code pasted at the end of my file.

Therefore I consider the redundant creation of `(SL).tmTheme` either a bug (which could be fixed), or a feature (which should be documented in the manual :grin:).

And if you consider it a bug and @wesbos would also add the above mentioned entries to his `.tmTheme` file (he uses the same outdated _SublimeLinter_ scopes/entries as I do), this issue would be fixed :wink: 

Thanks for reading, keep up the great work and have fun!
Mick

**Comment by grotewold** [comment]
https://github.com/wesbos/cobalt2/pull/64 Hope this resolves any issues you were having. Thanks!

**Comment by micck** [comment]
Hello Blake,

I hope you don't mind, if I re-use this issue (again).  For the sake of documentation and to help fellow *.tmTheme/Colour Scheme creators in supporting Sublime Linter.  I would like to share my conclusions:

The following 'XML/plist' snippet is working:

```xml
			<dict>
				<key>name</key><string>any text will do</string>
				<key>scope</key><string>sublimelinter.mark.error</string>
				<key>settings</key>
				<dict>
					<key>foreground</key>
					<string>#D02000</string>
				</dict>
			</dict>
```

As you may note, I prefer to have the `<key />` and `<string />` tag combinations in one line instead of spread over two.  But [SublimeLinter/SublimeLinter3](https://github.com/SublimeLinter/SublimeLinter3/) (for whatever reasons) expects a **newline** between the colour definition of (`<key>foreground</key>` and `<string>#D02000</string>`). 

I still would consider this a bug, as my theme works without those newlines...  but if not, now it is at least documented :page_facing_up: :relieved:

Thanks and take care,
Mick
