### ISSUE TITLE
Wrong highlighting position when using tab indentation

### ISSUE THREAD

**Issue by artisologic** [SublimeLinter/SublimeLinter3#284]
Hi there, I have searched all issues and could not find any reference to this.
I am unsure if it's a Sublime Linter bug or something underlying but here is a very simple test case:

![screen shot 2015-06-16 at 10 57 05](https://cloud.githubusercontent.com/assets/1539897/8180614/067928be-1417-11e5-8589-563803e94e12.png)

As you can see in this example, the linting error is that the `console` object is not present.

* The first 2 lines highlight the right word (no indentation or space indentation).
* All other lines use tab indentation and are not highlighting the correct position.

I actually can't really find the pattern it is using for tabs in the selection range...

**Comment by jawshooah** [comment]
Which linter are you using?

**Comment by artisologic** [comment]
My bad, this is using SublimeLinter-jshint.

**Comment by jawshooah** [comment]
Okay. I edited my previous comment, please follow the instructions there and post the debug log from startup through linting.

**Comment by artisologic** [comment]
Hi @jawshooah,

Here it is:

```
SublimeLinter: jshint version query: /usr/local/bin/jshint --version 
SublimeLinter: jshint version: 2.8.0 
SublimeLinter: jshint: (>= 2.5.0) satisfied by 2.8.0 
SublimeLinter: jshint activated: /usr/local/bin/jshint 
SublimeLinter: found existing HTML syntax, version 3 
SublimeLinter: found existing Rails syntax, version 1 
SublimeLinter: jshint: untitled.js ['/usr/local/bin/jshint', '--verbose', '--filename', '@', '--config', '/Users/benoit/Projects/cb-ebadm/.jshintrc', '-'] 
SublimeLinter: jshint output:
/Users/benoit/Projects/cb-ebadm/untitled.js: line 1, col 1, 'console' is not defined. (W117)
/Users/benoit/Projects/cb-ebadm/untitled.js: line 2, col 5, 'console' is not defined. (W117)
/Users/benoit/Projects/cb-ebadm/untitled.js: line 3, col 9, 'console' is not defined. (W117)

3 errors 
Package Control: Skipping automatic upgrade, last run at 2015-06-16 15:16:01, next run at 2015-06-16 16:16:01 or after
```

**Comment by artisologic** [comment]
Seems like an issue with the conversion between col and tabs.
For line 3, `col 9` seems correct to me but somehow it starts highlighting only from `col 15`.

**Comment by artisologic** [comment]
Found this on SublmeLinter-jshint: https://github.com/SublimeLinter/SublimeLinter-jshint/issues/54
Feels wrong to me to have to put `indent` to 1 if I'm using tabs... even though yes it does make the highlighting work.

**Comment by jawshooah** [comment]
Yeah, it's weird, but otherwise the linter plugin would need to rely on your ST3 `tab_width` setting and the `indent` in your `.jshintrc`  to correctly determine the column in the editor, which seems like a nasty bit of hackery to support a [deprecated feature](http://jshint.com/docs/options/#indent).

**Comment by artisologic** [comment]
Well I think it's 2 different things here really. The `indent` feature used to be here to actually enforce your indentation settings in your code. But not we're having to actually use that flag in a weird way to be able to have accurate highlighting.

To me it feels more like jshint should return 1 col if it's a tab.

For the previous example:

```
/Users/benoit/Projects/cb-ebadm/untitled.js: line 1, col 1, 'console' is not defined. (W117)
/Users/benoit/Projects/cb-ebadm/untitled.js: line 2, col 5, 'console' is not defined. (W117)
/Users/benoit/Projects/cb-ebadm/untitled.js: line 3, col 9, 'console' is not defined. (W117)
```

should be

```
/Users/benoit/Projects/cb-ebadm/untitled.js: line 1, col 1, 'console' is not defined. (W117)
/Users/benoit/Projects/cb-ebadm/untitled.js: line 2, col 5, 'console' is not defined. (W117)
/Users/benoit/Projects/cb-ebadm/untitled.js: line 3, col 2, 'console' is not defined. (W117)
```

Note the `col 2`, as a tab is only one character, therefore we shouldn't have to tweak that deprecated settings anyway (`indent`).

**Comment by jawshooah** [comment]
Agreed, but that's an issue on JSHint's side. We can't do anything about it, unfortunately.

**Comment by artisologic** [comment]
Agreed :)
That was informative anyway. I'm surprised there's not more people annoyed with this, unless I'm the only dev using tabs... haha

**Comment by jawshooah** [comment]
I'm partial to spaces myself, but whatever tickles your pickle :wink: 

Closing this, since there's not really anything we can do about it on our side.

**Comment by artisologic** [comment]
hehe, cheers for looking at this with me.
