### ISSUE TITLE
SublimeLinter-html-tidy make the paths configuration not work

### ISSUE THREAD

**Issue by hu2008yinxiang** [SublimeLinter/SublimeLinter3#286]
AS I assigned here https://github.com/SublimeLinter/SublimeLinter-html-tidy/issues/33

**Comment by jawshooah** [comment]
Please do not create duplicate issues. If, through discussion on the linked issue, it is discovered that a problem exists in SL3 core, we can revisit this.

**Comment by hu2008yinxiang** [comment]
I submit a pull request and it is still no response, why ?
https://github.com/SublimeLinter/SublimeLinter-html-tidy/pull/35

**Comment by grotewold** [comment]
Sorry it's taking some time. Please be patient as we get to your issue.
