### ISSUE TITLE
SublimeLinter: ERROR: ruby cannot locate 'ruby'

### ISSUE THREAD

**Issue by sachinmour** [SublimeLinter/SublimeLinter3#289]
Hello to all,
I installed sublime text 3 on ubuntu 15.04 and also installed sublimelintor ruby-wc for it.
Everything goes all right as given in documentation, but there is error regarding version of ruby in lintor, i think... help please

**Comment by grotewold** [comment]
Do you have too low of version of ruby? What is your ruby version?

**Comment by braver** [comment]
It's been a while so I'm going to assume this was resolved or @sachinmour moved on. If help is needed for setting up your linter let me know.
