### ISSUE TITLE
JSLint conflicts

### ISSUE THREAD

**Issue by Amparose** [SublimeLinter/SublimeLinter3#290]
The reporting in the editor does not match what I get running JSLint directly (ctrl + L) and seems mostly wrong. I have SublimeLinter v3.5 installed.

Example 1: http://pasteboard.co/1x6OEg2Z.png

I have all default settings, which means `"--indent", "2"`. So not sure why JSLint through SumblineLinter is asking for 4 spaces.

Example 2: http://pasteboard.co/1x748lvh.png

Once again running JSLint directly reports no errors. Through SublimeLinter I get an `use strict` error and a request to move the closing curly bracket to col 5, which makes no sense!

**Comment by jawshooah** [comment]
From CONTRIBUTING.md:
> If your issue is specific to a particular linter, report the issue on that linter's repository instead.

[Here](https://github.com/devdoc/SublimeLinter-jslint/issues) is the issue tracker for SublimeLinter-jslint.

**Comment by Amparose** [comment]
Apologies. Thank you for the link.
