### ISSUE TITLE
path in option is not picked up

### ISSUE THREAD

**Issue by leesei** [SublimeLinter/SublimeLinter3#295]
I've added my `jshint`'s path to `SublimeLinter.sublime-settings`, yet SublimeLinter still shows
`SublimeLinter: WARNING: jshint deactivated, cannot locate 'jshint' `

I'm on Arch Linux, using the AUR [Sublime Text 3 build 3038](https://aur.archlinux.org/packages/sublime-text-dev/).

```bash
$ uname -a                                                                                                                                                                                               
Linux artergos 4.0.7-2-ARCH #1 SMP PREEMPT Tue Jun 30 07:50:21 UTC 2015 x86_64 GNU/Linux
```

I posted the relevant files in this gist.
https://gist.github.com/leesei/f7582bbd1b77d52f02ca

**Comment by grotewold** [comment]
This seemed to work fine in your `sublime-console.log`, I'm not seeing it deactivate it the output.

**Comment by leesei** [comment]
Alas, I haven't opened an `.js` file.
I've updated the log.

**Comment by leesei** [comment]
I browsed the issues and found that `html-tidy` is the [culprit](https://github.com/SublimeLinter/SublimeLinter-html-tidy/issues/33).

I removed it and my path works again.
Closing this issue.
