### ISSUE TITLE
New plugin submission: sqlint (SQL Linter)

### ISSUE THREAD

**Issue by trezona-lecomte** [SublimeLinter/SublimeLinter3#297]
Hi there, I would like to submit the [SublimeLinter-contrib-sqlint](https://github.com/trezona-lecomte/SublimeLinter-contrib-sqlint) plugin for review.

This plugin provides an interface to [sqlint](https://github.com/purcell/sqlint) within Sublime Text 3. Please refer to the `sqlint` repo for more information on this linter. 

Let me know what you think, thanks!

**Comment by grotewold** [comment]
++

Please make your first release and I'll add to Package Control

**Comment by trezona-lecomte** [comment]
Hi @grotewold, thanks for the quick response. 

I've tagged the current version as [1.0.0](https://github.com/trezona-lecomte/SublimeLinter-contrib-sqlint/tree/1.0.0), is that all you need from my end?

**Comment by grotewold** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/d8efcb837cb3e1da482218be39a65bbbefa610f2  THANKS!
