### ISSUE TITLE
Linter error priority

### ISSUE THREAD

**Issue by ezk84** [SublimeLinter/SublimeLinter3#299]
It would be useful if there was a way to assign a priority to linters. 

For example I am running both the `php` and `phpcs` linters. The first one checks syntax errors, the second one checks code style. 

Syntax errors should always 'override' code style violations: I want to see the syntax error rather than try to work out why the coding standard is being violated (because a missing parenthesis throws the whole coding style checker out of whack). Currently the `phpcs` errors shadow the `php -l` errors.

I see this working in two ways:
- for a given line a higher priority linter will display its errors before lower-priority linters.
- a higher priority linter will disable lower priority linters if it detects errors.

I prefer the first one myself.

**Comment by braver** [comment]
The SL4 beta provides this feature for icons in the gutter, check it out!  https://github.com/SublimeLinter/SublimeLinter3#sublimelinter-4-beta

Priority for inline highlights would be super complicated, it doesn’t weigh up to the value it would provide.
