### ISSUE TITLE
Add Linter Plugin for Hacking Linter

### ISSUE THREAD

**Issue by utkonos** [SublimeLinter/SublimeLinter3#300]
I'd like to see a plugin for OpenStack's Hacking linter:
https://github.com/openstack-dev/hacking
https://pypi.python.org/pypi/hacking/0.9.6

**Comment by braver** [comment]
@utkonos This repo manages the shared linter, and if you have created a new linter let us know and we'll list it. 

To request new linters to be created, the [Sublime Text forum](https://forum.sublimetext.com) might be a better place: more people will see it and there is a better chance someone will come and create something for you.
