### ISSUE TITLE
Dump debug log to file – Sublime Text crashes on lint

### ISSUE THREAD

**Issue by louwers** [SublimeLinter/SublimeLinter3#302]
Hi there!

I would be very grateful if someone could help me dump the [debug messages](http://sublimelinter.readthedocs.org/en/latest/troubleshooting.html?highlight=debug#debug-mode) to a file instead of the console. 

So far, I tried `SublimeLinter-eslint` and `SublimeLinter-jshint`, but with both I have the same problem: as soon as I try to lint a file, Sublime Text crashes (so I can't read the console anymore).
I get a very promising `SublimeLinter: jshint activated: /usr/local/bin/jshint`message in the console when I launch Sublime Text. Also, `jslint` works fine from the Terminal, and so did `eslint`.

Thanks!

**Comment by jawshooah** [comment]
I suggest using a plugin like [SublimeLog](https://github.com/yrammos/SublimeLog), which is intended specifically for this use case.

**Comment by louwers** [comment]
Thanks a bunch!

`Console logging activated (/Users/Bart/.subl.log). Timestamp: 27 Jul 2015, 17:26:51.
SublimeLinter: jshint: setup.js ['/usr/local/bin/jshint', '--verbose', '--filename', '@', '--config', '/Users/Bart/waldfiles-dev/.jshintrc', '-']`
Very unhelpful result though. Guess I am stuck with command line linting for now.
