### ISSUE TITLE
key binding collision

### ISSUE THREAD

**Issue by Chrisriis** [SublimeLinter/SublimeLinter3#304]
The default Mac key-binding for "Alignment" is _ctrl+cmd+a_. 
Therefore it collides with Sublime Linter's "Show All Errors".
You can naturally work around this by setting your own key binding, but two top 25 packages shouldn't have a conflict like this.

I also posted this issue to the Alignment package: https://github.com/wbond/sublime_alignment/issues/80#issuecomment-126366599

**Comment by christianesperar** [comment]
+1

**Comment by braver** [comment]
It's a bit late in the game to change shipped key bindings. Perhaps they shouldn't have collided with a top25 package, but basing what keybindings to ship on what other packages are doing it tricky anyway. There are existing solutions and documentation for this, so yeah.. SublimeLinter4 might be a good opportunity to revisit this, but it's not on the horizon as far as I know.

**Comment by groteworld** [comment]
I did actually promise a solution in https://github.com/wbond/sublime_alignment/issues/80#issuecomment-126689551. Though I think the best option is to write documentation around how to overwrite the keymap. Maybe even write a small command that does it for them?

**Comment by braver** [comment]
@groteworld How about I just add something to the README about the available key bindings and a reference to the ST docs on how to customise them?

**Comment by pinheadmz** [comment]
Is there anyway to REMOVE a default key binding? I already use this key combo for something else:
```
    { "keys": ["ctrl+super+a"], "command": "sublime_linter_panel_toggle" },
```
And I can't figure out any way to add anything to `Default (OSX).sublime-keymap` that will remove that key binding from SublimeLinter, and allow the other plugin to catch it.

**Comment by kaste** [comment]
You don't remove a key binding, but you overwrite to do the command you like.

**Comment by pinheadmz** [comment]
@kaste can I overwrite with a command for a completely different package or menu item? I'm using the OSX system preferences keyboard shortcuts/app shortcuts to specify a custom key combo.

**Comment by kaste** [comment]
Using `Preferences > Key Bindings` you can bind a custom/Sublime command to `ctrl+super+a` which then takes precedence. OS wide shortcuts cannot be reassigned. You can try to set the command to the empty string or 'foo'. 🤞

**Comment by pinheadmz** [comment]
Awesome thank you I got this to work :-)
