### ISSUE TITLE
New linter plugin for review - stylelint

### ISSUE THREAD

**Issue by kungfusheep** [SublimeLinter/SublimeLinter3#305]
https://github.com/kungfusheep/SublimeLinter-contrib-stylelint

Cheers

**Comment by grotewold** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/fa9bce63339332840c1d0f13ad1f71467f8d8cad

Please make a first release, and it will be visible in Package Control.

Thanks for your patience and contribution!
