### ISSUE TITLE
New linter: XO

### ISSUE THREAD

**Issue by sindresorhus** [SublimeLinter/SublimeLinter3#306]
https://github.com/sindresorhus/SublimeLinter-contrib-xo

**Comment by kevva** [comment]
:+1:

**Comment by gillstrom** [comment]
:+1:

**Comment by grotewold** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/196d0331a6e8e434b77a091a4d9b1a9b76505830

Thanks for your patiences and contribution!
