### ISSUE TITLE
New linter: SublimeLinter-contrib-jade-lint

### ISSUE THREAD

**Issue by benedfit** [SublimeLinter/SublimeLinter3#309]
https://github.com/benedfit/SublimeLinter-contrib-jade-lint

This linter provides an interface to the [jade-lint](https://github.com/benedfit/jade-lint) linter and style checker for Jade.

N.B. jade-lint doesn't currently report columns for errors, but as the main contributor it is something I am working on, but SublimeLinter-contrib-jade-lint has been future-proofed to pick up columns as soon as they are available

Cheers

**Comment by balaclark** [comment]
:+1:

**Comment by benjaminparnell** [comment]
:+1:

**Comment by grotewold** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/fe48420953d54b206893f4c3ffcd8bf94e856ee7

Thanks for your patience and contribution!
