### ISSUE TITLE
Different setting per folder

### ISSUE THREAD

**Issue by Reinmar** [SublimeLinter/SublimeLinter3#310]
I have a project which consists of many submodules and each of them has its own JSHint and JSCS config files. In Sublime I want to have all these submodules as one projects (because they are rather small).

Is it possible to configure SublimeLinter3 so it uses different linter settings per folder? Or is it more a question about Sublime's than SublimeLinter's capabilities?

If I didn't miss anything and this is indeed impossible to achieve now, then could such feature be added to SublimeLinter or it doesn't seem to be feasible?

**Comment by braver** [comment]
A linter executable will look for it's configuration starting from the file it is linting. So, this should "just work". If not, that's up to the linter, not SL.
