### ISSUE TITLE
New linter SublimeLinter-contrib-protoc-gen-lint 

### ISSUE THREAD

**Issue by ckaznocha** [SublimeLinter/SublimeLinter3#312]
Hello,
I've created a plug interface to lint protocol buffers using protoc-gen-lint

https://github.com/ckaznocha/SublimeLinter-contrib-protoc-gen-lint

**Comment by grotewold** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/d6ffa04a0c2170322e871806460d279d5937b5fb

Please make a release and we'll be good to go! Thanks!

**Comment by ckaznocha** [comment]
Thanks @grotewold! I've created a release.
