### ISSUE TITLE
New linter: SublimeLinter-contrib-elm-make (and cake)

### ISSUE THREAD

**Issue by bbugh** [SublimeLinter/SublimeLinter3#313]
Hey there SublimeLinter3 legends, I made a package for Elm linting.

It's available here:
https://github.com/bbugh/SublimeLinter-contrib-elm-make

I'm pretty sure it's awesome, and so are you! :cake:  :cake:

**Comment by grotewold** [comment]
No! You, sir, are awesome!!

Please make a release and It will be added to package control.

Thanks for contributing to the project.

**Comment by bbugh** [comment]
We can both be awesome. "Yes, and"!

Here it is, my crowning achievement, my masterpiece: https://github.com/bbugh/SublimeLinter-contrib-elm-make/releases/tag/v1.0.0

**Comment by bbugh** [comment]
@grotewold it's not showing up in Package Control. Is there something else I need to do?

**Comment by grotewold** [comment]
https://packagecontrol.io/packages/SublimeLinter-contrib-elm-make




Looks like it's there, do you have the code already in the packages folder. If it recognizes it in there it won't find it in the command pallet.

**Comment by bbugh** [comment]
That was it, thanks.
