### ISSUE TITLE
Too Many errors when adding ignore pattern

### ISSUE THREAD

**Issue by Aminadav** [SublimeLinter/SublimeLinter3#315]
See the errors:
I want to ignore missing semicolon, I success to ignore it but it is still counted as error.

![image](https://cloud.githubusercontent.com/assets/3584317/9392944/ef65e6ae-4787-11e5-80bc-e500989410a8.png)
![image](https://cloud.githubusercontent.com/assets/3584317/9392981/210c022e-4788-11e5-8aec-2a6453dc543d.png)

Sublime linter settings:
"ignore_match": [
                    "Missing semicolon",
                    "._debugger._",
                    "._functions within._",
                    "._is better._in dot.*"
                ]

**Comment by lucasmenezesds** [comment]
+1

**Comment by braver** [comment]
This is an error message from the linter. You're suppressing the errors in SL, but you should change the configuration for the linter itself instead so it ignores these cases.
