### ISSUE TITLE
New Linter: SublimeLinter-contrib-glualint

### ISSUE THREAD

**Issue by FPtje** [SublimeLinter/SublimeLinter3#317]
I've made a linter that lints Garry's Mod's variant of Lua. 

Here's the repository:
https://github.com/FPtje/SublimeLinter-contrib-glualint

It has a release (1.0.0)

Here's the latest release of glualint:
https://github.com/FPtje/GLuaFixer/releases

**Comment by grotewold** [comment]
Fix the TravisCI badge and we're good. Thanks!

**Comment by FPtje** [comment]
Done! Thanks for the quick reply!

**Comment by grotewold** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/2ddc953ddcb8c616cc33b4e683686e362d5aa271

Thank you again for your contribution!
