### ISSUE TITLE
New linter gometalinter

### ISSUE THREAD

**Issue by alecthomas** [SublimeLinter/SublimeLinter3#319]
Hello,

I am the author of [gometalinter](https://github.com/alecthomas/gometalinter) which aggregates and normalises many linters for the Go programming language. 

I've written a SublimeLinter3 plugin for this tool which you can find [here](https://github.com/alecthomas/SublimeLinter-contrib-gometalinter). Please review and I'll clean up any issues.

Thanks,
Alec

**Comment by grotewold** [comment]
https://packagecontrol.io/packages/SublimeLinter-contrib-gometalinter woot!

**Comment by alecthomas** [comment]
Brilliant, thanks!
