### ISSUE TITLE
Stale errors displayed on save

### ISSUE THREAD

**Issue by CrabDude** [SublimeLinter/SublimeLinter3#320]
As of the v3.5.2 release and it's associated fixes (https://github.com/SublimeLinter/SublimeLinter3/pull/271, https://github.com/SublimeLinter/SublimeLinter3/issues/267), stale errors are now displayed on save.

Path to reproduce:

1. `npm install -g babel babel-eslint eslint` (Can't remember if these are necessary for Sublime)
1. Package Control: Install `SublimeLinter`, `Sublime-contrib-eslint` and `Babel`
1. Ensure `show_errors_on_save` is `true`
1. Create a lint error, save => No error is displayed
1. Continue typing => Error pop-up is never displayed
1. Fix lint error, save => Previous lint error is displayed/reported even though it's unquestionably been fixed

While this may even seem intended (e.g., Don't block the UI thread), the end result is:

1. Fixed errors are still reported as errors on save.
1. Real errors never get displayed because often you begin typing again after saving.

In the past, I'm not sure I ever noticed the UI lag, but I definitely noticed that the error reports were inconsistent with the current state of things. I think this was exacerbated by the fact that `eslint` seems to be running much slower recently, and taking >1s for even simple files, significantly adding to the lag.

I'm not sure what the solution is.

**Comment by grotewold** [comment]
Thanks for your contribution!

**Comment by CrabDude** [comment]
@grotewold Wow. That was so fast, I thought you just ignored and closed the issue. Impressed. Thanks.
