### ISSUE TITLE
New Linter: SublimeLinter-contrib-rstylelint

### ISSUE THREAD

**Issue by mom1** [SublimeLinter/SublimeLinter3#322]
I've made a linter that lints RSL language (.mac) https://github.com/mom1/SublimeRStyle

Here's the repository:
https://github.com/mom1/SublimeLinter-contrib-rstylelint

**Comment by grotewold** [comment]
Please make a release and it will be available in SublimeText.

Thanks!

**Comment by mom1** [comment]
I did

**Comment by grotewold** [comment]
https://packagecontrol.io/packages/SublimeLinter-contrib-rstylelint
