### ISSUE TITLE
New linter: Alex

### ISSUE THREAD

**Issue by sindresorhus** [SublimeLinter/SublimeLinter3#323]
https://github.com/sindresorhus/SublimeLinter-contrib-alex

**Comment by sindresorhus** [comment]
@grotewold friendly ping :)

**Comment by grotewold** [comment]
Thanks for the reminder. Please make a release and we're good to go!

Thanks again for your contributions to SL and Alex!

**Comment by sindresorhus** [comment]
Thanks. Done :)
