### ISSUE TITLE
Display linting results, also when zero

### ISSUE THREAD

**Issue by bobrocke** [SublimeLinter/SublimeLinter3#324]
Would it be possible to show linting results in the bottom status bar when there are no errors? Maybe something as simple as changing the `7 errors` displayed now to `0 errors`? Or even a green check mark? It would be nice to have visual confirmation that a linter did run and found no problems.

**Comment by mjs7231** [comment]
I would also love this.  Another linter I was using a while back also added a green checkmark on every line for a half second to visually show the linter ran and everything was good. Any feedback would be great as right now I'm always questioning if the linter actually ran or is broken.
