### ISSUE TITLE
New linter: SublimeLinter-contrib-sass-lint

### ISSUE THREAD

**Issue by skovhus** [SublimeLinter/SublimeLinter3#326]
Provides an interface to [sass-lint](https://github.com/sasstools/sass-lint) (the new Node.js linter for Sass/SCSS files).

Is it pending the release of `sass-lint` 1.2.0 which is expected to be out in the [coming week](https://github.com/sasstools/sass-lint/pull/115).

https://github.com/skovhus/SublimeLinter-contrib-sass-lint

**Comment by jawshooah** [comment]
Looks like you're using `.scss-lint.yml` instead of `.sass-lint.yml` as your config file.

**Comment by skovhus** [comment]
@jawshooah good catch. Should be fixed now.

**Comment by skovhus** [comment]
@jawshooah one thought: I don't like the global dependency that most SublimeLinter plugins have. I would like the linter to be more in control of its own dependencies (using virtual env for Python and node_modules for Node). In this case, I would imagine the version of `sass-lint` to be installed and managed by the linter, i.e. having a node_modules with it that this linter is using. Would that make sense to you? Any other linter that have this behavior? Thanks.

**Comment by jawshooah** [comment]
I'd need @grotewold to confirm here, but I don't believe that's within the scope of the project. SublimeLinter plugins are meant to be very thin layers on top of the framework that use whatever you have already installed. We don't want to get into package and dependency management.

**Comment by jawshooah** [comment]
However, because your plugin extends `NodeLinter`, it should look inside your projects `node_modules/.bin` directory for the `sass-lint` binary before checking globally. So you can still manage your dependencies per-project and have the linter plugin pick up on that.

**Comment by skovhus** [comment]
Ok. It was also just a thought for future improvement. : )

**Comment by jawshooah** [comment]
Think of it as adhering to the [Principle of Least Astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). When someone installs a SublimeLinter plugin, there's no reason they should expect us to install the linter binary as well.

**Comment by grotewold** [comment]
@jawshooah is right, We would rather make the fewest amount of assumptions about what others' development environments look like. 

Everything else looks in order, please make a release and I'll push it to the package channel. Thanks!

**Comment by grotewold** [comment]
After rereading your first post, I have added it to the package channel, it will not appear in package control until a release is made. That way, once 1.2.0 is released, you don't have to wait for us to push it out, you can do the contrib-sass-lint release by yourself. 

Feel free to close this issue now or when you've done your release.

**Comment by skovhus** [comment]
@grotewold thanks. I've tagged and pushed a version. I guess it should show up here: https://packagecontrol.io/packages/SublimeLinter-contrib-sass-lint

**Comment by grotewold** [comment]
I'm seeing it in package control so all looks good. Thanks again!

**Comment by skovhus** [comment]
@grotewold thanks. :) And when releasing new version I should just tag again right? It will automatically show up in the package control? I've tried tagging a version `1.0.1` with better error parsing.

**Comment by grotewold** [comment]
Exactly! It'll so up in an hour or less.

**Comment by skovhus** [comment]
Super! :+1:
