### ISSUE TITLE
New linter: SublimeLinter-contrib-cmakelint

### ISSUE THREAD

**Issue by jasjuang** [SublimeLinter/SublimeLinter3#328]
This is a linter for cmake files. It passes flake8 and pep257. Please review.

https://github.com/jasjuang/SublimeLinter-contrib-cmakelint

**Comment by grotewold** [comment]
Make a release and it should be visible in Package Control.

Thanks!

**Comment by jasjuang** [comment]
I can see it in Package Control now. 

One more small question: It is showing "No description provided" at the second line. How can I add in a description? I am not having any luck from googling.

**Comment by grotewold** [comment]
It's pulling from your Github repo description. Hope that helps!

**Comment by jasjuang** [comment]
got it, thanks!
