### ISSUE TITLE
Support more error levels than warning and error (like pylint)

### ISSUE THREAD

**Issue by emichael** [SublimeLinter/SublimeLinter3#329]
Having warning and error is nice, but many linters (e.g. pylint) have even more error levels. It would be nice if sublime linter had more options and gave each plugin a way to map its error hierarchy onto the sublimelinter error levels.

**Comment by braver** [comment]
We don't want to support anything else than errors and warnings because it just complicates everything without adding value. 

- Error - you need to do something about it now
- Warning - you should do something about it soon
