### ISSUE TITLE
Error - Unexpected token ,,  || Error Unexpected Identifier

### ISSUE THREAD

**Issue by fergusmeiklejohn** [SublimeLinter/SublimeLinter3#330]
Finds an error after a comma, but there is nothing there.  Deleting the comma leads to an error on all but the first character of the next word.

Same with Unexpected Identifier, it's like the Linter is seeing a character which isn't actually there then throwing an error
<img width="473" alt="screen shot 2015-09-07 at 09 28 44" src="https://cloud.githubusercontent.com/assets/11864025/9926748/ba4cd1c0-5d4a-11e5-8cf3-c536f6414b7b.png">
![screen shot 2015-09-17 at 14 43 34](https://cloud.githubusercontent.com/assets/11864025/9926749/ba8b8af0-5d4a-11e5-9232-d79790ecfaad.png)
![screen shot 2015-09-17 at 14 43 51](https://cloud.githubusercontent.com/assets/11864025/9926750/ba8bda32-5d4a-11e5-9610-9535c1f0ca3a.png)

**Comment by braver** [comment]
@fergusmeiklejohn what linter are you using here?

**Comment by braver** [comment]
🤷‍♂️ We'll re-open if there's news.
