### ISSUE TITLE
Linting <script> blocks in HTML documents does not consider non JavaScript content

### ISSUE THREAD

**Issue by durz** [SublimeLinter/SublimeLinter3#331]
Currently it seems that all `<script>` blocks in a HTML document are treated as though they are JavaScript. There are, however, very valid use cases for `<script>` blocks to *not* contain JavaScript. This is very common in libraries that support templating.

For example, when using Kendo UI, HTML templates are inserted inside of script blocks with a specific value for the `type` attribute (`text/x-kendo-tmpl`). 

````
<script type="text/x-kendo-tmpl">
    <tr data-uid="#= uid #">
        <td>...</td>
    </tr>
</script>
````

When using a linter like JSHint, there isn't an issue because JSHint itself knows how to take a HTML document and extract JS from it (using the `--extract` option) by looking for script blocks which have either a `type` attribute with a value of `"text/javascript"`, or no `type` attribute at all. This is consistent with a modern browser's handling of script tags where unknown script types get ignored: https://developer.mozilla.org/en/docs/Web/HTML/Element/script#attr-type.

However, with another type of linter like eslint that takes pure JS as its input, the whole contents get treated as JS so, naturally, the linter reports errors like:

> Unexpected token <

The HTML5 spec for the script element does not actually impose limits on the value of the `type` attribute, aside from requiring it to be a valid MIME type: http://www.w3.org/TR/html5/scripting-1.html#scriptingLanguages. So, it is perfectly valid that library authors define their own "language" using the `type` attribute.

I suggest an improvement: that SublimeLinter should check the script's `type` and then only pass the contents to a JS linter if the script block can be treated as JS.

Originally from:
roadhump/SublimeLinter-eslint#83
https://github.com/SublimeLinter/SublimeLinter3/issues/254

**Comment by campoy** [comment]
I'm having similar issues using webGL:

```html
<head>
    <title>Textures example</title>
    <script src="../libs/webgl-utils.js"></script>
    <script src="script.js"></script>
    <link rel="stylesheet" href="../libs/style.css">

	<script id="2d-vertex-shader" type="x-shader/x-vertex">
		attribute vec2 a_position;
		attribute vec2 a_texCoord;
		varying vec2 v_textCoord;
		 
		void main() {
		  gl_Position = vec4(a_position, 0, 1);
		  v_textCoord = a_texCoord;
		}
	</script>
```

For now I'm fixing it adding `/* jshint ignore:start */` at the beginning of each block, but I'd love to have this fixed.

**Comment by grotewold** [comment]
Consolidating this with https://github.com/SublimeLinter/SublimeLinter3/issues/356
