### ISSUE TITLE
New linter: SublimeLinter-contrib-eslint_d

### ISSUE THREAD

**Issue by roadhump** [SublimeLinter/SublimeLinter3#333]
https://github.com/roadhump/SublimeLinter-contrib-eslint_d

Plugin for `eslint_d`, a tool to reduce `eslint` startup time by running a server in the background.

**Comment by grotewold** [comment]
Fix your travis ci badge and make a release.

Thanks!

**Comment by roadhump** [comment]
Done https://github.com/roadhump/SublimeLinter-contrib-eslint_d/releases/tag/1.0.0

**Comment by grotewold** [comment]
It's been added, should be visible soon.

Thanks for your continued contributions!
