### ISSUE TITLE
linter marking gutter but not highlighting code

### ISSUE THREAD

**Issue by spengilley** [SublimeLinter/SublimeLinter3#334]
Hi there,

I have installed the latest sublimelinter and the sublime-phplint. The linter is detecting syntax errors and putting a little dot in the gutter. I would also like the linter to highlight the text that is erroring. I have accessed the command pallet and typed Mark. Then choose mark style. I have selected Fill, which has added an entry to my sublime linter user settings.

"mark_style": "fill"

However, no code is being highlighted in any way. Only the gutter mark is there.

Any ideas?

**Comment by grotewold** [comment]
What's the error you are getting linted back to you. Some linters that require compiling the code, like `phplint`, don't give a column or anything to highlight so SL only does a gutter mark. Could I see the console output as well?

**Comment by rokhit** [comment]
Hi @grotewold,
i've the same issue. The gutter icon is shown but the actual code line is not outlined. I copied the default gutter theme and called it "Test" (see attached screenshot).

My setup: ST3, SublimeLinter and SublimeLinter-php installed through Package Control.

How can I provide you with more information? What is the "console output" you asked for?

![bildschirmfoto 2015-12-02 um 13 14 25](https://cloud.githubusercontent.com/assets/2992880/11530684/021dbd6a-98f7-11e5-82df-727ff3a9d267.png)

**Comment by braver** [comment]
You can open Sublime Text’s console from the button in the status bar. Seems like linter specific behavior here otherwise, nothing wrong. If there is something wrong, we’ll reopen.
