### ISSUE TITLE
New Linter jsdebugmarkers

### ISSUE THREAD

**Issue by LeoLeal** [SublimeLinter/SublimeLinter3#337]
https://github.com/LeoLeal/SublimeLinter-jsdebugmarkers

**Comment by grotewold** [comment]
Please make a release and it should be visible in Package Control less then an hour later.


Thanks!

**Comment by LeoLeal** [comment]
The linter plugin is available on github... Is there any aditional step i
should follow?

Thanks
Em 25/09/2015 12:31 PM, "Blake Grotewold" <notifications@github.com>
escreveu:

**Comment by grotewold** [comment]
it needs a tag to for Package Control to detect changes.

Just create a 1.0.0 release here https://github.com/LeoLeal/SublimeLinter-jsdebugmarkers/releases

**Comment by LeoLeal** [comment]
Oh! You mean that... :)

Done!
Em 25/09/2015 3:22 PM, "Blake Grotewold" <notifications@github.com>
escreveu:

**Comment by grotewold** [comment]
https://packagecontrol.io/packages/SublimeLinter-jsdebugmarkers

Thanks again!
