### ISSUE TITLE
Use specific version of linter

### ISSUE THREAD

**Issue by OliverJAsh** [SublimeLinter/SublimeLinter3#340]
I have different versions of each plugin I have installed on my projects, but this plugin will only run against the global version of the plugin. Would it be possible to target a local version of a plugin, e.g. `./node_modules/.bin/eslint`, relative to the project directory?

**Comment by OliverJAsh** [comment]
It appears this can already be done with some plugins https://github.com/roadhump/SublimeLinter-eslint#linter-installation

**Comment by grotewold** [comment]
Yes, Node-based linters should be doing this for you. If not, please check their source and if they aren't inheriting from the NodeLinter class, encourage them to do so.
