### ISSUE TITLE
Checking my Linter Plugin for foodcritic

### ISSUE THREAD

**Issue by badmadrad** [SublimeLinter/SublimeLinter3#341]
Just following the plugin creation guidelines by posting here.

I would like my plugin to checked for completeness and correctness so that it may be published.

repo: https://github.com/badmadrad/SublimeLinter-foodcritic
linter: http://acrmp.github.io/foodcritic/

Please let me know if you need more information.

Thanks!

**Comment by grotewold** [comment]
While your `linter.py` file is carrying more variables then you'd need, everything seems to be in order,

Your TravisCI link is broken though. After fixing, please create a release and i'll get it into Package Control.

**Comment by badmadrad** [comment]
Fix made and Release created:
https://github.com/badmadrad/SublimeLinter-foodcritic/releases/tag/1.0.0

Do you need me to do a pull request to package control repository?

**Comment by glenjamin** [comment]
This looks quite similar to the other foodcritic plugin - it would appear that you also suffer from this same problem:

https://github.com/pelletiermaxime/SublimeLinter-contrib-foodcritic/issues/1#issuecomment-88628941

**Comment by glenjamin** [comment]
I stumbled across this discussion while about to make a PR to fix the "ruby vs chef" thing - not sure which one to PR to now!

**Comment by badmadrad** [comment]
I would PR to mine since its in the pipeline. That being said, I don't think this is a requirement for this package to at least be integrated into package control. The main reason is that once its in package control, its easy to disable a package with package manager. In the event, you find foodcritic throwing errors in your ruby files you could always disable and re-enable when you are working on a cookbook. By having it in package control this would be easy to do. Right, now the average use doesn't even have the option to use foodcritic in any capacity.

Sidenote, I work on ruby scripts and rails stuff all the time and don't run into issue where foodcritic is being noisy. Foodcritic is mostly looking for chef dsl conventions. The only foodcritic rule that gets tripped unnecessarily is when a ruby script shells out. If you have a regular ruby script that uses backticks or system to shell out it will throw a warning for rule FC002 which is not applicable. This could probably be ignored. If you are having a different experience, I would love to know.

I am open to pull request implementing a way to fix this how we figure out its a cookbook file or not. I have some ideas of my own I want to implement at some point.

**Comment by pelletiermaxime** [comment]
I disagree. Running foodcritic takes ressources and throws out several warning that confused me before when working on ruby stuff.
In any case, It would really be great to get this implementation or mine in Package Control to make it easier to install for everyone.

**Comment by badmadrad** [comment]
Just wondering what errors get thrown for you besides shell out and string interpolation? In my implementation I set foodcritic to igonore most of the errors that have to do with metadata and template files because those are confusing and out of the scope of a text editor linter in my opinion.

**Comment by pelletiermaxime** [comment]
I wrote a sublimelinter plugin for foodcritic because I don't want to manually run foodcritic. Imo it isn't the job of the linter plugin to filter rules. That's the job of the .foodcritic file in your project.

**Comment by jawshooah** [comment]
I'm inclined to agree with @pelletiermaxime here; I don't think it's appropriate to exclude rules in the linter plugin itself. You can do that in the `args` setting.

**Comment by grotewold** [comment]
I'm not necessarily sure what response you all are looking for. I'm too agree with @pelletiermaxime but what does that mean for this issue, these projects, and package control?

I've had multiple repos made for a single linter before, those differences were resolved with abandonment of one side, or consolidation into a single project on neutral ground (SublimeLinter org). I'm all ears to anyone, I just need to know if we are waiting on an arbiter to make a decision or what?

**Comment by badmadrad** [comment]
I think this issue should be marked as closed as the package is published. I understand some of the issues to exclude the rules maybe aren't the best solution for everyone but rather than let the it stagnate I am glad we are moving forward with something. I will continue to work on a more elegant solution that suits everyone.
