### ISSUE TITLE
ignore indentation of any kind in SASS .scss files

### ISSUE THREAD

**Issue by alanfluff** [SublimeLinter/SublimeLinter3#342]
Pretty please, how do I get SL3 to ignore indentation?

And sorry Google and I failed to find how to do this without resorting to a post here...

**Comment by jawshooah** [comment]
Generally, this is something you would configure in the linter itself, not SL3. For example, if you are using RuboCop, you could add the following to your `.rubocop.yml`:

```yml
Style/IndentationWidth:
  Enabled: false
```

Or, if for some reason you want to leave the linter's own config alone (maybe you want the warnings for your CI process, but don't want to bother with them in your editor), you could ignore them in your `.sublimelinterrc` with the [`ignore_match` setting](http://www.sublimelinter.com/en/latest/linter_settings.html#ignore-match):

```json
{
  "linters": {
    "rubocop": {
      "ignore_match": "[Ii]ndent"
    }
  }
}
```

**Comment by alanfluff** [comment]
Uh. My bad, typo, I meant to type ST3 (Sublime Text 3).

Thanks very much for the reply. I'm not using RuboCop (as far as I know), only SublimeLinter3 and SublimeText 3 and editing .scss files.

**Comment by grotewold** [comment]
Hey! I'm not quite sure what you're asking... Do you want to change how ST3 does indentation? Like change it to 2 spaces instead of a 4 space tab?

Sorry, If this is a SublimeText question and not SL question, it will probably be better answered [here](http://www.sublimetext.com/forum/).

**Comment by alanfluff** [comment]
Thanks, no, not looking to make Sublime Text indent differently; I am trying to see how to get SublimeLinter 3 to not report/tag as error, a line that it does not think the indentation is correct in. i.e. I am trying to get SL3 to not treat and indentation as an error even if it's inconsistent.

**Comment by jawshooah** [comment]
My RuboCop example was just that, an example. I would imagine that any linters you may be using have their own config files with similar settings.

**Comment by alanfluff** [comment]
Thanks. I'll leave this open for now in as I clearly don't understand SublimeLinter3 well enough (I don't know name, location or contents I would need for an equivalent file to control .scss / .sass linting but thanks nonetheless for showing this is likely what I need to solve this).

**Comment by jawshooah** [comment]
Well, what linters are you using? I'm guessing [scss-lint](https://github.com/brigade/scss-lint), in which case you can find their config documentation [here](https://github.com/brigade/scss-lint#configuration).

**Comment by alanfluff** [comment]
> Well, what linters are you using?
My likely naive answer to that is "SublimeLinter 3". Other than SL3 I don't know what linters I have installed (I thought I'd just installed SublimeLinter 3, as a package, but it was months ago and so maybe at the time I also installed other support files).

But I'll go and do some research now, with your links to help (thanks) and hopefully solve, cheers.

**Comment by jawshooah** [comment]
SublimeLinter3 is not itself a linter, it's just a framework for linter plugins. If all you have installed is SublimeLinter3, you're not linting anything.

You probably also installed [SublimeLinter-scss-lint](https://github.com/attenzione/SublimeLinter-scss-lint) or [SublimeLinter-csslint](https://github.com/SublimeLinter/SublimeLinter-csslint).

**Comment by alanfluff** [comment]
Ah, that explains a lot, thanks for pointing that out! :)

**Comment by jawshooah** [comment]
No problem, glad I could help. :beers:
