### ISSUE TITLE
New linter: SublimeLinter-contrib-coffee-jshint

### ISSUE THREAD

**Issue by univerio** [SublimeLinter/SublimeLinter3#343]
https://github.com/univerio/SublimeLinter-contrib-coffee-jshint

Uses [`coffee-jshint`](https://github.com/Clever/coffee-jshint) to lint CoffeeScript files.

**Comment by grotewold** [comment]
* `linter.py` fails pep257 linting
* unnecessary imports from `__future__`, this code only runs in python3.3

after those are fixed please make a release.

THANKS!!

**Comment by univerio** [comment]
Done. Release is [0.0.1](https://github.com/univerio/SublimeLinter-contrib-coffee-jshint/tree/0.0.1).

**Comment by grotewold** [comment]
It's been added to Package Control, and you should see it within an hour. Thanks again!
