### ISSUE TITLE
File with settings on mac and windows

### ISSUE THREAD

**Issue by PixelT** [SublimeLinter/SublimeLinter3#344]
I have file with settings (scss.yml, .jshintrc etc.) on Dropbox 
It's possible / define this same files to usage on mac and windows (if yes - where or how?)

**Comment by jawshooah** [comment]
I'm not sure what this has to do with SublimeLinter3. Are you asking how to keep a config file—**any** config file—in sync between computers? What's wrong with git? We are on GitHub after all.

**Comment by PixelT** [comment]
I wrote it here, because SublimeLinter have settings section.
I would define this same file config for mac and win by this way:
```
args: [
"--config", "/path/to/file"
]
```
but path to the file (which I have on dropbox) is dfferent on mac / win

**Comment by jawshooah** [comment]
Ah, I misunderstood your question. You're not asking how to share your config files between OSes, you're asking how to point to those shared config files in the same way between OSes.

Mac and Windows paths are quite different, so I'd guess that the only way to accomplish this would be through environment variables. You can check out the [setting tokens](http://www.sublimelinter.com/en/latest/settings.html?highlight=environment%20variables#setting-tokens) section of the docs for how to use them.

For example, you could have a `JSHINTRC` environment variable that points to `/Users/my-name/.jshintrc` on Mac, and `C:\Users\my-name\.jshintrc` on Windows.

I'm not sure exactly what subset of environment variables are available to Sublime Text's python context, so this may not work after all. If it doesn't, I'm not sure how to help you :disappointed:

**Comment by jawshooah** [comment]
Actually, assuming your Dropbox directory is located at the same path relative to your home directory on both OSes, you may be able to do this:

```json
{
  args: ["--config", "${home}/Dropbox/path/to/file"]
}
```

**Comment by PixelT** [comment]
@jawshooah - it seems that the last code works. Thanks!

**Comment by jawshooah** [comment]
Glad to hear it :beers:
