### ISSUE TITLE
Sublimelinter-contrib-polylint

### ISSUE THREAD

**Issue by nomego** [SublimeLinter/SublimeLinter3#346]
New linter plugin for [polylint](https://github.com/PolymerLabs/polylint)

https://github.com/nomego/SublimeLinter-contrib-polylint

**Comment by grotewold** [comment]
Please make a release and I'll get this in Package Control. Thanks!

**Comment by nomego** [comment]
1.0.0 released.

**Comment by grotewold** [comment]
https://packagecontrol.io/packages/SublimeLinter-contrib-polylint 

Thanks again!
