### ISSUE TITLE
Toggle Linter should show current active if different than user

### ISSUE THREAD

**Issue by groteworld** [SublimeLinter/SublimeLinter3#348]
This issue is from #339 where after discussing `.sublimelinterrc` files, the Toggle Linter menu doesn't show the current linters that are active, but just the current setting in the SublimeLinter - User Settings.

It should show another message if different setting file is effecting this setting.

**Comment by braver** [comment]
If it were me I'd just rip out the `toggle linter` command. Do you really want it to go through the entire cascade of settings and figure out where to toggle something? But, I've always found the way this package (never seen anyone else do this) insist on editing settings via the command panel to be super weird and confusing. It makes it really hard to build a mental model of what that actually does, how the commands map to the settings (especially if there are also `.sublimelinterrc`), while just editing the setting is super easy. So I may be biased towards ripping out all the commands that edit settings. ;)

**Comment by braver** [comment]
Settings toggle commands have been removed in SL4, which also “solves” this problem.
