### ISSUE TITLE
New plugin for proselint, a linter for prose

### ISSUE THREAD

**Issue by suchow** [SublimeLinter/SublimeLinter3#350]
https://github.com/amperser/SublimeLinter-contrib-proselint

**Comment by grotewold** [comment]
I would recommend some general cleanup of your `README.md`. Your TravisCI link doesn't work, the contribution information is incorrect. After that please make a release and we'll get it into Package Control.

Thanks!

**Comment by suchow** [comment]
@grotewold Thanks, I updated it.

**Comment by grotewold** [comment]
Sorry, I still need a release. https://github.com/amperser/SublimeLinter-contrib-proselint/releases

**Comment by suchow** [comment]
@grotewold Oops, sorry, done: https://github.com/amperser/SublimeLinter-contrib-proselint/releases/tag/v0.3.5

**Comment by grotewold** [comment]
Added! Should show up in about an hour.
