### ISSUE TITLE
Any Pascal-Linter out there?

### ISSUE THREAD

**Issue by chrisheib** [SublimeLinter/SublimeLinter3#351]
Hey, i've been trying to find a linter for pascal, but didn't succeed. The only thing i found was a linter embedded in the free-pascal Project, but that seems to be compiler-dependent and not converted to SublimeLinter aswell. 
Any other plugin that does the job im missing out on?

Edit: Free Pascal Project of cause.

**Comment by grotewold** [comment]
Nope, there is nothing currently out there, if you'd like to add the one you found, that would be great!

Documentation can be found [here](http://www.sublimelinter.com/en/latest/creating_a_linter.html)

**Comment by grotewold** [comment]
Closing because questions was answered. Good Luck! :beers:
