### ISSUE TITLE
When an error is highlighted by the linter, putting the cursor on the offending line to show the error message inline(as a popup)

### ISSUE THREAD

**Issue by darkred** [SublimeLinter/SublimeLinter3#354]
I've installed `SublimeLinter3` with `SublimeLinter3-jshint`.
As I've noticed
> when an error is highlighted by the linter, putting the cursor on the offending line 
> will result in the error message being displayed on the status bar.

So, could you please tell me, is there a way, when putting the cursor on the offending line (and when hovering mouse on the relevant gutter mark)
to display the error message inline (as a popup), too?
_(I searched the docs but couldn't find any relevant info)._
I think it would be practical to show it inline, instead of only showing it in the status bar.

If not, then that's my feature request.

**Comment by grotewold** [comment]
#178 has discussion of this and #318 is someone's early attempts at this. Thanks!

**Comment by darkred** [comment]
Thanks for replying :+1:
