### ISSUE TITLE
<script> in HTML file results in "Parsing error: Unexpected token <"

### ISSUE THREAD

**Issue by OliverJAsh** [SublimeLinter/SublimeLinter3#356]
I am using the ESLint plugin for SublimeLinter.

``` json
// package.json
{
  "name": "eslint-html",
  "private": true,
  "dependencies": {
    "eslint": "^1.7.2"
  }
}
```

``` json
// .eslintrc
{}
```

``` html
<!-- foo.html -->
<html>
    <body>
        <script>
            var foo = function () {

            };
        </script>
    </body>
</html>
```

I get the following error: `Parsing error: Unexpected token <` at line 3 at the start of `<script>`.

I have also tested this with the jscs linter plugin, which gaves me exactly the same error.

I understand SublimeLinter patches the HTML syntax so it can lint inline scripts. It reads the other HTML fine, but stumbles on `<script>`. This suggests that SublimeLinter works fine for excluding HTML, just not the script tag?

I have tried restarting Sublime.

Originally posted at https://github.com/roadhump/SublimeLinter-eslint/issues/99

**Comment by aarongeorge** [comment]
This happens with SublimeLinter-jscs also.

**Comment by b12k** [comment]
Same issue.
"Error: Parsing error: unexpected token <, Line 8..."
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <script type="text/javascript"></script>
</body>
</html>
```

**Comment by nvaldes** [comment]
Experiencing same issue with ESLint here.

**Comment by grotewold** [comment]
So this is an issue with the syntaxes that ST provide. When this was created I made an issue with SublimeText https://github.com/sublimehq/Packages/issues/106. If it's fixed it would be supportive in ST 3092+. SublimeLinter used to supply syntaxes with this fixed, but were outdated to other syntax changes and were a bear to maintain so they were removed to use the default syntaxes. Obviously, this has broken the inlaid linting in html files.

No real quick fix on this, may need to revert those commits and add logic to not use if version 3092+

Hopefully SublimeHQ will pick up that issue soon.

**Comment by hyperknot** [comment]
I've run into the same issue as well. Is there a way to disable lining on html sources as a temporary fix?

**Comment by dburrows** [comment]
You can turn eslint off temporarily for files with .html files extension with this setting: 

```
"eslint": {
  "@disable": false,
  "args": [],
  "excludes": ["*/*.html"]
}
```

**Comment by hyperknot** [comment]
@dburrows thanks, it's a good workaround for now

**Comment by tiagoporto** [comment]
@dburrows Which file I put this?

**Comment by grotewold** [comment]
It would go in the `SublimeLinter.sublime-settings` file. It should already be there, you'll just need to add the `"*/*.html"`

**Comment by tiagoporto** [comment]
Thanks @grotewold

**Comment by kaste** [comment]
@grotewold I don't know actually what you're after. Do you know a particular commit that introduced this issue, so I could make a diff of a working language spec and a buggy one? AFAIK the HTML package on SublimeHQ is on the initial commit. 

I tried some older version of ST3 and linting did not work there either. Do you have a specific working build of ST?

**Comment by groteworld** [comment]
As of https://github.com/sublimehq/Packages/commit/0417e42da416ec7f4fced63e84316944fc5d257f these changes have been made to the default HTML syntax. You will need newest build ST3103.

CSS may be having issue, I'm confirming in Packages issue sublimehq/Packages#106

**Comment by groteworld** [comment]
https://github.com/sublimehq/Packages/commit/f9b9e10b8d38b233c1078a425b6c1c026a62aa63 fixes issues with `<style>` and `<script>` tags. Please upgrade to SublimeText 3103 and download the latest from master of https://github.com/sublimehq/Packages, or wait until the next ST release.

**Comment by groteworld** [comment]
Build 3109 (released in dev today) has these fixes built-in. Hopefully it will reach beta release soon.

Closing issue as this seems fixed.

**Comment by codeofsumit** [comment]
I still have this problem in atom :-/
![image](https://cloud.githubusercontent.com/assets/2399810/21183213/2d95ce76-c207-11e6-80d5-a4c8e25f41df.png)

**Comment by ManasN** [comment]
@codeofsumit https://github.com/BenoitZugmeyer/eslint-plugin-html this solved my problem

**Comment by dsl101** [comment]
I've still got this problem on ST 3126 (stable channel). I've also installed eslint globally, and installed the plugin @ManasN mentioned (although I wasn't entirely sure if that was just Atom specific).

I'm presuming the changes @groteworld talked about in 3109 are in stable now? Anything else I could check for?

**Comment by EdenGoforIt** [comment]
> I still have this problem in atom :-/ ![image](https://cloud.githubusercontent.com/assets/2399810/21183213/2d95ce76-c207-11e6-80d5-a4c8e25f41df.png)

what extension do you use to show eslint error so nicely ?
