### ISSUE TITLE
Typechecking/linting haskell using hdevtools

### ISSUE THREAD

**Issue by ch1bo** [SublimeLinter/SublimeLinter3#357]
https://github.com/ch1bo/SublimeLinter-contrib-hdevtools

**Comment by grotewold** [comment]
Please make a Github release.


THANKS!

**Comment by ch1bo** [comment]
released version 1.0.0
https://github.com/ch1bo/SublimeLinter-contrib-hdevtools/commit/708442f4610e0445e681c7fb0722d363881467a5

**Comment by grotewold** [comment]
Added! Should show up in about an hour.
