### ISSUE TITLE
Is there a way to show errors like XCode does?

### ISSUE THREAD

**Issue by fclaussen** [SublimeLinter/SublimeLinter3#359]
I have a hard time looking at the status bar and reading all the useless information that is there(like column #) to find what is really important like my lint errors.

And sometimes nothing shows up. I don't know if it is because the message + other things on the bar gets too big and would not fit the status bar anymore or some incompatibility with another package might be causing this.

Would it be possible to achieve something like this image in sublimetext and keep things separate?

![Xcode Error Highlight](http://static1.squarespace.com/static/53c5b554e4b0627010c57fff/t/54526f2ee4b0a45b47d5f345/1414688560383/)

**Comment by grotewold** [comment]
Currently no, this wouldn't be possible. It is currently in progress to get a popup in the window though which would help with your difficulty with the status bar.

See https://github.com/SublimeLinter/SublimeLinter3/issues/178

**Comment by fclaussen** [comment]
Thanks @grotewold
