### ISSUE TITLE
Using the new popup API introduced in ST 3072 to show errors and warning inline

### ISSUE THREAD

**Issue by aziz** [SublimeLinter/SublimeLinter3#360]
[ST 3072](http://www.sublimetext.com/forum/viewtopic.php?f=2&t=17658&p=66237) introduced a simple HTML popup that sounds perfect for showing errors and warnings inline instead of showing them in status bar.

**Comment by grotewold** [comment]
Consolidated to https://github.com/SublimeLinter/SublimeLinter3/issues/178
