### ISSUE TITLE
SublimeLinter: WARNING: htmltidy deactivated, cannot locate 'tidy' 

### ISSUE THREAD

**Issue by aadityataparia** [SublimeLinter/SublimeLinter3#363]
SublimeLinter: WARNING: htmltidy deactivated, cannot locate 'tidy'

**Comment by grotewold** [comment]
Do you have the tidy program installed? Is it correctly in path?

**Comment by aadityataparia** [comment]
Problem solved, but how to I correct whole document?

**Comment by groteworld** [comment]
Currently this is not possible. Sorry, SublimeLinter does not support autofixers. I'll let you know if we ever get this ability.
