### ISSUE TITLE
Real world example using <near>

### ISSUE THREAD

**Issue by idleberg** [SublimeLinter/SublimeLinter3#365]
I'm really desperate here, otherwise I wouldn't post this as an issue. I searched GitHub for linters making use of `<near>`, but there are very few to learn from. I put a bounty on my [Stackoverflow](https://stackoverflow.com/questions/32339670/highlighting-in-custom-sublimelinter-plugin) question and asked on [Reddit](https://www.reddit.com/r/SublimeText/comments/3ofxdb/creating_a_sublimelinter_plugin_i_need_help_with/) – there are very few people familiar with the matter. So I was hoping to find some help, even if it's by improving the existing documentation with a real world example.

**Comment by braver** [comment]
Yeah, I think it's safe to say this isn't the most active place in the world. The [forum](https://forum.sublimetext.com) and discord etc. may be better places to get info like this.
