### ISSUE TITLE
New linter: SublimeLinter-contrib-fecs

### ISSUE THREAD

**Issue by robbenmu** [SublimeLinter/SublimeLinter3#367]
https://github.com/robbenmu/SublimeLinter-contrib-fecs

This linter provides an interface to the [fecs](https://github.com/ecomfe/fecs) linter for javascript.

**Comment by grotewold** [comment]
You are too patient, I'm sorry it took me this long to get to this review

The link to the TravisCI badge is broken, the syntax in the readme is still `"syntax"`, and remove the example settings at bottom of readme.
After all that tag your first release and it will be sent to Package Control.

Thanks!
