### ISSUE TITLE
tmp files copied from buffer losing extension

### ISSUE THREAD

**Issue by donabrams** [SublimeLinter/SublimeLinter3#368]
For some reason, tmp files copied from the buffer for linting are losing their extension. This PR may fix this: https://github.com/SublimeLinter/SublimeLinter3/pull/259. Related issue in the sass-linter: https://github.com/skovhus/SublimeLinter-contrib-sass-lint/issues/4#issuecomment-155185877

**Comment by skovhus** [comment]
@donabrams I cannot reproduce this if the syntax of the file is set.
