### ISSUE TITLE
Can't choose Gutter Theme

### ISSUE THREAD

**Issue by joebien** [SublimeLinter/SublimeLinter3#369]
OS 10.10.5
ST 3 build 3083

Linting is working but I get dark triangles in gutter for all errors no matter what theme I choose.

Console shows:
reloading Packages/User/SublimeLinter.sublime-settings
reloading Packages/User/SublimeLinter.sublime-settings
reloading Packages/User/SublimeLinter.sublime-settings
reloading Packages/User/SublimeLinter.sublime-settings

themes are located in Application Support/Sublime Text 3/Packages/User/SublimeLinter/gutter-themes

Please help!!!!!!

**Comment by grotewold** [comment]
That surely isn't your entire console. Could you post a fresh restart of sublime text's console?

**Comment by joebien** [comment]
Oh. Thanks. Here it is.

startup, version: 3083 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/joebien/Library/Application Support/Sublime Text 3/Packages
state path: /Users/joebien/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/joebien/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.687156
first paint time: 0.77499
startup time: 0.798461
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 1Self.1self
reloading plugin 1Self.1selfOpenDashboardCommand
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SublimeLinter-annotations.linter
SublimeLinter: annotations linter loaded 
reloading plugin JSHint Gutter.JSHint
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
Initializing 1self plugin
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: /var/folders/fc/yd4kpf7s0pd_kl9_vjjsq13r0000gn/T/SublimeLinter3-joebien 
SublimeLinter: annotations activated: <builtin> 
Package Control: No updated packages
SublimeLinter: annotations activated: <builtin>

**Comment by grotewold** [comment]
Try disabling the jshint gutter plugin you have installed. Not sure if that's the issue but it definitely could conflict as ST only allows one gutter icon at a time.

**Comment by joebien** [comment]
OK. Now I have no linting at all.

**Comment by grotewold** [comment]
Ok, so I assume you're trying to use jshint? You need to install the SublimeLinter-jshint package. Being sure to have the jshint CLI reachable in your path as well. Check out http://www.sublimelinter.com for more information on how to configure SL

**Comment by joebien** [comment]
OK. I got it. I had to install jshint on my system using the terminal. I don't remember having to do that before and I had it working. ??

Any way thanks a million. You rock.

**Comment by grotewold** [comment]
Glad we figured it out! Thanks for using SublimeLinter
