### ISSUE TITLE
Question: Any idea why my plugin build is failing?

### ISSUE THREAD

**Issue by benedfit** [SublimeLinter/SublimeLinter3#373]
See: https://travis-ci.org/benedfit/SublimeLinter-contrib-jade-lint

I'm a Python noob, but I tried fixing the error by removing the blank line in question, only for it to return another error saying I needed a line. Can anyone help?

**Comment by grotewold** [comment]
duplicate of https://github.com/SublimeLinter/SublimeLinter-pep257/issues/8
