### ISSUE TITLE
New linter: SublimeLinter-contrib-reek

### ISSUE THREAD

**Issue by kruszczynski** [SublimeLinter/SublimeLinter3#374]
https://github.com/codequest-eu/SublimeLinter-contrib-reek

This linter provides an interface for [reek](https://github.com/troessner/reek) linter for ruby.

**Comment by grotewold** [comment]
I'm sorry I didn't get to this one faster,

Please tag the first release and it will be on its way to Package Control!

Thanks!

**Comment by kruszczynski** [comment]
Done! :)

**Comment by grotewold** [comment]
Everything looks good and I'm seeing it in PC.

Thanks again!
