### ISSUE TITLE
Linter for Cudatext

### ISSUE THREAD

**Issue by Alexey-T** [SublimeLinter/SublimeLinter3#376]
Hi developers;
I want to ask: is it hard to make port of Linter to CudaText (uvviewsoft.com) ?
API doc is here,
http://wiki.freepascal.org/CudaText_API
Thanks

**Comment by grotewold** [comment]
The best I can help you is to say: fork SublimeLinter3, find everywhere the `sublime`, `sublime_plugin`, etc. imports are being used and find the equivalent in the CudaText API. I can't promise it will ever work, but it's your easiest bet for trying to quickly port it over. If you do get it to work, the majority of SL-linters should work with it.

**NOTE:** I don't have time to go through the CudaText APIs so this is complete speculation. I saw it was python. but how the plugins are loaded and all of that I'm clueless.

**Comment by grotewold** [comment]
Closing as this isn't something SL can do.
