### ISSUE TITLE
Most linters not working

### ISSUE THREAD

**Issue by WilliamNurmi** [SublimeLinter/SublimeLinter3#379]
The only working linters seem to be `php` and `phpmd`. I'm switching to working with python and have installed `pyflakes`, `pep8` and `pylint`. All of these work fine from command line. However, in sublime text, I'm getting no indication that the newcommers would be activated and no error message whatsoever.

The only visible problem I've found is that there seems to be some remnant SublimeLinter installation, since the Package Settings menu lists SublimeLinter twice (both pointing to the same settings files) and the right click menu has most options as duplicated. Removing SublimeLinter and all linters through package control leaves the extra menus in place. I've had a lot of trouble configuring xDebug and some other packages earlier, so I really wouldn't want re-install SublimeText from scratch. However, linting with phpmd works fine so I don't think the duplicate installation is the core issue here.

I'm running the latest SublimeText 3 Build 3083 on OsX 10.11.1.

Console output contains nothing about the inactive linters:

```
[2015-11-30 13:46:47,019 - WARNING  - process] Could not import subprocess32 module, falling back to subprocess module
first paint time: 4.72369
Package Control: No updated packages
reloading Packages/User/SublimeLinter.sublime-settings
[2015-11-30 13:47:12,728 - WARNING  - codeintel.pythoncile] Python Syntax Error in '/srv/www/analysis.XXX.com/usheat/main.py': invalid syntax (<unknown>, line 12)
SublimeLinter: php activated: /usr/bin/php 
SublimeLinter: phpmd activated: /Users/wnurmi/.composer/vendor/bin/phpmd 
SublimeLinter: chdir not set or invalid, using /srv/www/analysis.XXX.com/include/YYY 
SublimeLinter: php: Db.php ['/usr/bin/php', '-l', '-n', '-d', 'display_errors=On', '-d', 'log_errors=Off'] 
SublimeLinter: php output:
No syntax errors detected in -
```

SublimeLinter.sublime-settings

```
{
    "user": {
        "debug": true,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {
            "pep8": {
                "@disable": false,
                "args": [],
                "excludes": [],
                "ignore": "",
                "max-line-length": 80,
                "select": ""
            },
            "php": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "phpmd": {
                "@disable": false,
                "args": [
                    "/users/wnurmi/Documents/phpmd-ruleset.xml"
                ],
                "excludes": [],
                "rulesets": "cleancode,codesize,controversial,design,naming,unusedcode"
            },
            "pyflakes": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "pylint": {
                "@disable": false,
                "args": [],
                "disable": "",
                "enable": "",
                "excludes": [],
                "paths": [],
                "rcfile": "",
                "show-codes": true
            }
        },
        "mark_style": "outline",
        "no_column_highlights_line": false,
        "passive_warnings": true,
        "paths": {
            "linux": [],
            "osx": ["/usr/local/bin"],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": ["/usr/local/bin"],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": true,
        "show_marks_in_minimap": false,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "php": "html",
            "python django": "python"
        },
        "warning_color": "DDB700",
        "wrap_find": true
    }
}
```

I do think I have my paths setup (in both sublime settings and PATH):

```
$SHELL -l -c '/usr/bin/which pylint'
/usr/local/bin/pylint
```

Anyone ever tackled similar issues? Any help would be so much appreciated!

**Comment by grotewold** [comment]
Does your Packages directory show a SublimeLinter folder? if there are remnants of an install you should be able to delete them from there. Try a full reinstall of SL through package manager after, and see if it doesn't clear up the issue.

**Comment by WilliamNurmi** [comment]
Thanks Blake!

I removed an extra SublimeLinter folder from the packages user directory and the extra menu entries went with it. Unfortunately the pylint issue still persists after reinstalling. The only console log entries mentioning pylint are still

reloading plugin SublimeLinter-pylint.linter
SublimeLinter: pylint linter reloaded

Other than that, no activations, no errors, no nothing.

**Comment by grotewold** [comment]
Sweet! Well one error down.  Do you have debug mode on? Toggle that setting and restart SublimeText  then post all the console outputs. This will help me get s better idea of what's happening.

**Comment by WilliamNurmi** [comment]
I have ```"debug": true``` in SublimeLinter user settings file and this is all I get in Sublime Text console after restarting and loading opening py and php files with problems.
```
first paint time: 8.97995
[2015-12-01 16:32:45,555 - WARNING  - process] Could not import subprocess32 module, falling back to subprocess module
SublimeLinter: phpmd activated: /Users/wnurmi/.composer/vendor/bin/phpmd 
SublimeLinter: chdir not set or invalid, using /srv/www/analysis.XXX.com/include/data_analysis2 
SublimeLinter: phpmd: Db.php ['/Users/wnurmi/.composer/vendor/bin/phpmd', '@', 'text', '/users/wnurmi/Documents/phpmd-ruleset.xml', 'cleancode,codesize,controversial,design,naming,unusedcode'] 
SublimeLinter: phpmd output:

Warning: date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /Users/wnurmi/.composer/vendor/phpmd/phpmd/src/bin/phpmd on line 24

/private/var/folders/9q/fxtzqpz50kj7yy9gwnm6wdgc0000gn/T/SublimeLinter3-wnurmi/Db.php:18	The class Db has a coupling between objects value of 41. Consider to reduce the number of dependencies under 13.
```

Not a whole lot. The ```chdir``` seems to stem from phpmd linting, since I do not see it if I disable that linter.

Again, thanks a lot for helping!

**Comment by iad42** [comment]
This ticket never solved?

Have pretty much the same issue: SublimeLinter w/o errors and with enabled pylint does nothing

**Comment by braver** [comment]
@iad42  Pylint seems to have trouble getting started if you have more than one version of Python. See also [this](https://github.com/SublimeLinter/SublimeLinter-pylint/issues/12). Following the info in that issue I got it running by installing pylint for both Python3 and Python2 (running macOS Sierra).

There usually isn't a global problem with linters starting. I haven't seen cases where simply "nothing works". However, there are *so* many ways each of the linters may fail to work. 

@WilliamNurmi from reading this I don't have a clear idea on what problems remain for you. It's also been a while... Anything I can help you debug?

**Comment by braver** [comment]
🤷‍♂️ We'll re-open if there's news.
