### ISSUE TITLE
SublimeLinter ignore_match not working when extension is specified

### ISSUE THREAD

**Issue by colin-marshall** [SublimeLinter/SublimeLinter3#380]
I'm trying to get **SublimeLinter** and **HTMLTidy** to ignore certain php warnings. Specifically the  `missing <!DOCTYPE> declaration`, `inserting implicit <body>`, and `inserting missing 'title' element`. It tells you right in the docs how to do this:

```json
{
"ignore_match": [
    "missing <!DOCTYPE> declaration",
    "inserting (?:implicit <body>|missing 'title' element)"
    ]
}
```

Adding that to my SublimeLinter user settings file worked fine. The problem is that I want it only to apply to PHP files, because using just the above will also ignore it on HTML files.

The docs have an example for applying `ignore_match` only to certain extensions:

```json
{
"ignore_match": {
    "inc": [
        "missing <!DOCTYPE> declaration",
        "inserting (?:implicit <body>|missing 'title' element)"
        ]
}
```

So I copied that and changed the `inc` to `php` and I still get those warnings on php files.

Here is what the `htmltidy` section of my SublimeLinter settings file looks like:

```json
"htmltidy": {
            "@disable": false,
            "args": [],
            "excludes": [],
            "ignore_match": {
                "php": [
                    "missing <!DOCTYPE> declaration",
                    "inserting (?:implicit <body>|missing 'title' element)"
                 ]
            }
    }
```

Any idea why `ignore_match` works as it is supposed to until I specify an extension that the `ignore_match` rule is supposed to apply to? Thanks!!!

**Comment by colin-marshall** [comment]
This is a bug. See the accepted answer on my StackOverflow question:
http://stackoverflow.com/questions/34057863/sublimelinter-ignore-match-not-working-when-extension-is-specified

**Comment by grotewold** [comment]
Thanks to @alkuzad, in both SO and here, this has been corrected. Thanks for your help!

**Comment by colin-marshall** [comment]
Thanks @alkuzad and @grotewold!

**Comment by ctf0** [comment]
@groteworld am still having this issue
```json
"htmltidy": {
    "@disable": false,
    "args": [],
    "excludes": [],
    "ignore_match": {
        "blade": [
            "(<script>|<img>|<a>) escaping malformed URI reference",
            "inserting (?:implicit <body>|missing 'title' element)",
            "missing <!DOCTYPE> declaration",
            "plain text isn't allowed in <head> elements"
        ]
    }
},
```
