### ISSUE TITLE
New linter: SublimeLinter-contrib-cheetah-flake

### ISSUE THREAD

**Issue by jdb8** [SublimeLinter/SublimeLinter3#381]
https://github.com/jdb8/SublimeLinter-contrib-cheetah-flake

This linter provides an interface to the [cheetah-flake](https://github.com/asottile/cheetah_lint) linter for [yelp_cheetah](https://github.com/Yelp/yelp_cheetah) templates.

**Comment by grotewold** [comment]
Sorry that I got behind on this!

Fix the link in your TravisCI badge and tag your first release after. SublimeLinter-contrib-cheetah-flake will start showing in Package Control soon after.

Thanks!

**Comment by jdb8** [comment]
Thanks for including it. Tagged and is now showing up on Package Control :)

I'll close this now.
