### ISSUE TITLE
New linter: mypy

### ISSUE THREAD

**Issue by fredcallaway** [SublimeLinter/SublimeLinter3#382]
https://github.com/fredcallaway/SublimeLinter-contrib-mypy

**Comment by grotewold** [comment]
Sorry I got behind on this!

Fix your TravisCI build status badge and tag your first release. Then it will start showing in Package Control.

Thanks!

**Comment by fredcallaway** [comment]
All set (I think!)

**Comment by grotewold** [comment]
Badge is fixed but link is broken. I'm seeing it in Package Control as well.

Thanks again!

**Comment by fredcallaway** [comment]
Ah, duh! Fixed.
