### ISSUE TITLE
Renaming a linter?

### ISSUE THREAD

**Issue by benedfit** [SublimeLinter/SublimeLinter3#383]
Because of reasons; https://github.com/pugjs/jade/issues/2184, Jade is being renamed to Pug in the not so distant future. At this point `jade-lint` will be deprecated in favour of `pug-lint`. 

My question is, should `SublimeLinter-contrib-jade-lint` therefore be renamed, or should a new linter named `SublimeLinter-contrib-pug-lint` be created?

**Comment by grotewold** [comment]
We would rename the repo and the make the change in package control, package control has syntax for this.

**Comment by benedfit** [comment]
`SublimeLinter-contrib-jade-lint` has now been renamed https://github.com/benedfit/SublimeLinter-contrib-pug-lint. Could you please update this in package control?

Cheers

**Comment by grotewold** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/43672720c2b80af3b8f1781d69be4aac7101ed9f

It would be best if you made a package control message to notify users of the change.

Thanks for your patience!
