### ISSUE TITLE
Cannot get new linter plugin to lint files

### ISSUE THREAD

**Issue by sparr** [SublimeLinter/SublimeLinter3#384]
EDIT: this issue has narrowed in scope, the current problem is at the bottom of the thread

https://github.com/sparr/SublimeLinter-contrib-erlint

If I modify linter.py with the console open and debug mode on I see these messages:

    reloading plugin SublimeLinter-contrib-erlint.linter
    SublimeLinter: erlint linter reloaded

That is the only console output I ever get regarding this linter. I can run the erlint binary from a terminal. Moving the erlint binary so that it is not runnable from a terminal has no effect on the behavior in ST, which makes me thing that SL is not getting to the point of trying to run/version the binary. Opening, modifying, and saving .erl files produces no visible activity from SublimeLinter in the gutter or status bar or console, nor does manually setting an arbitrary file's Syntax to Erlang. I suspect I've overlooked something trivial in configuring the linter plugin.

**Comment by grotewold** [comment]
Giving it a quick look, your syntax name should be lowercase. Not at a computer so can't dive deep right now but try that out.

**Comment by sparr** [comment]
Changing the syntax to lowercase has one effect, it makes the linter aware of the missing/present erlint binary and adds this console line when saving/modifying linter.py if erlint is not available:

    SublimeLinter: WARNING: erlint deactivated, cannot locate 'erlint' 

However there's still no interaction with open .erl files.

**Comment by grotewold** [comment]
Right, because like it says it can't find erlint in your path. Make sure you've read the SublimeLinter configuration and troubleshooting for path setting

**Comment by sparr** [comment]
I had. It seems that the "computed PATH" reported during debug isn't the actual path it's using. I'll troubleshoot that later. For now, I've just shoved it in my sublime settings paths.

New problem! When I modify a .erl file, the linter runs... with no arguments. Here's the console output when I modify a .erl file:

    SublimeLinter: chdir not set or invalid, using /Users/crisher/src/erlang_practice/erlint/src 
    SublimeLinter: erlint: erlint.erl ['/Users/crisher/.local/bin/erlint'] 
    SublimeLinter: erlint output:
    Usage: erlint filename.erl 

Just to make sure the fault wasn't with the erlint binary mis-handling a parameter, I simply linked erlint on my path to /bin/echo, and now I get this:

    SublimeLinter: chdir not set or invalid, using /Users/crisher/src/erlang_practice/erlint/src 
    SublimeLinter: erlint: erlint.erl ['/Users/crisher/.local/bin/erlint'] 
    SublimeLinter: erlint output:
    [this line is empty in the console]

**Comment by sparr** [comment]
If I change the `cmd` from "erlint" to "erlint @" then it gets called with a literal at symbol as the parameter, not the filename. So the filename isn't being appended AND it's not being substituted for @.

**Comment by jawshooah** [comment]
`erlint` does not read data from `stdin`, so `tempfile_suffix = None` won't work. Try `tempfile_suffix = 'erl'`.

Here's the [documentation for `tempfile_suffix`](http://www.sublimelinter.com/en/latest/linter_attributes.html#tempfile-suffix).

**Comment by sparr** [comment]
Thanks, that gets it working. Only last concern, which might be nothing, is that my warnings are showing up in the status bar as "Error:".

**Comment by jawshooah** [comment]
Nothing out of the ordinary there; that's how it works for all linter plugins at the moment.
