### ISSUE TITLE
enable/disable show_errors_on_save per linter

### ISSUE THREAD

**Issue by stoivo** [SublimeLinter/SublimeLinter3#386]
Is there some option to use show_errors_on_save for one linter like PHP but not have it if it is ruby or JS?

Other than this, Linter is grate :sparkles:

**Comment by ajmichels** [comment]
Seems like this might be an [x/y problem](http://xyproblem.info) scenario. Can you provide more context for what you are trying to do?

**Comment by braver** [comment]
Yeah, uhh... why?

**Comment by stoivo** [comment]
Okey, so what I want is to enable show_errors_on_save  for the php linter since my php code has lot more issues and would like the linter to be more forcing. While in my ruby code some of the linting messages for ruby are more like recomondations.

**Comment by braver** [comment]
Ok, this'll probably end up as "won't fix" and I wouldn't expect traction on it any time soon anyway, but let's keep it around as a feature request.

**Comment by stoivo** [comment]
I don't think it is worth having it open even. My case is long solved by allways disabling it.

**Comment by braver** [comment]
That's also fine!
