### ISSUE TITLE
Removed/Unavailable from Package Control

### ISSUE THREAD

**Issue by vikrantpogula** [SublimeLinter/SublimeLinter3#388]
It seems like that both the core package and many contrib modules can't be installed from Package Control. Examples :

- https://packagecontrol.io/packages/SublimeLinter
- https://packagecontrol.io/packages/SublimeLinter-contrib-eslint

The results are also not found in sublime-text-3 (`cmd+shift+p - Install Package`)

Would appreciate any pointers on how to fix this !

**Comment by grotewold** [comment]
So not 100% on this, but I believe Package Control is having issues. If you really need SL now i encourage you to download the repo for now, otherwise hopefully this will be resolved shortly

**Comment by vikrantpogula** [comment]
@grotewold you're right but that was a few hours ago. 
ref : https://github.com/wbond/package_control/issues/1057

**Comment by vikrantpogula** [comment]
Everything seems back to normal now. I am closing this issue.

**Comment by DjebbZ** [comment]
Problem happening again. Typing `SublimeLinter` shows only plugins, and doesn't show `SublimeLinter` either. Noticed this yesterday (January 28th).

**Comment by groteworld** [comment]
@DjebbZ Make sure you don't have SublimeLinter already installed in your ST `Packages` folder. I'm seeing the project still on Package Control, so hopefully that is your issue. Sorry you're having problems.
