### ISSUE TITLE
Any way to increase gutter width?

### ISSUE THREAD

**Issue by liquidlotus** [SublimeLinter/SublimeLinter3#389]
After checking the docs I didn't find any information pertaining to increasing gutter width. My gutter icons are bleeding over double digit plus line numbers. Is there any way to fix this?
<img width="444" alt="gutter issue" src="https://cloud.githubusercontent.com/assets/3455435/12118312/bee9ddd2-b393-11e5-8a6d-dd52fe8d756b.png">

**Comment by grotewold** [comment]
A much requested feature in ST, sadly no there really isn't. You'll need to resize your icons to fit. Use the largest SublimeLinter provided icon as a guide line for how small. Sorry again!

**Comment by liquidlotus** [comment]
Alright, thanks.
