### ISSUE TITLE
Portable issues with pylint

### ISSUE THREAD

**Issue by Zonker96** [SublimeLinter/SublimeLinter3#390]
Hey everybody, 
I used sublimeLinter a while on my Pc. Now I want to make a portable version working with SublimeLinter and pylint. But I getting issues with pylint. They told me the issue is by SublimeLinter so I set up this issue post.

I will Link the post, so we can find which doesn't work fine. 

Link: https://github.com/SublimeLinter/SublimeLinter-pylint/issues/22

Tray

**Comment by NotSqrt** [comment]
Specifically, I suspect that relative paths to executables declared in the settings should be made absolute at some point when loading the settings, if that's not already the case.

**Comment by grotewold** [comment]
Following @NotSqrt's suggestion, the `"path"` SublimeLinter setting now resolves relative paths to an absolute path. Relative paths should be relative to the directory the SublimeText executable is located in.

**Comment by NotSqrt** [comment]
Nice !

**Comment by grotewold** [comment]
Thanks for the issue @Zonker96
