### ISSUE TITLE
Tempfile created for a inline-style tag contains HTML

### ISSUE THREAD

**Issue by brainz80** [SublimeLinter/SublimeLinter3#392]
Tempfile created for a inline-style tag contains HTML.
Took a while to confirm this because the tempfile is automatically removed after it been processed.

```css
	<style>
		body { background-color: black; color: white; }
	</style>

**Comment by grotewold** [comment]
This sounds like https://github.com/SublimeLinter/SublimeLinter3/issues/356 is the cause. Sorry that this is currently happening.

**Comment by groteworld** [comment]
Update in #356. consolidating this to that issue.
