### ISSUE TITLE
Feature request: entire line highlight

### ISSUE THREAD

**Issue by Gabriel-p** [SublimeLinter/SublimeLinter3#394]
I'm using this package along with Anaconda when working on my Python scripts. The latter will lint the code, and the single-word highlighting of SublimeLinter often gets drowned in a sea of underlines and highlights.

I searched the docs, but the [available options](http://sublimelinter.readthedocs.org/en/latest/global_settings.html#mark-style) for `mark_style` all seem to highlight a single word (ie: TODO, FIXME, etc.)

Could an option be added to highlight the _entire line_ to improve visibility?

**Comment by XenHat** [comment]
I second this feature request.

**Comment by braver** [comment]
I would advise to use the gutter marks to indicate lines that have errors. Starting a shouting war between linters doesn’t sound like a good way forward to me.

**Comment by FichteFoll** [comment]
This is also relevant for linters that do not provide column numbers, in which case SL only shows the gutter icon iirc.

**Comment by Gabriel-p** [comment]
@braver but then you'd have a gutter war with packages like [gitgutter](https://github.com/jisaacks/GitGutter)...

**Comment by braver** [comment]
Good point. There are certainly cases for this. Given the current state of affairs I wouldn’t hold my breath for this feature to land though.

**Comment by braver** [comment]
> This is also relevant for linters that do not provide column numbers, in which case SL only shows the gutter icon iirc.

There is an option to highlight the entire line for this case.

> but then you'd have a gutter war with packages like gitgutter

Gitgutter allows SL to have priority over its gutter marks.

We're working on a new version that has per-linter priorities for gutter marks, and allows you to configure styles per linter. This should allow you to have "light" highlighting of most errors (e.g. stippled underline), and "heavy" highlighting for others (e.g. fill). https://github.com/SublimeLinter/SublimeLinter3/pull/666

**Comment by braver** [comment]
The SL4 beta provides plenty of features to make highlights for some linters stand out against others, check it out!  https://github.com/SublimeLinter/SublimeLinter3#sublimelinter-4-beta
