### ISSUE TITLE
SublimeLinter Code of Conduct

### ISSUE THREAD

**Issue by groteworld** [SublimeLinter/SublimeLinter3#397]
Been wanting to do this for a while, recent comments reminded me.

Possible code of conducts to add to organization:
- [Open Code of Conduct](http://todogroup.org/opencodeofconduct/#SublimeLinter/hello@grotewold.me)
- [Contributor Covenent](http://contributor-covenant.org/version/1/3/0/)
- others?

**Comment by braver** [comment]
Shouldn’t we prioritize reacting to valid and valuable contributions (27 open pull requests right now) over yack shaving? If nobody’s contributing, or contributions are ignored, why have a code of conduct? 

Aside: same goes for the donations. It feels weird to ask for them if there is only one guy left to maintain this thing and he doesn’t even have the time for it.

**Comment by braver** [comment]
Ouch, sorry about my tone in that previous message. I'm not against COC's but I'd like to prioritise contributability first. If we feel the community needs more guidance it'll come up again and we'll make time for it then.
