### ISSUE TITLE
csslint show only errors

### ISSUE THREAD

**Issue by ildarkhasanshin** [SublimeLinter/SublimeLinter3#406]
how configure csslint for show only errors

**Comment by groteworld** [comment]
Check out http://www.sublimelinter.com/en/latest/navigating.html#making-warnings-passive

This won't hide warnings, but it will make them not show up in the command palette.

**Comment by ildarkhasanshin** [comment]
it's a pity

**Comment by jawshooah** [comment]
You could also just disable warnings in your `.csslintrc` if you don't care about them.

**Comment by ildarkhasanshin** [comment]
example?
create .csslintrc in home-directory?

**Comment by jawshooah** [comment]
Sure, you could put global settings in `~/.csslintrc`. That said, we are not csslint. You should [check them out](https://github.com/csslint/csslint) for more info on configuring their tool.

**Comment by groteworld** [comment]
Question seems answered. Thanks for using SublimeLinter!!
