### ISSUE TITLE
New linter: SublimeLinter-contrib-hadolint

### ISSUE THREAD

**Issue by niksite** [SublimeLinter/SublimeLinter3#414]
https://github.com/niksite/SublimeLinter-contrib-hadolint

This linter provides an interface to the `hadolint` linter for Dockerfile.

**Comment by groteworld** [comment]
Make a release and I'll get it into Package Control. Thanks!

**Comment by niksite** [comment]
tag 1.0.0 has been added

**Comment by groteworld** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/01a7ea51bfaba316e3928254ab9d69436d1bb123 Thanks again! should show up in PC within an hour.
