### ISSUE TITLE
New Linter: textlint

### ISSUE THREAD

**Issue by joeybaker** [SublimeLinter/SublimeLinter3#417]
https://github.com/joeybaker/SublimeLinter-textlint

Uses [textlinter](https://github.com/textlint/textlint) on markdown and text files.

**Comment by groteworld** [comment]
Please tag a new release and I'll get it into Package Control. Thanks!

**Comment by groteworld** [comment]
Sorry I missed this, please fix your jenkins badge as well.

**Comment by joeybaker** [comment]
Will do!

**Comment by joeybaker** [comment]
Should be all set now. Sorry about that.

**Comment by groteworld** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/c0c071fe96437ec67b1f437186034f1d25459b64 Thanks again! Should show up within the hour.

**Comment by joeybaker** [comment]
Thanks!
