### ISSUE TITLE
lint_mode load/save very slow with ST3 Go to Anywhere feature

### ISSUE THREAD

**Issue by bf** [SublimeLinter/SublimeLinter3#420]
I have the feeling that when using SublimeLinter with the `lint_mode: "load/save"` setting, the "Go to Anywhere" feature in SublimeText becomes awfully slow.

To open the "Go to Anywhere" dialog I press key combination `CTRL + P`, and a text input appears. Now, for each key I type into this input field, SublimeText will load the appropriate file in my directory on the fly and display it.

After installing SublimeLinter I have found out that the workflow described above is slowed down immensely, from near-instant response time to 5+ seconds of loading until the file I search for appears.

Somehow I suspect SublimeLinter to launch linting for each of these files that are offered to me by the SublimeText "Go to Anywhere" feature. If you SublimeLinter uses a simple logic / hook then that is the most straightforward explanation.

Could you add a feature to either detect that file is displayed from within the "Go to Anywhere" feature and disable linting, or add a SublimeLinter setting to delay linting until a file has been opened for at least X seconds?

**Comment by braver** [comment]
We recently changed a bunch of events to be asynchronous and that might help with issues like this. Could you try the latest release and check if you're still experiencing this issue?

**Comment by braver** [comment]
🤷‍♂️ We'll re-open if there's news.
