### ISSUE TITLE
new linter plugin:au3check

### ISSUE THREAD

**Issue by smsrkr** [SublimeLinter/SublimeLinter3#422]
[Repo](https://github.com/smsrkr/SublimeLinter-contrib-au3check)
Linter for AutoIt3 scripts using the official syntax checker au3check.

**Comment by groteworld** [comment]
Sorry for the wait, please make a release and I'll put it in Package Control.

**Comment by smsrkr** [comment]
[release 1.0.0](https://github.com/smsrkr/SublimeLinter-contrib-au3check/releases/tag/1.0.0)
Thank you!

**Comment by groteworld** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/86190f464151bdef5d8cd64f1a3b527a130c3eae Thanks!
