### ISSUE TITLE
Missing error code in Status bar info

### ISSUE THREAD

**Issue by jakobdo** [SublimeLinter/SublimeLinter3#423]
Hello,
when i run sublimelinter, i get a list of errors.
When marking an error, i get the status like:
Wrong hanging indentation (add X spaces), Line Y, Column X

Im missing the error / pynlinter / pep8 code like: W0311. (can be found in console, if run with debug)
Why is this code not printed in status info bar?

**Comment by smsrkr** [comment]
this should be reported to the respective _linter-plugin_'s project.

**Comment by jakobdo** [comment]
Will do, thanks.
