### ISSUE TITLE
Sublime freezes when opening Settings - User

### ISSUE THREAD

**Issue by prufrock123** [SublimeLinter/SublimeLinter3#424]
Hello,

Running Sublime Text 3 on Yosemite.

When I try to open SublimeLinter's Settings-User for setting my preferences, Sublime Text will freeze and become unresponsive, requiring a force quit.

I have tried uninstalling SublimeLinter and re-installing, but the problem persists.

Thank-you.

**Comment by andrewfree** [comment]
My whole UI is freezing when trying to load the the linter currently.

**Comment by prufrock123** [comment]
This problem is still occurring. Anyone else experience this?
