### ISSUE TITLE
New linter: SublimeLinter-contrib-swiftlint

### ISSUE THREAD

**Issue by mailiam** [SublimeLinter/SublimeLinter3#425]
Linter plugin for Swift using [realm/SwiftLint
](https://github.com/realm/SwiftLint)
[mailiam/SublimeLinter-contrib-swiftlint](https://github.com/mailiam/SublimeLinter-contrib-swiftlint)

**Comment by groteworld** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/21a7ac39f9cc9c7990ce861baa2a7803b25b4bb6

Thank you so much!!
