### ISSUE TITLE
sublime text 3, SublimeLinter jslint not working

### ISSUE THREAD

**Issue by michaelserna** [SublimeLinter/SublimeLinter3#426]
startup, version: 3103 osx x64 channel: stable
executable: /Volumes/Sublime Text/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/michaelserna/Library/Application Support/Sublime Text 3/Packages
state path: /Users/michaelserna/Library/Application Support/Sublime Text 3/Local
zip path: /Volumes/Sublime Text/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/michaelserna/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.255408
using gpu buffer for window
startup time: 0.315191
first paint time: 0.352187
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.profile_syntax_definition
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Python.syntax_test_python
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin All Autocomplete.all_views_completions
reloading plugin AngularJS.AngularJS-sublime-package
reloading plugin AngularJS.jscompletions
reloading plugin AngularJS.message
reloading plugin AngularJS.sublime_commands
reloading plugin AngularJS.viewlocation
reloading plugin AppendSemiColon.AppendSemiColon
reloading plugin Emmet.emmet-plugin
reloading plugin GitGutter.git_gutter
reloading plugin GitGutter.git_gutter_change
reloading plugin GitGutter.git_gutter_compare
reloading plugin GitGutter.git_gutter_events
reloading plugin GitGutter.git_gutter_handler
reloading plugin GitGutter.git_helper
reloading plugin GitGutter.view_collection
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeLinter-jshint.linter
SublimeLinter: jshint linter loaded 
reloading plugin Trimmer.Trimmer
reloading plugin CSScomb.CSScomb
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: off 
SublimeLinter: jshint activated: /usr/local/bin/jshint (disabled in settings) 
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2016-03-03 19:26:13, next run at 2016-03-03 20:26:13 or after
reloading Packages/User/SublimeLinter.sublime-settings
reloading Packages/User/SublimeLinter.sublime-settings
reloading Packages/User/SublimeLinter.sublime-settings
reloading Packages/User/SublimeLinter.sublime-settings

**Comment by groteworld** [comment]
> SublimeLinter: jshint activated: /usr/local/bin/jshint (disabled in settings)

you seem to have it disabled somewhere in your settings. This could be either in your SublimeLinter User settings, project settings (if applicable), or .sublimelinterrc settings file (if applicable)

**Comment by tborychowski** [comment]
I have the same issue in ST v3114. 
Command line eslint works perfectly but not in SublimeLinter.
I enabled debug mode for it but see no errors, nor any other info.
It just doesn't work.
When triggered from menu it shows "No linter errors." message.

**Comment by dongruiyang** [comment]
my sublimelinter doesn't  work!!! 
ST v3114 version

**Comment by slhck** [comment]
For me, I had transferred my user packages from another machine, and it didn't work anymore, not outputting anything. Completely reinstalling SublimeLinter and SublimeLinter-pylint as well as clearing my SublimeLinter user settings (just removing all its contents), then restarting Sublime solved the problem.
