### ISSUE TITLE
New linter: SublimeLinter-contrib-bemlint

### ISSUE THREAD

**Issue by DesTincT** [SublimeLinter/SublimeLinter3#427]
Linter plugin for html files using [bemlint](https://github.com/DesTincT/bemlint)

https://github.com/DesTincT/SublimeLinter-contrib-bemlint

**Comment by groteworld** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/51a516575de151d3cb508b016fd405b35a417f21

Thank you so much!!
