### ISSUE TITLE
Linter Autodetection

### ISSUE THREAD

**Issue by seansean11** [SublimeLinter/SublimeLinter3#429]
I have the SublimeLinter-jshint and SublimeLinter-contrib-eslint both installed in Sublime Text.  When running a project that only has eslint installed locally and an .eslintrc file (nothing for jshint), the jshint plugin starts showing unwanted errors/warnings.  After reading the docs, it looks like I can use Sublime's "project settings" to ignore the jshint plugin on a per-project basis. 

Is there a way to automate this?  I would like to avoid adding more settings and files to my project.  My original intuition was that only the SublimeLinter-contrib-eslint package would provide linting, since there is nothing related to jshint in this project.

**Comment by ajmichels** [comment]
Currently the only way to do what you are asking is to specify the `"@disable": true` [meta setting](http://sublimelinter.readthedocs.org/en/latest/meta_settings.html#disable) for the linter you want to disable for the [project](http://sublimelinter.readthedocs.org/en/latest/settings.html#project-settings). 

Are you saying you don't want to add a `.sublime-project` file to your project? You don't need to have it in your project directory, sublime can open project file outside of your project directory you just have to define your project paths as absolute paths. Even if you did you should be putting something like `*.sublime-*` in your .gitignore file.

**Comment by seansean11** [comment]
Thanks for the explanation, and yes, it's not a hassle to have to disable specific plugins in the sublime-project file.  If it were easy to build, auto-detection of linter-specific files would be a nice-to-have feature.

**Comment by ajmichels** [comment]
Hmm. I get what you are saying, but many if not most linters don't require any kind of configuration. As long as they can be run their defaults often do good enough job. How would we detect that someone just wants to use the default settings versus not at all. I the answer would be some sort of configuration... Which kind of leads us back to where we are. Any suggestions?
