### ISSUE TITLE
Provide a way for syntaxes to tell SublimeLinter their "underlying syntax" by themselves

### ISSUE THREAD

**Issue by FichteFoll** [SublimeLinter/SublimeLinter3#431]
Currently, users have to explicitly add entries to their global `syntax_map` setting in order to receive linting using a general linter for a certain language flavor (or just a custom syntax).

I suggest to allow package (or syntax def) authors to tell SublimeLinter which linter SL should chose using a syntax-specific setting that SL will inspect if there is no global `syntax_map` override, which would take precedence.
#### Example

I have a syntax named `Sublime Text Syntax Def (YAML)`, which highlights YAML files in a specific way. In a file named `Sublime Text Syntax Def (YAML).sublime-settings` (in the same package) I would then put this:

``` json
{
    "sublimelinter.syntax": "yaml"
}
```

or similar, so that all users installing this syntax and `SublimeLinter-pyyaml` automatically have linting enabled.
The setting would be accessible via `view.settings().get("sublimelinter.syntax")`. The dot is used in order to separate a plugin's settings from core settings and a not yet established standard.

**Comment by viluon** [comment]
+1, we need this!

**Comment by braver** [comment]
I like the idea at #691 a lot actually
