### ISSUE TITLE
New linter: SublimeLinter-contrib-htmllint

### ISSUE THREAD

**Issue by necramirez** [SublimeLinter/SublimeLinter3#432]
Linter plugin for html files using [htmllint](https://github.com/htmllint/htmllint)

https://github.com/necramirez/SublimeLinter-contrib-htmllint

**Comment by groteworld** [comment]
Please make a release and I'll get this in Package Control. Thanks!

**Comment by necramirez** [comment]
https://github.com/necramirez/SublimeLinter-contrib-htmllint/releases/tag/1.0.0

**Comment by groteworld** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/884dcf054ac3c72264465041cf2c9e49e8d8675b

Thanks!
