### ISSUE TITLE
ruby: No such file or directory -- ruby-lint (LoadError) 

### ISSUE THREAD

**Issue by LeEnno** [SublimeLinter/SublimeLinter3#434]
Hey there, I can't get my head around getting ruby-lint to work, using SublimeLinter-contrib-ruby-lint Package.

My settings:

```javascript
{
    "user": {
        "debug": true,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {
            "rubylint": {
                "@disable": false,
                "args": [],
                "excludes": []
            }
        },
        "mark_style": "outline",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": false,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "javascript (babel)": "javascript",
            "magicpython": "python",
            "php": "html",
            "python django": "python",
            "pythonimproved": "python"
        },
        "warning_color": "DDB700",
        "wrap_find": true
    }
}
```

Console log on startup with `album.rb` file open:

```
startup, version: 3103 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/Enno/Library/Application Support/Sublime Text 3/Packages
state path: /Users/Enno/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/Enno/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["RuboCop", "Vintage"]
pre session restore time: 0.281268
using gpu buffer for window
first paint time: 0.347509
startup time: 0.375412
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.profile_syntax_definition
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Python.syntax_test_python
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin AdvancedNewFile.AdvancedNewFile
reloading plugin Alignment.Alignment
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin ChangeQuotes.change_quotes
reloading plugin DocBlockr.jsdocs
reloading plugin Emmet.emmet-plugin
reloading plugin ExpandRegion.__init__
reloading plugin ExpandRegion.expand_region_handler
reloading plugin ExpandRegion.expand_to_indent
reloading plugin ExpandRegion.expand_to_line
reloading plugin ExpandRegion.expand_to_quotes
reloading plugin ExpandRegion.expand_to_regex_set
reloading plugin ExpandRegion.expand_to_semantic_unit
reloading plugin ExpandRegion.expand_to_subword
reloading plugin ExpandRegion.expand_to_symbols
reloading plugin ExpandRegion.expand_to_word
reloading plugin ExpandRegion.expand_to_word_with_dots
reloading plugin ExpandRegion.expand_to_xml_node
reloading plugin ExpandRegion.ExpandRegion
reloading plugin ExpandRegion.html
reloading plugin ExpandRegion.javascript
reloading plugin ExpandRegion.latex
reloading plugin ExpandRegion.python
reloading plugin ExpandRegion.utils
reloading plugin Git.git_commands
reloading plugin Open Search Result.open_search_result
reloading plugin Open Search Result.util
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SCSS.scss_completions
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeLinter-contrib-ruby-lint.linter
SublimeLinter: rubylint linter loaded 
reloading plugin VAlign.valign
reloading plugin Wrap Plus.wrap_plus
reloading plugin Highlight.SublimeHighlight
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: /var/folders/l2/j37t2cjs5ssgcgsrk1xyt1x40000gn/T/SublimeLinter3-Enno 
SublimeLinter: user shell: /bin/bash 
SublimeLinter: computed PATH using /bin/bash:
/Users/Enno/.rvm/gems/ruby-2.2.1/bin
/Users/Enno/.rvm/gems/ruby-2.2.1@global/bin
/Users/Enno/.rvm/rubies/ruby-2.2.1/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Users/Enno/.rvm/bin
 
SublimeLinter: ENV['GEM_HOME'] = '/Users/Enno/.rvm/gems/ruby-2.2.1' 
SublimeLinter: rubylint version query: /Users/Enno/.rvm/bin/rvm-auto-ruby -S ruby-lint --version 
SublimeLinter: rubylint version: 2.2.1 
SublimeLinter: rubylint: (>= 2.0.0) satisfied by 2.2.1 
SublimeLinter: rubylint activated: ['/Users/Enno/.rvm/bin/rvm-auto-ruby'] 
Emmet: No need to update PyV8
SublimeLinter: chdir not set or invalid, using /Users/Enno/Sites/pictrs/master/pictrs/app/models 
SublimeLinter: rubylint: album.rb ['/Users/Enno/.rvm/bin/rvm-auto-ruby', '-S', 'ruby-lint'] 
SublimeLinter: rubylint output:
ruby: No such file or directory -- ruby-lint (LoadError) 
Package Control: Skipping automatic upgrade, last run at 2016-03-17 18:11:45, next run at 2016-03-17 19:11:45 or after
```

From what I can tell, it's not about the path or executable not being found (since it's satisfied with the version). From what I read on other issues it's also not caused by the `chdir` stuff, because this is just a message stating that the setting is not set.

Any ideas on why sublime can find out the correct version but can't actually run `ruby-lint` on a file?

**Comment by LeEnno** [comment]
One addition I should add: `/Users/Enno/.rvm/bin/rvm-auto-ruby -S ruby-lint --version` gives the following output:

```
warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.4-compliant syntax, but you are running 2.2.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
ruby-lint v2.1.0 on ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
```

1. What's that stuff about the parser? Should I take action?
2. `ruby-lint` is actually v2.1.0, but SublimeLinter thinks it's 2.2.1 (probably some regex stuff).

**Comment by groteworld** [comment]
This is a problem with https://github.com/jawshooah/SublimeLinter-contrib-ruby-lint and should be reported there. It seems to be running fine, but errors out because it can't find the `album.rb` file. The line below is the actual executables error.

```bash
ruby: No such file or directory -- ruby-lint (LoadError) 
```

Hope this helps.

**Comment by LeEnno** [comment]
Reported an issue there, thank you!

**Comment by LeEnno** [comment]
Sorry to reopen again, but the same behavior occurs with other linters, so there's probably something wrong with the paths in SublimeLinter.

My situation:

- I have 3 SublimeLinter linters installed: `ruby-lint`, `haml-lint` and `eslint`.
- My project root is: `/Users/Enno/Sites/pictrs/master/pictrs`.
- I use rvm and my default gem root is `/Users/Enno/.rvm/gems/ruby-2.2.4`.
- Gems are installed in the `@global` gemset (SublimeLinter seems to not like the `default` gemset).

Below there are some logs. The weird thing is that the errors are a little different depending on the way files are opened. When I open Sublime with a to-be-linted file, the `LoadError` occurs when Sublime tries to lint. When Sublime is already open and I change to a to-be-linted file, the LoadError occurs earlier (when Sublime tries to find the linter version). See the logs for clarification.

# Setup log (SublimeLinter stuff only):

```
SublimeLinter: hamllint linter loaded 
SublimeLinter: rubylint linter loaded 
SublimeLinter: eslint linter loaded 
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: /var/folders/l2/j37t2cjs5ssgcgsrk1xyt1x40000gn/T/SublimeLinter3-Enno 
SublimeLinter: user shell: /bin/bash 
SublimeLinter: computed PATH using /bin/bash:
/Users/Enno/.rvm/gems/ruby-2.2.4/bin
/Users/Enno/.rvm/gems/ruby-2.2.4@global/bin
/Users/Enno/.rvm/rubies/ruby-2.2.4/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Users/Enno/.rvm/bin
```

# ruby-lint

The to-be-linted file is `/Users/Enno/Sites/pictrs/master/pictrs/app/models/album.rb`.

## On Startup:

```
SublimeLinter: ENV['GEM_HOME'] = '/Users/Enno/.rvm/gems/ruby-2.2.4' 
SublimeLinter: rubylint version query: /Users/Enno/.rvm/bin/rvm-auto-ruby -S ruby-lint --version 
SublimeLinter: rubylint version: 2.1.0 
SublimeLinter: rubylint: (>= 2.0.0) satisfied by 2.1.0 
SublimeLinter: rubylint activated: ['/Users/Enno/.rvm/bin/rvm-auto-ruby'] 
SublimeLinter: rubylint: album.rb ['/Users/Enno/.rvm/bin/rvm-auto-ruby', '-S', 'ruby-lint'] 
SublimeLinter: rubylint output:
ruby: No such file or directory -- ruby-lint (LoadError)
```

## When changing to `album.rb` file:

```
SublimeLinter: ENV['GEM_HOME'] = '/Users/Enno/.rvm/gems/ruby-2.2.4' 
SublimeLinter: rubylint version query: /Users/Enno/.rvm/bin/rvm-auto-ruby -S ruby-lint --version 
SublimeLinter: WARNING: no rubylint version could be extracted from:
ruby: No such file or directory -- ruby-lint (LoadError)
```

# haml-lint

The to-be-linted file is `/Users/Enno/Sites/pictrs/master/pictrs/app/views/adminbill/plausi.html.haml`.

## On Startup:

```
SublimeLinter: ENV['GEM_HOME'] = '/Users/Enno/.rvm/gems/ruby-2.2.4' 
SublimeLinter: hamllint version query: /Users/Enno/.rvm/bin/rvm-auto-ruby -S haml-lint --version 
SublimeLinter: hamllint version: 0.13.0 
SublimeLinter: hamllint: (>= 0.6.0) satisfied by 0.13.0 
SublimeLinter: hamllint activated: ['/Users/Enno/.rvm/bin/rvm-auto-ruby'] 
/Users/Enno/Sites/pictrs/master/pictrs/config/rubocop.yml
SublimeLinter: chdir has been set to: /Users/Enno/Sites/pictrs/master/pictrs 
SublimeLinter: hamllint: plausi.html.haml ['/Users/Enno/.rvm/bin/rvm-auto-ruby', '-S', 'haml-lint'] 
SublimeLinter: hamllint output:
ruby: No such file or directory -- haml-lint (LoadError) 
```

## When changing to `plausi.html.haml` file:

```
SublimeLinter: hamllint version query: /Users/Enno/.rvm/bin/rvm-auto-ruby -S haml-lint --version 
SublimeLinter: WARNING: no hamllint version could be extracted from:
ruby: No such file or directory -- haml-lint (LoadError)
```

# Notes

1. `eslint` (https://github.com/roadhump/SublimeLinter-eslint) works just fine, because the executables are installed via `npm` locally.
2. `rubocop` (https://github.com/pderichs/sublime_rubocop) works fine as well. Of course, it's not based on the SublimeLinter framework, but the executables are located in the same directory as `haml-lint` and `ruby-lint`.

Calling the linters with from the terminal works totally fine.  
Any ideas what I am doing wrong?

**Comment by LeEnno** [comment]
Here we are with a little more information: I use different ruby versions for my home folder (where the shell probably opens first) and my project folder. This means:

- When querying the linter version on startup, SublimeLinter does this "in the context" of the home folder.
- When running the linter, SublimeLinter does this "in the context" of the project folder.

Both actions speak to different folders which in my case results in different ruby versions with different gemsets. That's why SublimeLinter is totally fine with the linter's version (fetched from the home folder) but can't execute the linter inside the project folder, since the linter's not installed in there.

I can fix this by adding the gem executables folder of my project folder to the `paths` setting. But this means that everytime my project changes the ruby version, I will have to remember adjusting this path.

Is there a possibility to make SublimeLinter augment the path from the project folder instead of the home folder?

**Comment by groteworld** [comment]
Ah, after reading that last comment that explains it your issue. These executables aren't technically in your path. You could add these path settings to a  `.sublime-project` or `.sublimelinterrc` file in the project. That way it's dynamic to the project.

Some documentation on these setting file types are http://www.sublimelinter.com/en/latest/settings.html#project-settings and http://www.sublimelinter.com/en/latest/settings.html#sublimelinterrc-settings

Hope this helps.

**Comment by LeEnno** [comment]
Thanks for your help.

I already tried setting the path via `.sublimelinterrc`, but this has no effect. As the documentation states:

> Only meta-settings and linter settings are recognized in `.sublimelinterrc` files.

I could try using the `.sublime-project` file, but I'd still have to remember updating this setting every time I update the ruby version in my project.

I still think it would be great if SublimeLinter could execute the version query in the context of the project folder (sorry if I'm using wrong terminology here), since this would resolve the "missing executable" error without any workarounds. But I can also understand that this might be an edge case.

Right now the solution is either:

- setting the path in a  `.sublime-project` file or
- `gem install`ing the executables in the home folder **as well as** in the project folder.

**Comment by LeEnno** [comment]
Just a quick follow up: project settings aren't an option, since the same restrictions apply as the ones for `.sublimelinterrc`. Only meta- and linter-settings. So right now the only solution is to install executables in the home folder as well as in the project folder.

Since this issue is getting crowded with unnecessary info, I summarized the main problem in https://github.com/SublimeLinter/SublimeLinter3/issues/446 and will close this one.
