### ISSUE TITLE
SublimeLinter-csslint not working yet eslint and jshint do

### ISSUE THREAD

**Issue by seanbischoff** [SublimeLinter/SublimeLinter3#435]
Only posting here after going through docs and online guides.

Running ST3 on WIndows 64bit
I ran "npm install -g csslint"
I installed thru pkg manager
I restarted
I added path "C:\Users\[myName]\AppData\Roaming\npm" in the package user preferences. Also extended it into node_modules. No luck. Currently I have none listed here.
I can open a terminal in my css folder, and manually run csslint with results, so I know csslint works
In ST3 console I see that the plugin loaded:

> reloading plugin SublimeLinter-csslint.linter
SublimeLinter: csslint linter loaded 

As did eslint linter and jshint

But when I remove a ":" or "{" or otherwise make CSS invalid in CSS, nothing at all happens.

Full ST3 console output

------------------------
DPI scale: 1
startup, version: 3103 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/sbischoff/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/sbischoff/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/sbischoff/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.138697
startup time: 0.173697
first paint time: 0.174697
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.profile_syntax_definition
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Python.syntax_test_python
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin Bracketeer.bracketeer
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin Can I Use.useIt
reloading plugin Color Highlighter.ColorHighlighter
reloading plugin Color Highlighter.colors
reloading plugin ColorSchemeSelector.ColorSchemeSelector
reloading plugin CSS Format.css_format
reloading plugin DocBlockr.jsdocs
reloading plugin EasyElement.EasyElement
reloading plugin Emmet.emmet-plugin
reloading plugin FileDiffs.file_diffs
reloading plugin HTMLBeautify.HTMLBeautify
reloading plugin LESS.less_completions
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageResourceViewer.package_resource_viewer
reloading plugin PackageResourceViewer.package_resources
reloading plugin SCSS.scss_completions
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeLinter-csslint.linter
SublimeLinter: csslint linter loaded 
reloading plugin SublimeLinter-html-tidy.linter
SublimeLinter: htmltidy linter loaded 
reloading plugin SublimeLinter-jshint.linter
SublimeLinter: jshint linter loaded 
reloading plugin Trimmer.Trimmer
reloading plugin ColorPicker.sublimecp
reloading plugin SCSS.tmbundle-SublimeText2.scss_completions
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1512, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1529, in _find_and_load_unlocked
ImportError: No module named 'SCSS.tmbundle-SublimeText2'
reloading plugin SublimeCodeIntel.ordereddict
reloading plugin SublimeCodeIntel.SublimeCodeIntel
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin SublimeLinter-contrib-eslint.linter
SublimeLinter: eslint linter loaded 
plugins loaded
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: c:\users\sbisch~1\appdata\local\temp\SublimeLinter3-sbischoff 
SublimeLinter: jshint version query: C:\Users\sbischoff\AppData\Roaming\npm\jshint.cmd --version 
SublimeLinter: jshint version: 2.9.1 
SublimeLinter: jshint: (>= 2.5.0) satisfied by 2.9.1 
SublimeLinter: jshint activated: C:\Users\sbischoff\AppData\Roaming\npm\jshint.cmd 
Emmet: No need to update PyV8
SublimeLinter: eslint: main.js ['C:\\Users\\sbischoff\\AppData\\Roaming\\npm\\eslint.cmd', '--format', 'compact', '--stdin', '--stdin-filename', '__RELATIVE_TO_FOLDER__'] 
SublimeLinter: jshint: main.js ['C:\\Users\\sbischoff\\AppData\\Roaming\\npm\\jshint.cmd', '--verbose', '--filename', '@', '-'] 
Package Control: Skipping automatic upgrade, last run at 2016-03-17 15:53:14, next run at 2016-03-17 16:53:14 or after

-------------------------------------

**Comment by groteworld** [comment]
In your full output you are showing the JS linters properly working. Could you show the not working csslint output? additionally, what happens when you run the csslint executable on the file from the command prompt. Sorry you're having issues.

**Comment by seanbischoff** [comment]
No worries, thanks for the quick followup!

Screenshot of ST3 w/CSS errors: 
https://www.dropbox.com/s/vdkeh4h2aq4b5o4/csslint-not-active.png?raw=1

Screenshot of command line use of csslint:
https://www.dropbox.com/s/srsdt9mbxshagvj/csslint-command-line.png?raw=1

I'm sure I missed a setting somehow. Unless it's theme/color scheme related? Anyhow any help is greatly appreciated. :).

**Comment by groteworld** [comment]
Ah! It is syntax related. It's currently set to LESS syntax highlighting which technically is not css. if you want to keep LESS highlighting. Go into your SL user settings and under the `syntax_map` setting add `"less": "css"`

More information on the syntax map setting can be found here: http://www.sublimelinter.com/en/latest/global_settings.html#syntax-map

**Comment by seanbischoff** [comment]
Shazaam! That was it.  I did try "css":"css" before, neg results. Being set to LESS makes sense.

I'm using SCSS. Adding `"scss":"css"` enables those as well.

Thank you sooo much for the help!

**Comment by jawshooah** [comment]
@seanbischoff Since you're using SCSS, I'd suggest [scss-lint](https://github.com/brigade/scss-lint) and the corresponding [SublimeLinter plugin](https://github.com/attenzione/SublimeLinter-scss-lint).
