### ISSUE TITLE
linters stopped working in sublime but work from the command line, no warnings in console

### ISSUE THREAD

**Issue by nicolehe** [SublimeLinter/SublimeLinter3#438]
Hi,

My linters worked in the past but stopped working recently (probably after I did something that I don't remember). I tested jshint from the command line and it worked. 

startup, version: 3103 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/nicolehe/Library/Application Support/Sublime Text 3/Packages
state path: /Users/nicolehe/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/nicolehe/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: []
pre session restore time: 0.373287
first paint time: 0.432997
startup time: 0.463684
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.profile_syntax_definition
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Python.syntax_test_python
reloading plugin Vintage.vintage
reloading plugin Vintage.vintage_commands
reloading plugin Vintage.vintage_motions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 1Self.1self
reloading plugin 1Self.1selfOpenDashboardCommand
reloading plugin Colorsublime.colorsublime-plugin
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SublimeLinter-jshint.linter
SublimeLinter: jshint linter loaded 
reloading plugin Arduino-like IDE.StinoStarter
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin OmniSharp.OmniSharpSublime
generating syntax summary
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin SublimeLinter-contrib-eslint.linter
SublimeLinter: eslint linter loaded 
plugins loaded
omnisharp plugin_loaded
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: /var/folders/hs/lm4vl0g16tl7xjlxq6kq2zf80000gn/T/SublimeLinter3-nicolehe 
Initializing 1self plugin
reloading Packages/User/SublimeLinter.sublime-settings
Package Control: Skipping automatic upgrade, last run at 2016-03-28 15:18:43, next run at 2016-03-28 16:18:43 or after
reloading Packages/User/SublimeLinter.sublime-settings

**Comment by nicolehe** [comment]
Update: It works for some files but not others. It will lint my .html file with Javascript, but won't lint my .js file.

**Comment by groteworld** [comment]
Is that console output while the javascript file has been loaded and saved? It doesn't show any activity from the linter so that typically means the linter doesn't believe it's supposed to run on that file. So also check to make sure the js file has a JavaScript syntax highlighting

**Comment by nicolehe** [comment]
Yeah, that's the output from the .js file. How do I check if the file has Javascript syntax highlighting?

**Comment by groteworld** [comment]
In the bottom right-hand corner it should say JavaScript and if you click it, it should be coming from the JavaScript dropdown.

**Comment by nicolehe** [comment]
Ahhh that did it! I had it sent to Unity JavaScript, oops. Thank you!!!

**Comment by groteworld** [comment]
Awesome! yeah I think that is one of the more confusing pieces of the system. It is syntax dependant, so that it doesn't try to run python linters on your js code, but that also blocks any syntax that it doesn't know. Here's a doc about setting a custom syntax map if you prefer the Unity JS syntax http://www.sublimelinter.com/en/latest/global_settings.html#syntax-map

Glad we could solve this! :beers:
