### ISSUE TITLE
Code to get python path returns empty string in sublime console

### ISSUE THREAD

**Issue by jasjuang** [SublimeLinter/SublimeLinter3#440]
I am trying to get contrib-cmakelint work on Windows 10. Code such as 
````
os.path.dirname(sys.executable)
sys.exec_prefix
````
to get python path works perfectly on a python console but returns empty string in sublime.

To be more specific the below code does not work
````
cmd = ('python', os.path.dirname(sys.executable)+'\Scripts\cmakelint', '*', '@')
cmd = ('python', sys.exec_prefix+'\Scripts\cmakelint', '*', '@')
````
and I had to hard code it to 
````
cmd = ('python', 'C:\Python27\Scripts\cmakelint', '*', '@')
````
in order to make it work. Can someone give me suggestions?

**Comment by FichteFoll** [comment]
If cmakelint is implemented in Python, you should probably be using the [`PythonLinter`](http://www.sublimelinter.com/en/latest/python_linter.html) linter class. It will find the appropriate Python installation for you.

**Comment by jasjuang** [comment]
Thanks for letting me know!
