### ISSUE TITLE
New Linter: SublimeLinter-contrib-sublime-syntax

### ISSUE THREAD

**Issue by FichteFoll** [SublimeLinter/SublimeLinter3#441]
https://github.com/FichteFoll/SublimeLinter-contrib-sublime-syntax

Please make sure to restrict installation to ST builds 3092 and higher. I don't know which build syntax testing was implemented in exactly, but I believe that this should suffice.

Also, since I didn't have an executable to work with in order to name the plugin, please also review the linter name. I could also change that to "sublime-syntax-test", if you wish.

-

Due to the special requirements for linting syntax test files, I ended up having to apply the linter to all syntaxes and check for the view's eligibility in the `run` method. Please let me know if there is a better way for this, but I went through the source code and this seemed to be the "best way" at the time since most other methods are classmethods which don't have the view-specific information available (e.g. `can_lint_syntax`).

Finally, I didn't find any documentation on some of the [attributes that `lint.Linter` provides](http://www.sublimelinter.com/en/latest/linter_attributes.html) for most of its methods, most notably `self.filename` and `self.view` (although I ended up not needing that) – and also `self.name`, which is a class attribute. I only found out about those by inspecting the source code directly.

**Comment by FichteFoll** [comment]
*subtle push*

**Comment by groteworld** [comment]
Thanks for the reminder, and the amazing work you do for ST! https://github.com/SublimeLinter/package_control_channel/commit/838a78bf5ebaf52d0ac84536fdf64ce611fdedb4
