### ISSUE TITLE
New linter: SublimeLinter-contrib-lslint

### ISSUE THREAD

**Issue by XenHat** [SublimeLinter/SublimeLinter3#447]
I made a linter to complement the `sublime-text-lsl` plugin.

https://github.com/XenHat/SublimeLinter-contrib-lslint

This linter provides an interface to the lslint linter for the Linden Scripting Language (and its OSSL variant)

**Comment by groteworld** [comment]
Please make a release and I'll put it in Package Control. Thanks!

**Comment by XenHat** [comment]
I have created a release.
_Sorry for the late reply, notifications weren't configured properly._

**Comment by groteworld** [comment]
https://packagecontrol.io/packages/SublimeLinter-contrib-lslint

Thanks again.

**Comment by XenHat** [comment]
Thank you! :)
