### ISSUE TITLE
New linter plugin: SublimeLinter-contrib-lessc

### ISSUE THREAD

**Issue by MarkGriffiths** [SublimeLinter/SublimeLinter3#448]
After finding there was no SublimeLinter plugin for less, I put this together and have been using it myself for a fair while without issue. Figured it was about time I published it.

It's just a simple bridge to `lessc --no-color --lint`, but nicely picks up problems in function use and maths.

https://github.com/MarkGriffiths/SublimeLinter-contrib-lessc

**Comment by groteworld** [comment]
Please make a new release and I'll add it to Package Control. Thanks!

**Comment by MarkGriffiths** [comment]
v1.0.0 pushed to master, thanks

**Comment by groteworld** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/0d95d01dec08c26ecb2b1da5ae341d7b35050b50

Should show up within an hour in Package Control. Thanks Again!
