### ISSUE TITLE
Trying to run one linter silently kills all linters

### ISSUE THREAD

**Issue by praxiq** [SublimeLinter/SublimeLinter3#451]
I'm trying to create my own linter to check [ledger](http://ledger-cli.org/) files. I've created it, and it looks ok. But here's what happens:
1. I run Sublime and open a python file. I confirm that a known-good linter, the flake8 linter, is working normally. It logs a few lines to the console as it lints the file.
   
   ```
   SublimeLinter: flake8: linter.py <builtin> 
   SublimeLinter: flake8 options: {'jobs': '1', 'reporter': <class 'SublimeLinter-flake8.linter.Flake8.get_report.<locals>.Report'>, 'max_line_length': 120, 'max_complexity': 10, 'ignore': ['E302', 'W291', 'W293']} 
   SublimeLinter: flake8 output:
   linter.py:36:30: E262 inline comment should start with '# ' 
   ```
2. I switch to a tab with a ledger file open. SublimeLinter logs a few lines to the debug console confirming that it has successfully activated my linter. No errors or warnings are logged to the console.
   
   ```
   SublimeLinter: ledger version query: /usr/local/bin/ledger --version 
   SublimeLinter: ledger version: 3.1.1 
   SublimeLinter: ledger: (>= 3.1.1) satisfied by 3.1.1 
   SublimeLinter: ledger activated: /usr/local/bin/ledger 
   SublimeLinter: ledger: ledger.ldg ['/usr/local/bin/ledger', 'balance', '--strict', '-f', '@'] 
   ```
3. The end. My new linter does not actually work, and furthermore, the flake8 linter no longer works on python files either. No more debug messages appear from SublimeLinter at all. Simply trying to run my linter seems to silently kill SublimeLinter entirely until I restart Sublime.

It's actually not totally dead - if I edit my linter file it logs that it reloaded and activated the linter, but none of the linters will actually work (or log anything) until I restart Sublime.

**Comment by braver** [comment]
@praxiq did you ever get this to work? In general you shouldn't see the behaviour described here, but perhaps something is wrong with your linter or something else in the setup that's broken. It's a bit hard to tell from just this information.
