### ISSUE TITLE
New linter plugin: SublimeLinter-contrib-bashate

### ISSUE THREAD

**Issue by maristgeek** [SublimeLinter/SublimeLinter3#453]
After finding there was no SublimeLinter plugin for bashate, I put this together and have been using it myself, and it matches all the tests in bashate's tests directory as well. Figured it was about time I published it.

https://github.com/maristgeek/SublimeLinter-contrib-bashate

**Comment by groteworld** [comment]
In your TravisCI file you reference PEP257, this has been renamed `pydocstyle` and you should change your pip and executable to such. If you are confused see any SublimeLinter org linter's TravisCI file.

Other then that, looks good, please make a release and I'll put it into Package Control.

**Comment by maristgeek** [comment]
Fixed, v1.0.0 released. Thanks.

**Comment by groteworld** [comment]
Thanks again for your contribution! It should show up in package control in an hour.

https://github.com/SublimeLinter/package_control_channel/commit/2f8a2c75202b57b21a8671b4b9fc7d64e3fa20a7
