### ISSUE TITLE
Getting `WARNING: pylint deactivated, cannot locate 'pylint@python'` even with `path` set

### ISSUE THREAD

**Issue by rkpatel33** [SublimeLinter/SublimeLinter3#459]
I keep getting 

```
SublimeLinter: WARNING: pylint deactivated, cannot locate 'pylint@python' 
```

even thought pylint is installed and visible, and I have the `path` variable in ST3 user settings set to its location. I am using a global virtualenv which is why I am using the `path` setting to make sure ST3 can see it.

Also, this only recently stopped working for me and I have not really changed anything. I am on OSX and SublimeText3.

Console messages wrt SublimeLinter.

```
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: /var/folders/zv/k8dql3ms7zj2k7cd6wsm5z140000gn/T/SublimeLinter3-rishi 
SublimeLinter: find_python(version='3', script=None, module=None) 
SublimeLinter: find_python: requested version = {'major': 3, 'minor': None} 
SublimeLinter: find_posix_python: python3 => None 
SublimeLinter: find_posix_python: python3 => None 
SublimeLinter: find_posix_python: python => /usr/local/bin/python 
SublimeLinter: find_python: system python = /usr/local/bin/python 
SublimeLinter: find_python: available version = {'major': 2, 'minor': 7} 
SublimeLinter: find_python: <= (None, None, 2, 7) 
SublimeLinter: no python 3 available to augment sys.path 
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2016-05-23 15:26:42, next run at 2016-05-23 16:26:42 or after
SublimeLinter: find_python(version=None, script='pylint', module=None) 
SublimeLinter: find_python: default python = /usr/local/bin/python 
SublimeLinter: find_python: available version = {'major': 2, 'minor': 7} 
SublimeLinter: find_python: 'pylint' path = None 
SublimeLinter: find_python: <= (None, None, 2, 7) 
SublimeLinter: WARNING: pylint deactivated, cannot locate 'pylint@python' 
```

`which` yields the following:

```
rishi@Rishi-MBP:~|⇒  which pylint
/Users/rishi/Virtualenvs/global/bin/pylint
```

SublimtText user setting `path` variable setup:

```
    "paths":
    {
        "linux":
        [
        ],
        "osx":
        [
            "/usr/local/lib/node_modules/jshint",
            "/Users/rishi/Virtualenvs/global/bin",
            "/Users/rishi/Virtualenvs/global/lib/python2.7/site-packages"
        ],
        "windows":
        [
        ]
    },
```

**Comment by tomkins** [comment]
I've noticed this one recently as well.

@rkpatel33 - do you have SublimeLinter-pydocstyle installed? The package previously known as SublimeLinter-pep257.

A recent update to that package seems to have caused problems for me.

**Comment by rkpatel33** [comment]
No I don't have that package installed. Any way to debug in the Sublime console (I'm not very familiar with using it)?

**Comment by braver** [comment]
@rkpatel33  Pylint seems to have trouble getting started if you have more than one version of Python. See also [this](https://github.com/SublimeLinter/SublimeLinter-pylint/issues/12). Following the info in that issue I got it running by installing pylint for both Python3 and Python2 (running macOS Sierra). Perhaps that could also solve your problem?

**Comment by braver** [comment]
🤷‍♂️ We'll re-open if there's news.
