### ISSUE TITLE
Option to show the linter that reports a certain error

### ISSUE THREAD

**Issue by FichteFoll** [SublimeLinter/SublimeLinter3#460]
Especially in the Python world (which multiple linters exists for), many linters follow a similar error reporting scheme where it is hard to distinguish from within SublimeLinter's UI where the report actually came from. Currently you have to enable debug mode and check each linter's raw output in order to find which linter reports the error.

Both in the status bar report and the "show lint errors" popup there should be an indication of which linter the report came from. I'm thinking of prefixing the status bar line with `<linter>:` and suffixing the list with `(<linter>)`.

**Comment by braver** [comment]
FYI #666 includes a new popup that displays all errors on a given line and includes the linter that reported the error.
