### ISSUE TITLE
Error toggling with shortcut, but not with menu option

### ISSUE THREAD

**Issue by icetbr** [SublimeLinter/SublimeLinter3#461]
When using the "CTRL + K, t" I get an error. Sometimes I don't get it, but I can't reproduce that. I never get it through the menu.

Traceback (most recent call last):
  File "C:\tools\sublime\sublime_plugin.py", line 533, in run_
    return self.run(**args)
  File "C:\toolssublime\Data\Packages\SublimeLinter\commands.py", line 672, in run
    if self.linters[self.which]:
KeyError: 'all'

**Comment by icetbr** [comment]
Well, not used to python, hacked my way through. Changed the run method to this fixed the issue

    def run(self, **args):
        """Run the command."""
        self.which = args['which']

        if self.linters.get(self.which) is None:
            linters = []
            settings = persist.settings.get('linters', {})

            for instance in persist.linter_classes:
                linter_settings = settings.get(instance, {})
                disabled = linter_settings.get('@disable')

                if self.which == 'all':
                    include = True
                    instance = [instance, 'disabled' if disabled else 'enabled']
                else:
                    include = (
                        self.which == 'enabled' and not disabled or
                        self.which == 'disabled' and disabled
                    )

                if include:
                    linters.append(instance)

            linters.sort()
            self.linters[self.which] = linters

        if self.linters and self.linters[self.which]:
            self.window.show_quick_panel(self.linters[self.which], self.on_done)

**Comment by braver** [comment]
FYI #666 will remove the all the several menus and commands that all "sort of work". Toggling will have to be done by accessing the preferences because linters may also be toggled using other configuration files.
