### ISSUE TITLE
Configure linter-specific rules globally 

### ISSUE THREAD

**Issue by yairEO** [SublimeLinter/SublimeLinter3#462]
I've asked this [question in stackoverflow](http://stackoverflow.com/q/37367267/104380) but nobody bothered to look:

I want to configure sublimeLinter with global linting rules (ESLINT), so all my javascript files will be linted using those rules. I already have ESLINT configured and working (in my GULP file):

```
"rules": {
    "no-mixed-spaces-and-tabs" : [2, "smart-tabs"],
    "block-spacing"            : [2, "always"],
    "comma-style"              : [2, "last"],
    "no-debugger"              : [2],
    "no-alert"                 : [2],
    "indent"                   : [1, 4],
    "strict"                   : 0,
    "no-undef"                 : 1
},
"ecmaFeatures" : {
    "modules": true,
    "sourceType": "module"
},
"parserOptions": {
    "ecmaVersion" : 6,
    "sourceType": "module",
    "ecmaFeatures": {
        "jsx": false,
        "experimentalObjectRestSpread": true
    }
},
"envs": [
    "browser", "es6"
]
```

I want to know how can I configure sublimeLInter to use above settings.
### SublimeLinter.sublime-settings

```
{
    "user": {
        "debug"                 : false,
        "delay"                 : 0.25,
        "error_color"           : "D02000",
        "gutter_theme" : "Packages/SublimeLinter/gutter-themes/Default/Default-theme",
        "gutter_theme_excludes" : [],
        "lint_mode"             : "background",
        "linters"               : {
            "eslint": {
                "@disable" : false,
                "args"     : [],
                "excludes" : []
            }
        },
        "mark_style"                : "solid underline",
        "no_column_highlights_line" : false,
        "passive_warnings"          : false,
        "paths"                     : {
            "linux"   : [],
            "osx"     : [],
            "windows" : []
        },
        "python_paths": {
            "linux"   : [],
            "osx"     : [],
            "windows" : []
        },
        "rc_search_limit"       : 3,
        "shell_timeout"         : 10,
        "show_errors_on_save"   : false,
        "show_marks_in_minimap" : true,
        "syntax_map"            : {
            "html (django)" : "html",
            "html (rails)"  : "html",
            "html 5"        : "html",
            "php"           : "html",
            "python django" : "python"
        },
        "warning_color" : "DDB700",
        "wrap_find"     : true
    }
}
```

I've read sublimeLiner documentation page and can't understand how to setup simple linter rules globally (for any opened file which the linter supports)

**Comment by B4bharat** [comment]
@yairEO If you are using windows, place your '.eslintrc' file in c:/users/<your username> directory, in Linux, its '~/home/<your username>' directory.

Also specify the path where node is installed in the sublimelinter user preferences file - 
"paths" : {
  "linux"   : [<Path of your node installation>],
  "osx"     : [<Path of your node installation>],
  "windows" : [<Path of your node installation>]
}

If you are unsure of where your node is installed, you can run this command in your terminal - which node. It will tell you the path.

Let me know if it worked or not.

**Comment by B4bharat** [comment]
This guy has the detailed explanation - http://jonathancreamer.com/setup-eslint-with-es6-in-sublime-text/

**Comment by braver** [comment]
Jup, those explanations seem to cover it!
