### ISSUE TITLE
Persist lint errors on file change

### ISSUE THREAD

**Issue by ackvf** [SublimeLinter/SublimeLinter3#467]
Hello, is it possible to persist the list of errors a file has after I start fixing them? Even a simple quote change requires to lint the whole file again to see further errors.

I am aware that the line numbers might change and that it would be painful for you to fix this, so instead the menu of "Show All Errors" could say "near line xy" to hold true.

**Comment by braver** [comment]
The "Report (Open Files)" will give you a static list of errors. 

Another alternative would be to run the linter as a build system.

If that's not what you're looking for I think I need more information about what you're trying to achieve, or what your workflow looks like.

**Comment by ackvf** [comment]
Actually, I have moved to VS Code since then and I don't remember what exactly was the problem, but I think that the error highlighting and the list in `Show All Errors` would be reset with a change to the file.

Right now it seems that even if I start fixing the errors, I can still call the `Show All Errors` list to see next error and the errors are still highlighted in the file as well.

Not an issue any more.
