### ISSUE TITLE
Disable Gutter Marks

### ISSUE THREAD

**Issue by LeonardoGentile** [SublimeLinter/SublimeLinter3#469]
Hello,
I've tried to look around for a specific setting to disable the gutter marks completely but I couldn't find it.
I want to do this because apparently there is [no way](https://github.com/gornostal/Modific/issues/100) to set a priority on different plugins using the gutter.

I'm using modific plugin that also uses the gutter and both plugins conflict each other and weird things are showing up in the gutter. 

At this point the only workaround would be to chose a _mark style_ and disable the gutter theme completely. Is this possible? 

If there is another solution to set priority for conflicting plugins using the gutter would be better.

See also: 
- https://github.com/SublimeTextIssues/Core/issues/319
- https://github.com/SublimeTextIssues/Core/issues/1020

**Comment by patrick-ivers** [comment]
`Tools > SublimeLinter > Choose Gutter Theme...` and then set it to `None`

**Comment by mrmowgli** [comment]
I've also used lint mode->manual so that it doesn't mess with the plugin gitgutter, then just check manually.  It would be great if there were two columns for the gutter to use.

**Comment by camloken** [comment]
I found you can still use Modific and have errors highlight if you change the settings in Modific to display dot. Go to `Preferences > Package Settings > Modific > Settings - User` and add the following:

`{`
    ` "region_icon": "dot",`
`}`

Error s will now display with a red dot. Changes will have a green dot.

**Comment by ntwb** [comment]
I just stumbled on this issue whilst trying to debug the Sublime Linter warning and error colors

<img width="224" alt="screen shot 2017-09-19 at 12 59 59 pm" src="https://user-images.githubusercontent.com/1016458/30574222-e93b710c-9d3b-11e7-97b2-639a34d577a2.png">


If I change `"region_icon": "dot"` as you suggest @camloken the icons in the gutter change to `dots`, no colors are changed

<img width="220" alt="screen shot 2017-09-19 at 1 13 30 pm" src="https://user-images.githubusercontent.com/1016458/30574315-6a76bb5a-9d3c-11e7-9806-6898e2a9c560.png">

Here's the breakdown of each gutter mark:

• Line 13 is an added line (Modific)
• Lines 16 is a modified line (Modific)
• Line 18 is a removed line (Modific)
• Line 21 lint warning (Sublime Linter & Sublime Linter ESLint)
• Line 22 lint error (Sublime Linter & Sublime Linter ESLint)

So my issue is more of a issue for me as to why `"error_color": "D02000",` and `"warning_color": "DDB700",` are not currently being used on the lint error and warnings, more research to do ;)

**Comment by braver** [comment]
Disabling gutter marks is quite possible. There can only be one icon in the gutter at a time, which one is displayed depends on the situation. GitGutter creates a lot of marks and luckily has a way to prevent it from overriding other marks. There is no way to solve this beyond every package implementing something similar. I don’t think it’s reasonable to expect that to happen. Luckily there are several styles available and they can all be enabled and disabled at will.
