### ISSUE TITLE
how to set // to json

### ISSUE THREAD

**Issue by ildarkhasanshin** [SublimeLinter/SublimeLinter3#475]
how to set // for json-file
it's default-file for https://wbond.net/sublime_packages/sftp

![img-2016-07-02-23-48-53](https://cloud.githubusercontent.com/assets/8765305/16541994/0d3d5ac0-40b8-11e6-886b-556a29025d93.png)
![img-2016-07-02-23-46-54](https://cloud.githubusercontent.com/assets/8765305/16541996/10d3a680-40b8-11e6-86af-d7c85ced371d.png)

**Comment by braver** [comment]
JSON doesn’t allow comments. Sublime uses a lot of JSON-like files that do. I don’t know of a configuration or linter that allows comments here, but it should be possible. A better place to look for help would be the Sublime forums: https://forum.sublimetext.com
