### ISSUE TITLE
New Linter Plugin: SublimeLinter-contrib-stylelint_d

### ISSUE THREAD

**Issue by jo-sm** [SublimeLinter/SublimeLinter3#483]
https://github.com/jo-sm/SublimeLinter-contrib-stylelint_d

This plugin uses `stylelint_d`, which acts like a long-running `stylelint` process and makes linting with `stylelint` significantly faster.

**Comment by jo-sm** [comment]
Bumping this since it's been almost one month since initial issue submission...

**Comment by groteworld** [comment]
Sorry I missed this! Thank you for your wait.
https://github.com/SublimeLinter/package_control_channel/commit/4b56dabb6338d1519d9a0c3e4320645a8ace323f

**Comment by jo-sm** [comment]
Thank you!
