### ISSUE TITLE
ignore_match

### ISSUE THREAD

**Issue by ildarkhasanshin** [SublimeLinter/SublimeLinter3#485]
how to add an exception // for json-files?
https://s.mail.ru/8ZL1/RuGpr4msT - json-file
https://s.mail.ru/9VnY/nnZdDC2fT - linter-settings

**Comment by groteworld** [comment]
Changing the `strict` setting to `false` will allow you to have comments in a json file.

**Comment by ildarkhasanshin** [comment]
It did not help

"json": {
    "@disable": false,
    "args": [],
    "chdir": "/tmp",
    "excludes": [],
    "strict": false
}

**Comment by braver** [comment]
This is an issue with the linter, not with SL: https://github.com/SublimeLinter/SublimeLinter-json/issues/7
