### ISSUE TITLE
Stripping whitespace from message

### ISSUE THREAD

**Issue by niksy** [SublimeLinter/SublimeLinter3#486]
Is it possible to strip excess whitespace in `P<message>` argument? I’m using [stylelint](http://stylelint.io/) CLI output and it’s message has some excess whitespace I would like to remove (in screenshot, between "border: none" and "value-border-zero")

![screen shot 2016-08-15 at 10 22 32](https://cloud.githubusercontent.com/assets/389286/17659401/8960dec4-62d2-11e6-9772-28b61f1b4689.png)

**Comment by braver** [comment]
The stylelint linter plug-in should be able to do some regex processing on the messages before sending them to SL. Perhaps start looking for a solution there: https://packagecontrol.io/packages/SublimeLinter-contrib-stylelint
