### ISSUE TITLE
JS with PHP

### ISSUE THREAD

**Issue by alexandre1985** [SublimeLinter/SublimeLinter3#487]
I have SublimeLinter, SublimeLinter-jshint and SublimeLinter-php on my Sublime Text.
An example of that it happens:
I have an .php file that has javascript code and a bit of php in it.
My syntax highlight is set to JavaScript.
The problem is that the php code it appears as an error on linter.
How can I make SublimeLinter detect the php code that is on a Javascript file and use the SublimeLinter-php on those lines of code?
Best Regards

**Comment by braver** [comment]
The PHP syntax you’re using could support the embedded JavaScript syntax. That way both linters would work. If you set the PHP file to JS syntax all you can do is disable the linter (jshint probably has “disable” comments) for the PHP blocks because nothing is able to tell it’s PHP.
