### ISSUE TITLE
New linter plugin request SublimeLinter-contrib-avr-gcc

### ISSUE THREAD

**Issue by ChisholmKyle** [SublimeLinter/SublimeLinter3#488]
Linter link: [https://github.com/ChisholmKyle/SublimeLinter-contrib-avr-gcc](https://github.com/ChisholmKyle/SublimeLinter-contrib-avr-gcc)

I'm using it for programming Arduino. I've tested it on Mac and Windows but not Linux (yet). It's a simple linter and has almost the exact same code as SublimeLinter-contrib-clang

**Comment by groteworld** [comment]
you'll want to fix your TravisCI link in the readme. Other then that make a release tag and I'll get it into Package Control

**Comment by ChisholmKyle** [comment]
OK fixed the TravisCI link and made a release.

**Comment by ChisholmKyle** [comment]
Can we get this into Package Control? Thanks

**Comment by groteworld** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/eec5f6fcca196b933156a894504c9c10881717cf

Should show up within an hour in Package Control. Thanks Again!
