### ISSUE TITLE
No tooltips?!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [SublimeLinter/SublimeLinter3#494]
I'm completely lost. How can I activate tooltips, say for instance in the python 3 linter, or globally for all linters.

Like if I go with my cursor over the linted text a tooltip opens.

**Comment by saschagehlich** [comment]
Not possible right now - move your text cursor to the underlined code and you'll see the according linter message in the status bar. Or press `^⌘A` to show all linter errors in your code.

**Comment by groteworld** [comment]
Tooltips have been added in v3.8.0
