### ISSUE TITLE
Python 3 Annotations are marked as syntax error

### ISSUE THREAD

**Issue by mevinbabuc** [SublimeLinter/SublimeLinter3#496]
Python 3 annotations are not identified by sublimeLinter. Is there some settings that I need to add to get this working or is this not implemented yet ?

**Comment by braver** [comment]
SublimeLinter doesn’t lint anything by itself. What linter are you using and have you tried looking at its documentation?

**Comment by braver** [comment]
This really is specific to a specific linter.
