### ISSUE TITLE
Is it possible to use one linter with different configs?

### ISSUE THREAD

**Issue by 34x** [SublimeLinter/SublimeLinter3#499]
Hello,

In my project I have 3 code styles based on file extensions, and for all of this files I am using one linter (for example one linter but different configurations for php, js and phtml files). Is it any way to get such configuration? 

Best regards

**Comment by braver** [comment]
Sure, it's up to the linter to look for a config file. This way you can, for instance, use the same eslint linter for different projects and have different config for each.
