### ISSUE TITLE
csstree linter

### ISSUE THREAD

**Issue by smelukov** [SublimeLinter/SublimeLinter3#500]
https://github.com/csstree/SublimeLinter-contrib-csstree

**Comment by groteworld** [comment]
Fix the TravisCI build link in README.md and make a release. I'll then get it into Package Control. Thank!

**Comment by smelukov** [comment]
done
thank!

**Comment by groteworld** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/958eb80f3a6e5fdca6867a620548d438e9e277f4

Should show up within an hour in Package Control. Thanks Again!
