### ISSUE TITLE
It's time! Inline errors and hover definitions

### ISSUE THREAD

**Issue by noma4i** [SublimeLinter/SublimeLinter3#502]
Since big announcement SublimeLinter should have inline error messages and on-hover support implemented.

https://www.sublimetext.com/blog/articles/sublime-text-3-build-3124

**Comment by FichteFoll** [comment]
Duplicate: https://github.com/SublimeLinter/SublimeLinter3/issues/471

**Comment by noma4i** [comment]
If somebody needs that. Iv baked version which has replaced `Show all errors`method. Instead of showing a list in quick view it will place errors inline. Plays nice with `Show all errors on save` by clearing outdated errors and showing only relevant.

Not planning to make a PR. Use it on your own risk ;) https://github.com/noma4i/SublimeLinter3

![screen shot 2016-09-26 at 9 46 09 am](https://cloud.githubusercontent.com/assets/210667/18819165/1e07a726-83ce-11e6-9397-33ac51a22107.png)

**Comment by nikini** [comment]
@noma4i Why not do a PR?

**Comment by jgalentine007** [comment]
I'm a bit new to Sublime Text - Does anyone know if there is a way to get a simple persistent listing of all linter errors without having to engage the quick panel?  Ala the error pane in Visual Studio or most any other IDE? (I guess this might have more to do with Sublime Text itself - I know that it is a text editor and not an IDE but only having a one line status bar seems a bit silly!)

**Comment by groteworld** [comment]
Merging discussion to #471

**Comment by Cerberus-tm** [comment]
@noma4i Hi! I remember using your inline errors and liking it very much. Do you think a similar thing would be possible with the Sublime Linter 5? It has pop-ups, which are nice, but I'd love to also have the option of showing all errors inline as in your old version...
