### ISSUE TITLE
Couldn't get the path working

### ISSUE THREAD

**Issue by vennsoh** [SublimeLinter/SublimeLinter3#505]
Hi there, 

I have been following the guides on finding a linter executable but I don't seem to be able to get it working?
http://sublimelinter.readthedocs.io/en/latest/troubleshooting.html#finding-a-linter-executable

Conditions:
I don't have admin access to my machine.

My steps:
1. Installed all my npm packages without using sudo. https://docs.npmjs.com/getting-started/fixing-npm-permissions (eg: npm install -g csslint / jshint / ...)
2. Then I install ST3 sublimelinter.
3. Then I install the sublimelinter-csslint / jshint / ...
4. I created .bashrc and .bash_profile at my home directory.
5. .bashrc is empty.
6. I put this in .bash_profile

export PATH=/opt/bin:$PATH

case $- in
   _i_) source ~/.bashrc
esac

---

Tried:
# Mac OS X, Linux

hash -r
which linter // No results no error as if nothing has happened? Do I type which linter or which csslint? I tried bot but all return nothing

echo $SHELL // This returns /bin/bash

---

What else should I be trying?

**Comment by braver** [comment]
It’s been a while... did you ever get this working?

**Comment by braver** [comment]
🤷‍♂️ We'll re-open if there's news.
