### ISSUE TITLE
New linter plugin request SublimeLinter-contrib-lesshint

### ISSUE THREAD

**Issue by jasjuang** [SublimeLinter/SublimeLinter3#508]
Repo link: https://github.com/jasjuang/SublimeLinter-contrib-lesshint

After finding there was no SublimeLinter plugin for lesshint, so I put this together. Works perfectly on my own machine.

**Comment by groteworld** [comment]
Sorry for the slow response! Should show up within an hour in Package Control. Thanks Again!
