### ISSUE TITLE
Doesnt work at all

### ISSUE THREAD

**Issue by Alecto** [SublimeLinter/SublimeLinter3#513]
CSS file. last sublime.
It does not find any errors, even though I made them deliberately.

**Comment by braver** [comment]
@Alecto, if you're still having these problems, what linters are you running and is there any output in the console that might help finding out what's wrong?

**Comment by Alecto** [comment]
no, I do not use it, tried to put it and set it up several times, but completely unsuccessfully. if you try to figure it out, I'll try to put it again and see what is output and where.

**Comment by braver** [comment]
If you want to try again, I'll try to help you out to get it running again. For most people it seems to work, so we should be able to get it going too!

**Comment by braver** [comment]
We'll re-open if there's news.
