### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by saltnpixels** [SublimeLinter/SublimeLinter3#517]
I am having issues:
```
Packages/SublimeLinter/lint/queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./python3.3/queue.py", line 175, in get
queue.Empty
```

and theres a lot more of that....
I cannot get this working with php lint.

**Comment by groteworld** [comment]
What does your SublimeLinter.sublime-settings file look like?

**Comment by saltnpixels** [comment]
I deleted my user settings for sublime linter 3 and it fixed everything!

**Comment by groteworld** [comment]
Awesome, Thank you for using SublimeLinter!
