### ISSUE TITLE
SublimeLinter-contrib-bandit

### ISSUE THREAD

**Issue by ericwb** [SublimeLinter/SublimeLinter3#518]
Please take a look at my new linter for that does security linting.   I have tested it and seemed to be working nicely.  I'd like to contribute it to the SublimeLinter GitHub repo.

The repo can be found here:

https://github.com/ericwb/SublimeLinter-contrib-bandit

**Comment by groteworld** [comment]
Thank you! Please fix the TravisCI link in the README and make a [release](https://github.com/ericwb/SublimeLinter-contrib-bandit/releases).

Closes #159

**Comment by ericwb** [comment]
Ok, I've removed "contrib" from links and docs, updated the travis link, and made a 1.0.0 release.  I think its ready to go.  Thanks

**Comment by groteworld** [comment]
You should have received an invite to the SublimeLinter organization. Send a transfer request for the repo to SublimeLinter and I'll accept it and get it in Package Control.

**Comment by ericwb** [comment]
Ok, I accepted the invite, but I'm unclear on how to issue a transfer request.  I see there is a Transfer Ownership option, but when I attempt to transfer it to SublimeLinter, it fails with " You don’t have the permission to create repositories on SublimeLinter".

**Comment by groteworld** [comment]
ok you should have seen that you've gotten access to the repository. I pushed your version to this repository and you should have write access, i'll get this in package control, feel free to remove your repo and fork [SublimeLinter/SublimeLinter-bandit](https://github.com/SublimeLinter/SublimeLinter-bandit) or just work out of that repository.

Thank you for your contribution
