### ISSUE TITLE
ComposerLinter submodule

### ISSUE THREAD

**Issue by cjquinn** [SublimeLinter/SublimeLinter3#522]
Looking at the `NodeLinter` class it looks in `node_modules/.bin` for an executable which is handy as you don't need to install everything globally. Is there any scope for doing something similar with linters that exist as composer packages?

Thoughts? Happy to put in a pull request.

**Comment by groteworld** [comment]
Following NodeLinter's example, I think there is a place for this project for ComposerLinter (not sure how common Composer is with all PHP developers/linters so PHPLinter?). Only question I'd have is usage, like I said, I don't know if a lot, or any of our current PHP linters use composer to download them. But if there is one or two, and if they want to use it. I'd say it's helpful.

I am not a PHP developer though, so it won't be me doing this development, I just don't know enough about the ecosystem.

@ajmichels thoughts, knowledge?

**Comment by cjquinn** [comment]
Both `phpcs` and `phpmd` exist on [Packagist](https://packagist.org/) and have instructions for installing using composer, but they do specify globally. I feel like more and more, especially in the JavaScript world, people are recommending using dev dependencies on a project basis though.

I did also find something called `phplint` on Packagist as well but I'm not sure its the same thing as there seem to be a few `phplint`s floating about.

**Comment by ajmichels** [comment]
I think composer has a pretty strong adoption. As @cjquinn mentioned both `phpcs` and `phpmd` are setup to be installed easily with composer. There may be other linters/libraries that are not currently represented in the SublimeLinter org, but I am not sure how many. We could certainly implement some sort of ComposerLinter and people can extend. Both the phpcs and phpmd projects are setup to support per-project executable paths, so there is a route for people can take to utilize packages installed into a projects 'vendor' directory. That being said an automated solution would probably be welcomed. It certainly adds additional complexity that will have to be maintained as Composer evolves, just as NodeLinter has to be maintained as NPM evolves. The solution would probably not look much different than what is in NodeLinter, just different names and paths, maybe some other minor differences.

**Comment by groteworld** [comment]
Awesome thank you, both of you! In that case, this seems like a good win for the community. I look forward to pull requests

**Comment by cjquinn** [comment]
@ajmichels looking through the source for `NodeLinter` its going to be practically the same functionality. Are you happy for me to give this a bash?

**Comment by ajmichels** [comment]
Go for it. I can look over any PRs you com up with.

**Comment by cjquinn** [comment]
@ajmichels I've submitted a PR here #528.

**Comment by braver** [comment]
fixed in #528.
