### ISSUE TITLE
visual feedback when file has "no errors"

### ISSUE THREAD

**Issue by brupelo** [SublimeLinter/SublimeLinter3#523]
Your package is awesome, I've been using for a while the alternative [Flake8Lint](https://github.com/dreadatour/Flake8Lint/blob/master/Flake8Lint.py#L981) package but after realizing a very old version of flake8 was being shipped with it i don't see any strong reason for not start using this one, also I can see this one is actively maintained.

I must to say after using this package for few minutes I can see it works very well out of the box. I'm still missing a really cool feature from Flake8Lint package, this is, every time your file didn't contain any warning/error, some icons would start blinking in the bookmarks section, the feature seems quite trivial to implement and you can find it [over here](https://github.com/dreadatour/Flake8Lint/blob/master/Flake8Lint.py#L981).

You can see you can specify if you want or not to get the success report through the user settings, hope you consider implementing it for the next release. It's a non-obtrusive feature, so... ;)

Thanks in advance.

**Comment by braver** [comment]
I don’t think blinking gutter marks is a really great idea, but the status bar could provide explicit feedback that there are no issues.
