### ISSUE TITLE
KeyError: 'all' when executing SublimeLinterToggleLinter command

### ISSUE THREAD

**Issue by brupelo** [SublimeLinter/SublimeLinter3#524]
When i call more than once the next command `{ "keys": ["ctrl+k", "ctrl+t"], "command": "sublimelinter_toggle_linter", "args": {"which": "all"}}` I'll get the next error:

    Traceback (most recent call last):
      File "D:\software\SublimeText 3_x64\sublime_plugin.py", line 795, in run_
        return self.run(**args)
      File "D:\software\SublimeText 3_x64\Data\Packages\SublimeLinter\commands.py", line 673, in run
        if self.linters[self.which]:
    KeyError: 'all'

In order to run this command many times using the I need to `Clear Caches`. 

When I execute the command using the contextual menu instead the shortcut the error doesn't happen.

Windows7 over here.

**Comment by braver** [comment]
We dropped this in SL4: https://github.com/SublimeLinter/SublimeLinter3#sublimelinter-4-beta
