### ISSUE TITLE
Linting seem to be done with text in ram not the saved file and generate a lot of false positive.

### ISSUE THREAD

**Issue by devanonyme** [SublimeLinter/SublimeLinter3#526]
Hello,

We are working on Windows from a SVN repository that checkout with windows line-ending.

Our .eslintrc.json file has this config:
"linebreak-style": ["error", "windows"]

And it works fine in Webstorm but not with my collegues that are using Sublime. We have checked all the configs and it does look like the linting is done in memory using the working line-ending of Sublime, not the one that will be applied at save.

Is this a known problem and is there a documented workaround aside deactivating the rule althogether?

Thanks!

**Comment by braver** [comment]
Linters work on the buffer, an in-memory representation of the file on disk. Pretty much everything in Sublime works this way. 

You could disable the lint rule altogether, but linters in SL given extra parameters as well. Please have a look at the documentation: http://www.sublimelinter.com/en/latest/linter_settings.html. Eslint takes a “rules” argument that you should be able to use to disable this specific rule in Sublime: https://eslint.org/docs/user-guide/command-line-interface#--rule

**Comment by devanonyme** [comment]
I have probably filled it the wrong way. I still think that if sublime is changing line ending in it's ram representation it should convert it back to the file representation before passing it throught the linting process.

Disabling the rule defeat the purpose.
