### ISSUE TITLE
SublimeLinter-contrib-epcomp

### ISSUE THREAD

**Issue by veelo** [SublimeLinter/SublimeLinter3#527]
Hi,

Thanks for providing a powerfull linting framework, which enabled me to turn an archaic compiler into an efficient linter for Extended Pascal.

Please consider https://github.com/veelo/SublimeLinter-contrib-epcomp for inclusion in Package Control.

Thanks,
Bastiaan Veelo.

**Comment by groteworld** [comment]
Excuse my extremely slow response time! Please make a github release and I will add this plugin to Package Control. Thanks!

**Comment by veelo** [comment]
Done!
Thanks a lot.

**Comment by groteworld** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/14243e6e3fef260dc69f325a8e4a36686f6e016c
Should show up within an hour in Package Control. Thanks Again!
