### ISSUE TITLE
WARNING: no jshint version could be extracted from:

### ISSUE THREAD

**Issue by fredrikpaues** [SublimeLinter/SublimeLinter3#529]
I can't seem to get the jshint linter to work on Windows 10 w/ Sublime Text (build 3126). I have installed Node.js (`node -v` from the command line outputs `v6.9.2`), jshint (`jshint -v` outputs `jshint v2.9.4`) and jshint is in the ["paths"](http://www.sublimelinter.com/en/latest/global_settings.html#paths-setting) global setting:

    "paths": {
        "linux": [],
        "osx": [],
        "windows": [
            "C:/Users/Fredrik/AppData/Roaming/npm"
        ]
    }

(`where jshint` outputs `C:\Users\Fredrik\AppData\Roaming\npm\jshint` `C:\Users\Fredrik\AppData\Roaming\npm\jshint.cmd`)

All the console output generated from SublimeLinter Debug Mode which mentions SublimeLinter is below.

    reloading plugin SublimeLinter-chktex.linter
    SublimeLinter: chktex linter loaded 
    reloading plugin SublimeLinter-contrib-scss-lint.linter
    SublimeLinter: scss linter loaded 
    reloading plugin SublimeLinter-csslint.linter
    SublimeLinter: csslint linter loaded 
    reloading plugin SublimeLinter-flake8.linter
    SublimeLinter: flake8 linter loaded 
    reloading plugin SublimeLinter-jshint.linter
    SublimeLinter: jshint linter loaded 
    reloading plugin SublimeLinter.commands
    reloading plugin SublimeLinter.sublimelinter
    SublimeLinter: debug mode: on 
    SublimeLinter: temp directory: c:\users\fredrik\appdata\local\temp\SublimeLinter3-Fredrik 
    SublimeLinter: find_python(version='3', script=None, module=None) 
    SublimeLinter: find_python: requested version = {'minor': None, 'major': 3} 
    SublimeLinter: find_windows_python: matching => C:\Program Files\Sublime Text 3\python33.dll\python.exe 
    SublimeLinter: find_windows_python: matching => C:\Program Files\Sublime Text 3\python3.3.zip\python.exe 
    SublimeLinter: find_windows_python: matching => C:\Program Files\Sublime Text 3\python33.dll\python.exe 
    SublimeLinter: find_windows_python: matching => C:\Program Files\Sublime Text 3\python3.3.zip\python.exe 
    SublimeLinter: computed PATH from system:
    C:\Users\Fredrik\AppData\Roaming\npm
    C:\Program Files\ImageMagick-7.0.3-Q16
    C:\Python27\
    C:\Python27\Scripts\
    C:\Python27\Lib\site-packages\
    C:\miktex\miktex\bin\
    C:\texlive\2014\bin\win32
    C:\Program Files (x86)\Intel\iCLS Client\
    C:\Program Files\Intel\iCLS Client\
    C:\Windows\system32
    C:\Windows
    C:\Windows\System32\Wbem
    C:\Windows\System32\WindowsPowerShell\v1.0\
    C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
    C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
    C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
    C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
    c:\Program Files\Intel\WiFi\bin\
    c:\Program Files\Common Files\Intel\WirelessCommon\
    C:\Program Files (x86)\Windows Live\Shared
    C:\Program Files (x86)\SumatraPDF
    C:\Strawberry\perl\bin
    C:\Strawberry\perl\site\bin
    C:\Strawberry\c\bin
    C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
    C:\cygwin64\bin
    C:\Anaconda
    C:\Anaconda\Scripts
    C:\WINDOWS\system32
    C:\WINDOWS
    C:\WINDOWS\System32\Wbem
    C:\WINDOWS\System32\WindowsPowerShell\v1.0\
    C:\Program Files\MATLAB\R2015a\runtime\win64
    C:\Program Files\MATLAB\R2015a\bin
    C:\Program Files (x86)\Skype\Phone\
    C:\Program Files\gs\gs9.20\bin
    C:\Program Files\Microsoft\Web Platform Installer\
    C:\Ruby21-x64\bin
    c:\Program Files\Intel\WiFi\bin\
    c:\Program Files\Common Files\Intel\WirelessCommon\
     
    SublimeLinter: find_windows_python: <= C:\Anaconda\python.exe 
    SublimeLinter: find_python: system python = C:\Anaconda\python.exe 
    SublimeLinter: find_python: available version = {'minor': 7, 'major': 2} 
    SublimeLinter: find_python: <= (None, None, 2, 7) 
    SublimeLinter: no python 3 available to augment sys.path 
    SublimeLinter: ENV['GEM_HOME'] = 'None' 
    SublimeLinter: jshint version query: C:\Users\Fredrik\AppData\Roaming\npm\jshint.cmd --version 
    SublimeLinter: WARNING: no jshint version could be extracted from:
    'node' is not recognized as an internal or external command,
    
    operable program or batch file.

**Comment by SaintDako** [comment]
It looks like `jshint` would be on the path but it's failing for `node`. Is `node` found in any of those listed directories? (After the line `SublimeLinter: computed PATH from system:`)

**Comment by braver** [comment]
Indeed looks like node isn’t available in your path there. If solving that doesn’t fix it let me know.
