### ISSUE TITLE
New plugin: livecodelint

### ISSUE THREAD

**Issue by trevordevore** [SublimeLinter/SublimeLinter3#531]
https://github.com/trevordevore/sublimelinter-contrib-livecodelint

**Comment by groteworld** [comment]
Sorry for the slow response time! Please make a github release and I'll put it in Package Control. Thanks!

**Comment by trevordevore** [comment]
Done!

**Comment by groteworld** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/5f6f72c85247f89028d75351eae6dead177cb085
Should show up within an hour in Package Control. Thanks Again!
