### ISSUE TITLE
New plugin: codeclimate

### ISSUE THREAD

**Issue by noahd1** [SublimeLinter/SublimeLinter3#532]
https://github.com/codeclimate/SublimeLinter-contrib-codeclimate

**Comment by groteworld** [comment]
Sorry for the slow response time! Please fix your TravisCI link in the README, make a release, and I'll put it in Package Control. Thanks!

**Comment by noahd1** [comment]
Hi @groteworld -

No problem. I've fixed the TravisCI link and tagged a release. Let me know if you need anything else.

Thanks for this project!

**Comment by groteworld** [comment]
Sorry for my speed! Should show up within an hour in Package Control. Thanks Again!

https://github.com/SublimeLinter/package_control_channel/commit/dbe1bad4a36f0934e46f45036bda67b97f981cfa
