### ISSUE TITLE
underline problems only on the current line under cursor

### ISSUE THREAD

**Issue by aristidesfl** [SublimeLinter/SublimeLinter3#535]
Would it be possible to add an option to show marks only on the line(s) under the cursor? In this case marks would be invisible unless the cursor is positioned in the line which has the error. Gutter marks would be independent  and always visible.

![screen shot 2017-01-30 at 14 03 00](https://cloud.githubusercontent.com/assets/208149/22424007/d4362304-e6f4-11e6-9947-8d359863b5a1.png)

**Comment by braver** [comment]
I think this is a bit outside of what a normal use case for SL would look like. How would this improve things? If you are dealing with loads and loads of errors, perhaps that points to a different issue you need to deal with.

Also, if anything, we're not looking to make the behaviour more complicated.
