### ISSUE TITLE
New plugin: ansible-lint

### ISSUE THREAD

**Issue by mliljedahl** [SublimeLinter/SublimeLinter3#536]
SublimeLinter plugin for Ansible, using ansible-lint.

Repo link: https://github.com/mliljedahl/SublimeLinter-contrib-ansible-lint

**Comment by nklmilojevic** [comment]
When will this be in Package Control? 

Thanks

**Comment by mliljedahl** [comment]
@nklmilojevic hopefully soon :) Waiting for this plugin to be reviewed by the maintainers.

**Comment by nklmilojevic** [comment]
Me too! :) Thanks for the great work.

**Comment by groteworld** [comment]
I'm sorry for the slow response, Please fix the TravisCI link, "Recommended" is spelt wrong [here](https://github.com/mliljedahl/SublimeLinter-contrib-ansible-lint#reccomended-plugin), and make a release and I will put it into Package Control. Thanks!

**Comment by mliljedahl** [comment]
Thanks @groteworld! The first release is now pushed with the fixes you suggested.

**Comment by groteworld** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/d89ad0333672b0018d43bbc28cca65b4c9560f88
Thank you both for the ping! Should show up within an hour in Package Control. Thanks Again!
