### ISSUE TITLE
ERROR: eslint cannot locate 'eslint'

### ISSUE THREAD

**Issue by a-ludi** [SublimeLinter/SublimeLinter3#539]
I have some trouble with `eslint`. When I start Sublime  the console says: `ERROR: eslint cannot locate 'eslint'`

#### Temporary Fix

To fix the issue I open the (global) settings file alter the `paths`, save, restore the correct `paths` and save. After this procedure `eslint` works just fine.

#### The Catch

I could not isolate the original cause for this behaviour, but wanted to file the bug in case somebody else suffers from this.

**Comment by a-ludi** [comment]
@braver Why did you close this issue? It is *not* resolved!

**Comment by braver** [comment]
@a-ludi what is the issue then? 

There are loads of reasons a linter may not be able to find its excecutable. There are also loads of solutions for that, one being the manual configuration of paths. Which solved the problem for you. Unless I’m mistaken there is no bug to solve here. SublimeLinter cannot automatically solve all the PATH issues someone might have.

**Comment by a-ludi** [comment]
@braver The issue arises at every start of Sublime. The "solution" is only temporary until sublime is restarted. The solution requires a manual reconfigure at every start of sublime. This must be something inherent to SublimeLinter.

Maybe you can give me a pointer where I can start looking for the issue?

**Comment by braver** [comment]
Oh, right, sorry, I totally didn't get that from the original issue. For starters, what OS and version of Sublime are you on?

- did you install eslint globally
- is the installation directory in your $path
- does it work from the command line (e.g. `eslint some-file.js`
- is there output in the console beyond that single line you mentioned
- did you try adding the eslint installation directory to the path options for SL
