### ISSUE TITLE
New linter plugin: SublimeLinter-contrib-gcc

### ISSUE THREAD

**Issue by jfcherng** [SublimeLinter/SublimeLinter3#540]
SublimeLinter plugin for `C/C++` using `gcc`.

Repo link: https://github.com/jfcherng/SublimeLinter-contrib-gcc

**Comment by groteworld** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/521dfd7b432377cb544a5095deb2d75a2606508b
Sorry for the slow approval! Should show up within an hour in Package Control. Thanks Again!
