### ISSUE TITLE
SublimeLinter's message doesn't fit status bar

### ISSUE THREAD

**Issue by mityukov** [SublimeLinter/SublimeLinter3#542]
.. and it seems there is no option to read the whole message without increasing editor window size (far beyond the screen width, sometimes).

There might be something useful in the end of message, sometimes. Here's an example:

https://www.evernote.com/l/ACgO99QJbJlJN6iCo8xOinMEwiAr8jyVLxc

So, to conclude:

1. The message doesn't fit;

2. Whole message, split on several lines could probably be displayed:
   - in a tooltip when the mouse is over the status bar
   - in a popup, when the status bar is clicked
   - or, maybe, there could be a command available for Cmd+Shift+P, like: "show current error message"

Neither of options is available (or I couldn't find). There should be a solution, I believe. Maybe an option to see full message in the panel.

**Comment by mrusme** [comment]
With tooltips now being available, SublimeLinter could provide an option to fully disable displaying any text in the status bar. Imho this would be the best solution to this issue.
