### ISSUE TITLE
[Bug] SublimeLinter don't work in unsaved buffers in a new windows.

### ISSUE THREAD

**Issue by Kristinita** [SublimeLinter/SublimeLinter3#545]
### 1. Summary

SublimeLinter don't work in unsaved buffers in a new windows.

### 2. Expected behavior

Succesful work in unsaved buffers in new window like behavior, if I wrote my text in a new tab — <kbd>Ctrl+N</kbd> in Windows.

![Expected](http://i.imgur.com/9HjmFgl.png)

Sublime Text console output in debug mode:

```c++
SublimeLinter: writegood: <unsaved> ['C:\\Users\\SashaChernykh\\AppData\\Roaming\\npm\\write-good.cmd'] 
SublimeLinter: writegood output:
In c:\users\sashac~1\appdata\local\temp\SublimeLinter3-SashaChernykh\untitled.tmp
=============
many really
^^^^
"many" is a weasel word and can weaken meaning on line 3 at column 0
-------------
many really
     ^^^^^^
"really" can weaken meaning on line 3 at column 5 
SublimeLinter: proselint: <unsaved> ['C:\\Python36\\Scripts\\proselint.exe'] 
chr evt: ) (0x29)
SublimeLinter: writegood: <unsaved> ['C:\\Users\\SashaChernykh\\AppData\\Roaming\\npm\\write-good.cmd'] 
SublimeLinter: writegood output:
In c:\users\sashac~1\appdata\local\temp\SublimeLinter3-SashaChernykh\untitled.tmp
=============
many really
^^^^
"many" is a weasel word and can weaken meaning on line 3 at column 0
-------------
many really
     ^^^^^^
"really" can weaken meaning on line 3 at column 5 
SublimeLinter: proselint: <unsaved> ['C:\\Python36\\Scripts\\proselint.exe'] 
SublimeLinter: proselint output:
c:\users\sashac~1\appdata\local\temp\SublimeLinter3-SashaChernykh\untitled.pltmp:5:2: typography.symbols.ellipsis '...' is an approximation, use the ellipsis symbol '…'.
c:\users\sashac~1\appdata\local\temp\SublimeLinter3-SashaChernykh\untitled.pltmp:7:1: sexism.misc Gender bias. Use 'husband and wife' instead of 'man and wife'.
c:\users\sashac~1\appdata\local\temp\SublimeLinter3-SashaChernykh\untitled.pltmp:9:2: typography.symbols.copyright (c) is a goofy alphabetic approximation, use the symbol ©.
```

### 3. Actual behavior

Nothing occurs, no output in Sublime Text console in debug mode.

Behavior, if I wrote my text in a new window — <kbd>Ctrl+Shift+N</kbd> in Windows.

![Actual](http://i.imgur.com/VchttOJ.png)

<kbd>Ctrl+Shift+P</kbd> → SublimeLinter: Lint This View → no effect.

### 4. Settings

My `User/SublimeLinter.sublime-settings` file:

```json
{
    "user": {
        "debug": true,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Danish Royalty/Danish Royalty.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {
            "annotations": {
                "@disable": false,
                "args": [],
                "errors": [
                    "FIXME"
                ],
                "excludes": [],
                "warnings": [
                    "NOTE",
                    "README",
                    "TODO",
                    "XXX",
                    "@todo"
                ]
            },
            "csslint": {
                "@disable": false,
                "args": [],
                "errors": "",
                "excludes": [],
                "ignore": [
                    "order-alphabetical",
                    "ids"
                ],
                "warnings": ""
            },
            "htmltidy": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "jshint": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "proselint": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "slimlint": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "sublimesyntax": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "writegood": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "xmllint": {
                "@disable": false,
                "args": [],
                "excludes": []
            }
        },
        "mark_style": "fill",
        "no_column_highlights_line": true,
        "passive_warnings": true,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": false,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "javascript (babel)": "javascript",
            "magicpython": "python",
            "nuget": "xml",
            "php": "html",
            "python django": "python",
            "pythonimproved": "python",
            "xml": "xml"
        },
        "warning_color": "DDB700",
        "wrap_find": false
    }
}
```

My text in unsaved buffers:

    many really

    ...

    man and wife

    (c)

### 5. Steps to reproduce

I reproduce the problem in a version of Sublime Text without plugins and user settings.

I install SublimeLinter; [**proselint**](https://packagecontrol.io/packages/SublimeLinter-contrib-proselint) and [**write-good**](https://packagecontrol.io/packages/SublimeLinter-contrib-write-good) linters → I restart Sublime Text.

<kbd>Ctrl+N</kbd> → I wrote my text in new tab → I get expected behavior.

<kbd>Ctrl+Shift+N</kbd> → I wrote my text in new window → I get actual behavior.

### 6. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126
**SublimeLinter:**
3.7.4

Thanks.

**Comment by Pysis868** [comment]
I have build 3114, and my "Tools > SublimeLinter Lint this View (Ctrl+Super+L)" option in the menu is grayed out disabled for new, unsaved buffers/panes/views.

**Comment by braver** [comment]
Works just fine on my machine. New instance of Sublime, new window, unsaved file: background linting is active and errors are highlighted. Could you try again with recent versions of Sublime and SL?

**Comment by Kristinita** [comment]
**Status: :broken_heart: Partially fixed**

Please, reopen this issue.

### 1. Summary

SublimeLinter for unsaved buffers:

Work:

+ new tab (<kbd>Ctrl+N</kbd> in Windows)
+ new window (<kbd>Ctrl+Shift+N</kbd> in Windows)

Doesn't work:

    basic usage of these packages:

+ [**GhostText Sublime Text**](https://packagecontrol.io/packages/GhostText)
+ [**GitHub Issue Sublime Text**](https://packagecontrol.io/packages/GitHubIssue)

### 2. Environment

The latest versions at 27 April 2018:

+ Windows 10 Enterprise LTSB 64-bit EN
+ Sublime Text Build 3143
+ Firefox 59.0.2 (64-bit)
+ SublimeLinter 4.3.2
+ SublimeLinter-contrib-write-good 2.2.0
+ GitHub Issue 3.3.0
+ GhostText Sublime 1.0.13
+ GhostText Firefox 17.12.11.910
+ MarkdownEditing 2.2.6
+ nircmd 2.81

### 3. Configuration

my `User/SublimeLinter.sublime-settings` file:

```json
{
	"debug": true,
}
```

### 4. Steps to reproduce

I reproduce the problem in a version of Sublime Text without plugins and user settings.

I install all environment from section above → I restart Sublime Text → I make basic actions for GhostText and GitHub Issue packages:

#### 4.1. GhostText

I open any webpage with textarea, for example, **<https://github.com/SublimeLinter/SublimeLinter/issues/545>** → I press GhostText button in Firefox toolbar → I wrote `many really` in opened unsaved buffer.

#### 4.2. GitHub Issue

<kbd>Ctrl+Shift+P</kbd> (<kbd>⌘⇧p</kbd> for Mac) → `GitHub Issue: Create Issue` → I print in opened field `SublimeLinter/SublimeLinter` → <kbd>Enter</kbd> → I wrote `many really` in opened unsaved buffer.

### 5. Expected behavior

Saved file:

![Normal](https://i.imgur.com/x2wXPn5.png)

Successful lint.

Sublime Text console output:

```node
SublimeLinter: SublimeLinter.sublime-package:275: Linting buffer 26 took 0.27s
SublimeLinter: SublimeLinter.sublime-package:229: Delay buffer 26 for 0.05s
SublimeLinter: #33 SublimeLinter.sublime-package:703: 'writegood' is linting 'test.md'
SublimeLinter: #33 SublimeLinter.sublime-package:1111: Running …

  D:\Киролайна  (working dir)
  > C:\Users\SashaChernykh\AppData\Roaming\npm\write-good.cmd c:\users\sashac~1\appdata\local\temp\tmpqkyu1v.md

SublimeLinter: #33 SublimeLinter.sublime-package:753: writegood output:
    In c:\users\sashac~1\appdata\local\temp\tmpqkyu1v.md
    =============
    many really
    ^^^^
    "many" is a weasel word and can weaken meaning on line 1 at column 0
    -------------
    many really
         ^^^^^^
    "really" can weaken meaning on line 1 at column 5
```

### 6. Actual behavior

GhostText unsaved buffer:

![GhostText](https://i.imgur.com/vk5lMuL.png)

GitHub Issue unsaved buffer:

![GitHub Issue](https://i.imgur.com/CPnjPXT.png)

No lint, no console output.

Thanks.

**Comment by kaste** [comment]
Hi 👋 

GitHub Issue sets the view as scratch https://github.com/divinites/gissues/blob/c95435f0d8a9923de8b5c4ca7304938abaf40e6f/libgit/utils.py#L29 and we don't lint such views

https://github.com/SublimeLinter/SublimeLinter/blob/7bbe75b3ad603a38c8393ee7da77b3ebb67f2749/lint/util.py#L79-L86

**Comment by kaste** [comment]
(Besides that, I don't know what scratchiness is in Sublime land, and why we don't lint scratchy buffers. 😬 )

**Comment by kaste** [comment]
GUI like buffers and diff views are probably also read-only.
