### ISSUE TITLE
transfer SublimeLinter-contrib-puppet and SublimeLinter-contrib-puppet-lint to new maintained repo

### ISSUE THREAD

**Issue by dschaaff** [SublimeLinter/SublimeLinter3#547]
The current version in package control is pulled from https://github.com/stopdropandrew/SublimeLinter-puppet and https://github.com/stopdropandrew/SublimeLinter-puppet-lint. sopdropandrew is no longer mainting the linters and I have updated them to keep them working.

https://github.com/stopdropandrew/SublimeLinter-puppet should change to https://github.com/dschaaff/SublimeLinter-puppet.

https://github.com/stopdropandrew/SublimeLinter-puppet-lint should change to https://github.com/dschaaff/SublimeLinter-puppet-lint.

See https://github.com/stopdropandrew/SublimeLinter-puppet/pull/1 and let me know what other info you'd like me to provide. 

Thanks!

**Comment by groteworld** [comment]
Thank you for making that easy, and for taking on support for these linters.
