### ISSUE TITLE
Update SublimeLinter-contrib-reek plugin

### ISSUE THREAD

**Issue by kruszczynski** [SublimeLinter/SublimeLinter3#548]
This update introduces better highlighting of code, introduced in [this PR.](https://github.com/codequest-eu/SublimeLinter-contrib-reek/pull/3) 

Repo link: https://github.com/codequest-eu/SublimeLinter-contrib-reek

**Comment by groteworld** [comment]
You seem to have made a release, which automatically pushes to package control within an hours time. It seems to be version 1.1.0 which includes the PR.

If I missed something in this issue let me know, but I don't need to do anything to update

Thanks

**Comment by kruszczynski** [comment]
You are correct, I was confused by the sentence "Then do the steps above with the new version." - I figured I had to create an issue. Sorry about that!

**Comment by groteworld** [comment]
No problem, glad we figured it out. Thanks again!
