### ISSUE TITLE
[setup] ValueError: Expecting property name enclosed in double quotes

### ISSUE THREAD

**Issue by nate-kobe** [SublimeLinter/SublimeLinter3#554]
OS: Elementary OS 0.4 (Loki)
Python 3.3
Latest Sublime Text

Installation worked fine, linters are found (eslint, xo). However, anytime ST tries to lint a file, it throws the following:

`Traceback (most recent call last):`
  `File "/opt/sublime_text/sublime_plugin.py", line 389, in run_callback
expr()`
   `File "/opt/sublime_text/sublime_plugin.py", line 522, in <lambda> run_callback('on_activated', callback, lambda: callback.on_activated(v))`
  `File "/home/user/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 278, in on_activated self.check_syntax(view)`
  `File "/home/user/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 205, in check_syntax  Linter.assign(view, reset=True)`
  `File "/home/user/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 755, in assign
    linter = linter_class(view, syntax)`
  `File "/home/user/.config/sublime-text-3/Packages/SublimeLinter/lint/node_linter.py", line 55, in __init__
    self.read_manifest(path.getmtime(self.manifest_path))`
  `File "/home/user/.config/sublime-text-3/Packages/SublimeLinter/lint/node_linter.py", line 241, in read_manifest   self.cached_manifest = json.load(codecs.open(self.manifest_path, 'r', 'utf-8'))`
 ` File "./python3.3/json/__init__.py", line 271, in load`
  `File "./python3.3/json/__init__.py", line 316, in loads`
  `File "./python3.3/json/decoder.py", line 351, in decode`
  `File "./python3.3/json/decoder.py", line 367, in raw_decode`
`ValueError: Expecting property name enclosed in double quotes: line 106 column 3 (char 3230)`

**Comment by NickMackz** [comment]
You probably have a mistake in your package.json.

I received an almost identical error message when I'd left an extra comma at the end of `dependencies` in my project's package.json.

**Comment by braver** [comment]
@nate-kobe could you check your package.json and report back if @NickMackz has the right suggestion?

**Comment by braver** [comment]
🤷‍♂️ We'll re-open if there's news.

**Comment by feliperaul** [comment]
I started having this error after I added comments to my package.json, using `//` at the beginning of every line (which should be allowed).

@braver could you please reopen?

**Comment by braver** [comment]
Comments aren't allowed in JSON.
