### ISSUE TITLE
New linter plugin: SublimeLinter-contrib-nvcc

### ISSUE THREAD

**Issue by blahgeek** [SublimeLinter/SublimeLinter3#555]
Linter for CUDA C++ sources using nvcc.

Repo link: https://github.com/blahgeek/SublimeLinter-contrib-nvcc

**Comment by groteworld** [comment]
Please fix the TravisCI link and make a github release, and I will get it into Package Control. Thank you for supporting SublimeLinter

**Comment by blahgeek** [comment]
Done. Thanks for your review!

**Comment by groteworld** [comment]
https://github.com/SublimeLinter/package_control_channel/commit/f7f7090057857d762867cb9bc3ff4b0f13afc22e

Awesome! Thanks!!
