### ISSUE TITLE
"passive warnings" doesn't work if there is also an error on the same line

### ISSUE THREAD

**Issue by nchursin** [SublimeLinter/SublimeLinter3#557]
Using pep8 interface. Steps to reproduce:
1. Set `Passive warnings` to True.
2. Have first warning, then an error in one line. E.g.:
```	
class sample():
	def __init__(self):
		pass
		
		
	def foo():
		pass

```
This will show `Indent with tabs` and after that `Too many blank lines`. The last is considered to be an error. 
3. Execute `Show all errors`.

Expected:
Only `Too many blank lines` is shown.

Actual:
Both warning (`Indent with tabs`) and error (`Too many blank lines`) are shown.

I'm pretty sure it's not pep8 linter specific, but it's the only linter I use. 

UPD: checked that on flake8 linter - it's there too.

**Comment by braver** [comment]
https://github.com/SublimeLinter/SublimeLinter3/blob/master/commands.py#L230

It just checks the type of errors on the line, so if there is one error on the line it will show all everything from that line.

**Comment by braver** [comment]
We're not going to fix this by patching the current implementation, it's too weird and confused for that. Error reporting will have to be completely redone.
