### ISSUE TITLE
New linter plugin: SublimeLinter-contrib-joker

### ISSUE THREAD

**Issue by candid82** [SublimeLinter/SublimeLinter3#558]
Linter for Clojure and ClojureScript using [Joker](https://github.com/candid82/joker)

Repo link: https://github.com/candid82/SublimeLinter-contrib-joker

**Comment by groteworld** [comment]
Please fix the TravisCI links in the readme and make a github release, and I will get it in Package Control. Thanks!

**Comment by candid82** [comment]
Done!

**Comment by candid82** [comment]
Hey @groteworld, any chance this can be added in Package Control?

**Comment by groteworld** [comment]
Sorry for the wait!! Should show up within an hour in Package Control. Thanks Again!

https://github.com/SublimeLinter/package_control_channel/commit/cd461e304ae135df60466989210ec1021ec552c0
