### ISSUE TITLE
No new version info message after automatic upgrade 3.7.4 --> 3.8.0 

### ISSUE THREAD

**Issue by darkred** [SublimeLinter/SublimeLinter3#559]
Using ST3 3126 x64 in win10.

I had SublimeLinter 3.7.4 installed.
Today I launched ST3 and SublimeLinter got updated automatically to 3.8.0 via Package Control.
The upgrage completed ok. There were no errors in console (unfortunately I didn't keep the console entries)
But I didn't get the [3.8.0](https://github.com/SublimeLinter/SublimeLinter3/blob/master/messages/3.8.0.txt) message after the upgrade (I didn't get any message).

_For testing, I uninstalled SublimeLinter via Package Control and reinstalled it, 
but only got the generic [install.txt](https://github.com/SublimeLinter/SublimeLinter3/blob/master/messages/install.txt) message._

<br/>

Shouldn't I get the message regarding the new version?
Especially with the addition of the inline tooltips new feature, 
I'm afraid many users might miss it, if they get no message after the automatic upgrade.

**Comment by groteworld** [comment]
😢 yeah, there should have been the 3.8.0 message that auto-popped up on upgrade, but I forgot to add it to message.json. Will push out a revision and it should work.

**Comment by groteworld** [comment]
OK, so revision tag has been pushed so now when people auto-upgrade to 3.8.0+1, it should show up.

**Comment by darkred** [comment]
Thank you
