### ISSUE TITLE
[popups] Tooltip line numbers are off by one

### ISSUE THREAD

**Issue by bcaplan** [SublimeLinter/SublimeLinter3#560]
The line numbers that show up in the tooltips are zero indexed, but SublimeText starts them at 1.

![image](https://cloud.githubusercontent.com/assets/20348/24924729/aa660542-1eaa-11e7-8448-fd41a4dd9e67.png)

**Comment by rodu** [comment]
I'm experiencing this problem too.

![screenshot_2017-04-12_09-28-34](https://cloud.githubusercontent.com/assets/3225111/24948629/c9d22240-1f62-11e7-9a9a-5baa928e8634.png)

**Comment by braver** [comment]
I'm consolidating this and other related issues in #619
