### ISSUE TITLE
New linter plugin: SublimeLinter-contrib-tailor

### ISSUE THREAD

**Issue by vaemoi** [SublimeLinter/SublimeLinter3#562]
Linter for swift using [tailor](https://tailor.sh)

Repo Link -> https://github.com/vaemoi/SublimeLinter-contrib-tailor

**Comment by groteworld** [comment]
Please make a release and I'll put it in Package Control. Thanks!

**Comment by vaemoi** [comment]
Sorry, not quite sure what a release is?

**Comment by vaemoi** [comment]
Sorry, brainfart. Done!

**Comment by brwnrclse** [comment]
Hello just checking in, was there anything I missed on this repo?

Thanks again!

**Comment by vaemoi** [comment]
Hey just checking in, was there anything specific I missed in my release?

Thanks again!

**Comment by groteworld** [comment]
Nope, i'm just slow! Sorry!!! It should appear in Package Control within an hour.

https://github.com/SublimeLinter/package_control_channel/commit/b438f8229e3bd9c9751e92c29cb4fe2e596c3eeb
