### ISSUE TITLE
[popups] Tooltip only closes on user interaction.

### ISSUE THREAD

**Issue by eikeland** [SublimeLinter/SublimeLinter3#564]
Tooltips are a great feature for linters so good job for including this.
The issue i have is that the tooltip do not disappear when the error is fixed, like the gutter mark, it only disappear after moving arrow keys, enter, escape or mouseclick.

When i fix the error and just keep writing code on the same line the tooltip is still there and is blocking the code completion suggestions.

Shouldn't  the tooltip disappear when the guttermark disappers automatically?

Im on OSX 10.12.4 and ST Build 3126 using linter jshint.

**Comment by woble** [comment]
Tooltip is definitely a nice addition to SublimeLinter, kudos to the contributors. But I was wondering the same and also why it's not on hover and click instead.

Perhaps someone with the know-how can look at the implementation of tooltips in [TypeScript-Sublime-Plugin](https://github.com/Microsoft/TypeScript-Sublime-Plugin) as their integration is very nice from a user experience point of view. Ref: [quick_info.py](https://github.com/Microsoft/TypeScript-Sublime-Plugin/blob/master/typescript/commands/quick_info.py).

**Comment by braver** [comment]
I'm consolidating this and other related issues in #619
