### ISSUE TITLE
New plugin: gosimple

### ISSUE THREAD

**Issue by clocklear** [SublimeLinter/SublimeLinter3#566]
Repo: https://github.com/clocklear/SublimeLinter-contrib-gosimple
Tag: 1.0.0

Let me know if you need anything else!

**Comment by groteworld** [comment]
Should show up within an hour in Package Control. Thanks Again!

https://github.com/SublimeLinter/package_control_channel/commit/7e6acf42ab84e4409e2e6e817808ed9bcc466067
