### ISSUE TITLE
[popups] Tooltips flashing as you release the mouse (after clicking on a highlighted error)

### ISSUE THREAD

**Issue by darkred** [SublimeLinter/SublimeLinter3#568]
Using ST3 3126 (and now 3128) x64 in win10.
I use SublimeLinter 3.8.0 with SublimeLinter-contrib-eslint 1.10.0.

The tooltips are a great addition. Thanks a lot to everybody involved.

<br>

I've noticed the following issue:
currently the tooltips appear when you click on a highlighted error.
But then, as you release the mouse button,
the tooltip disappears momentarily  and then re-appears. 
giving the impression that it's "flashing".

_It's more apparent if you hold down the mouse button for a bit some longer and then release it._
Here is a video capture to see what I mean:
![video_2017-04-13_123620](https://cloud.githubusercontent.com/assets/723651/25000254/4f0db5c8-2049-11e7-9ac5-f78bc568290c.gif)

**Comment by jayfunk** [comment]
PR #579 I believe is targeted at fixing issues similar to the one you outlined. Which is being discussed about in #565.

**Comment by darkred** [comment]
Today Sublime Text 3 stable build 3143 has been released ([blog post](https://www.sublimetext.com/blog/articles/sublime-text-3-point-0)).
Because of that, hopefully PR #579 and #577 will be merged soon.

**Comment by braver** [comment]
I'm consolidating this and other related issues in #619
