### ISSUE TITLE
All patched SublimeLinter color schemes show up in the "UI: Select Color Scheme"

### ISSUE THREAD

**Issue by deathaxe** [SublimeLinter/SublimeLinter3#569]
Beginning with ST3 3127 a new command _UI: Select Color Scheme_ was introduced. It lists all _*.tmTheme_ files it can find and thus shows all the patched versions SublimeLinter created, too. This is confusing.

#### Suggestion

To avoid this all the patched color schemes should use _*.hidden-tmTheme_ as file extension.

**Comment by deathaxe** [comment]
I also created an issue in [SublimeTextIssues](https://github.com/SublimeTextIssues/Core/issues/1663#issuecomment-294503789) as it was not clear who might be responsible to hide unwanted color schemes. The response seems clear.

**Comment by FichteFoll** [comment]
Note that they also used to show up in the menu before the addition of the quick-panel selection (with previews).
