### ISSUE TITLE
New linter plugin: SublimeLinter-contrib-swaglint

### ISSUE THREAD

**Issue by byCedric** [SublimeLinter/SublimeLinter3#571]
Linter for swagger documents using [swaglint](https://github.com/bycedric/swaglint)

https://github.com/byCedric/SublimeLinter-contrib-swaglint.

**Comment by groteworld** [comment]
Please make a release and I'll put it in Package Control. Thanks!

**Comment by byCedric** [comment]
Done!

**Comment by groteworld** [comment]
Should show up within an hour in Package Control. Thanks Again!

https://github.com/SublimeLinter/package_control_channel/commit/b33457ba98ab9b685d24475774e6f0b471adb859
