### ISSUE TITLE
Inline tooltips override autocompletions

### ISSUE THREAD

**Issue by nchursin** [SublimeLinter/SublimeLinter3#575]
Almost always when you start typing a code you have some suggestions for autocompletion. Linter's inline tooltips close them, which makes me sad. Could you fix that? 
I think `view.is_auto_complete_visible()` will do the thing

**Comment by jayfunk** [comment]
PR #565 is tracking this issue. It appears to happen with all popups, not just autocompletions.

**Comment by nchursin** [comment]
@jayfunk OK, thanks for the info. Closing this one then.
