### ISSUE TITLE
Inline tooltips show when selecting multi-line code blocks

### ISSUE THREAD

**Issue by notthatnathan** [SublimeLinter/SublimeLinter3#576]
- Click and drag to select multiple lines
- Every line that has an lint issue shows a tooltip

This prevents selection from happening in some cases, as the tooltip blocks the cursor.

Expected: Tip only fires when the cursor is placed on a single line.

**Comment by Cerberus-tm** [comment]
I don't know what version this happened in, but it doesn't seem to happen in the latest version? At least it doesn't happen to me.

**Comment by braver** [comment]
Works-on-my-machine
