### ISSUE TITLE
New linter plugin: nginx-lint

### ISSUE THREAD

**Issue by irvinlim** [SublimeLinter/SublimeLinter3#578]
Linter for nginx `.conf` files using [nginx-lint](https://github.com/temoto/nginx-lint).

https://github.com/irvinlim/SublimeLinter-contrib-nginx-lint

**Comment by irvinlim** [comment]
Done! Thank you :)

**Comment by groteworld** [comment]
Should show up within an hour in Package Control. Thanks Again!

https://github.com/SublimeLinter/package_control_channel/commit/672fd28661eeb013043aa3e5643b58a26a3f5cdd
