### ISSUE TITLE
[setup] WARNING: php deactivated, cannot locate 'php' 

### ISSUE THREAD

**Issue by audiomx** [SublimeLinter/SublimeLinter3#580]
## **SublimeLinter: WARNING: php deactivated, cannot locate 'php'** 

`{
    "default": {
        "debug": false,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "mark_style": "outline",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": ["C:/wamp64/bin/php/php5.6.25/php.exe"]
        },`

**Comment by braver** [comment]
Could you try changing the path setting to point at a directory, not at the exe itself? You might also try adding that to your $PATH.

**Comment by braver** [comment]
🤷‍♂️ We'll re-open if there's news.
