### ISSUE TITLE
Allow PATH option in user settings.

### ISSUE THREAD

**Issue by veelo** [SublimeLinter/SublimeLinter3#586]
I know that linter executables should be in PATH in order for the linter to be enabled. My request is to remove that restriction. I have [implemented a path option](https://github.com/veelo/SublimeLinter-contrib-epcomp/blob/master/linter.py#L46) in the [user settings of my linter](https://github.com/veelo/SublimeLinter-contrib-epcomp#linter-configuration), which almost works. The problem is that SublimeLinter3 does not seem to read that file when it initially tries to enable linters. It works if I go into linter.py and make a change, then SublimeLinter3 reloads the linter, at which point it reads the user settings and the executable is found and properly executed.

So it appears the only thing missing is that SublimeLinter3 should load the user settings before it tries to find the executables when it enables linters.

**Comment by braver** [comment]
I can kinda see how this could get a bit more complicated than it looks on the surface. Do you have a specific use case in mind for this?

**Comment by veelo** [comment]
Yes, the use case is referenced by the two links above in code and documentation respectively. The advantage is that the linter executable (which in my case is a compiler) does not have to be in the system wide PATH which often is already long enough as it is. Secondly, different projects (or even working copies) may want to use different versions of the compiler. It is not a good practise to put comilers in the system PATH, especially when more than one are installed. Therefore it is an advantage to be able to customise the path to the linter executable in the configuration.

What complications do you see in f72603e0486ef031f67e7c49d7dbb14d39ad5810, which implements this?

**Comment by kaste** [comment]
Hi, I think I implemented something similar without needing a patch upstream. For the `flake8` linter I enabled a setting `executable`  

https://github.com/SublimeLinter/SublimeLinter-flake8/blob/adb4890d55acd0c5028ec0685a111b8bd93ae3d7/linter.py#L53-L62


which gets processed in `build_cmd` like so

https://github.com/SublimeLinter/SublimeLinter-flake8/blob/adb4890d55acd0c5028ec0685a111b8bd93ae3d7/linter.py#L91-L100

If this is irrelevant, sorry for the noise.

**Comment by veelo** [comment]
Thanks @kaste for thinking with me. But it doesn't help, sadly. You implement the ``executable`` setting in much the same way as I do. The reason you seem not to need an upstream patch is that you do define ``cmd`` before ``can_lint`` is called, which ``which`` succeeds in finding. That is, ``can_lint`` uses the hard coded ``cmd`` value, whereas linting happens using ``build_cmd`` which uses ``executable`` as given in settings.

I could _cheat_ in the same way by hard coding my ``cmd`` as ``notepad.exe`` just to let ``can_lint`` pass, but that would be a very ugly hack.

PR #587 makes ``can_lint`` read the settings first and use the same executable as is used for the actual linting, to determine whether linting will work or not.

I have tried re-implementing ``can_lint`` to insert that call myself, but I can't seem to call the base implementation from it as it hasn't finished constructing yet. I am a Python noob though, so I might be doing something wrong.

**Comment by kaste** [comment]
When you look at `NodeLinter` they actually implement `can_lint` very optimistic, bc they need to find the correct executable later. And they basically override `context_sensitive_executable_path` which gets called during `build_cmd`. AFAIK `context_sensitive_executable_path` must return `(False, <path>)` for success and `(False, '')` to disable the linter at this late point. 

(Aside: it confuses me that you define `executable` on `cls`; I do it as a setting; bc you actually want late resolving)

My attempt would be:

 - don't use cls.executable
 - define cls.cmd = ('epcomp.exe', '@')
 - implement context_sensitive_executable_path so that it returns the correct path to cmd as late as possible

**Comment by veelo** [comment]
Thank you! I got it working now. What is the purpose of `'@'`? I have left it out. I cannot seem to disable the linter when a non-existent path is configured, neither with `False, ''` nor with `True, None`. But I'm fine with that, the OS supplies a suitable error message.

https://github.com/veelo/SublimeLinter-contrib-epcomp/blob/master/linter.py

**Comment by kaste** [comment]
Yes you're correct. You cannot literally _disable_ the linter at that point anymore, but it will/should stop the linting attempt when you return `True, None` and print an error. Something like _cannot locate..._

The `@` is just a mistake, I meant `*`, which would fill in the linter settings as args automatically. So if you do `cmd = ('epcomp.exe', '-y', '*')` you should get the `-y` you later fill in manually. All the other options https://github.com/veelo/SublimeLinter-contrib-epcomp/blob/2cbc3baaf99e33ee96696b16cd041e6f5c9a7a83/linter.py#L100-L102 could be actually settings like I've shown here https://github.com/SublimeLinter/SublimeLinter-flake8/blob/adb4890d55acd0c5028ec0685a111b8bd93ae3d7/linter.py#L53-L62 and these will be transformed to your args. This is explained here http://sublimelinter.readthedocs.io/en/latest/linter_attributes.html#defaults   

The result would be that you don't have to override `build_cmd` at all.

**Comment by veelo** [comment]
Thanks a lot for all your help! I'll incorporate the points above in a later release.
