### ISSUE TITLE
New linter plugin: SublimeLinter-contrib-serplint

### ISSUE THREAD

**Issue by beaugunderson** [SublimeLinter/SublimeLinter3#590]
This adds a linter definition for the `serplint` linter, which lints the `Serpent` language for creating Ethereum contracts.

Here's the [pull request](https://github.com/SublimeLinter/package_control_channel/pull/41). ✨

Here it is in action:

![screenshots](http://i.imgur.com/KYXNBMh.png)

**Comment by groteworld** [comment]
Hello,

Please consider updating these parts of the repo before I merge package control PR

* In [README Settings](https://github.com/beaugunderson/SublimeLinter-contrib-serplint#settings), please consider removing the example settings.
* Connect the TravisCI build server to your project so badge shows a successful build
* Add a repository description at the top, see [SublimeLinter/SublimeLinter-jshint](https://github.com/SublimeLinter/SublimeLinter-jshint) for example

**Comment by beaugunderson** [comment]
@groteworld all done, thanks!

**Comment by groteworld** [comment]
Should show up within an hour in Package Control. Thanks Again!
