### ISSUE TITLE
New linter: SublimeLinter-contrib-yaml-lint

### ISSUE THREAD

**Issue by witsec** [SublimeLinter/SublimeLinter3#593]
https://github.com/witsec/SublimeLinter-contrib-yaml-lint

This linter provides an interface for the [yaml-lint](https://rubygems.org/gems/yaml-lint/) Ruby gem.

**Comment by witsec** [comment]
Is there anything else I should do at this point?

**Comment by groteworld** [comment]
Sorry got this during the holidays and lost track of it. Thanks for the nudge!

Should show up within an hour in Package Control. Thanks Again! https://github.com/SublimeLinter/package_control_channel/commit/e33cb561919eb1cb48c4424de92fa7201adf023e
