### ISSUE TITLE
New linter: SublimeLinter-contrib-cookstyle

### ISSUE THREAD

**Issue by jeffbyrnes** [SublimeLinter/SublimeLinter3#598]
https://github.com/jeffbyrnes/SublimeLinter-contrib-cookstyle

This linter modifies `SublimeLinter-rubocop` to work with `cookstyle`, a Chef-centric wrapper for rubocop.

**Comment by groteworld** [comment]
you should consider removing the SL-rubocop release tags from this project. The following is the easiest way to accomplish this.

```
# From the project directory

#Delete local tags.
git tag -d $(git tag -l)

#Fetch remote tags.
git fetch

#Delete remote tags.
git push origin --delete $(git tag -l)

#Delete local tags.
git tag -d $(git tag -l)
```

After that, please fix your TravisCI badge and make your own release and we will be good to go!

**Comment by jeffbyrnes** [comment]
Ah, right, good call! Will do.

**Comment by jeffbyrnes** [comment]
[`SublimeLinter-contrib-cookstyle` v1.0.0](https://github.com/jeffbyrnes/SublimeLinter-contrib-cookstyle/releases/tag/v1.0.0) released!

**Comment by groteworld** [comment]
Sorry for the wait! Should show up within an hour in Package Control. Thanks Again!
https://github.com/SublimeLinter/package_control_channel/commit/43ce1c9c9eb61058e75c01c4eb8f0ea05389d193
