### ISSUE TITLE
@python meta setting is not allowed to be a float

### ISSUE THREAD

**Issue by flekschas** [SublimeLinter/SublimeLinter3#599]
The documentation for the project-based python setting says:

> The @python meta setting is a **floating point number** that specifies the python version that should be used when running python-based linters.

URL: https://sublimelinter.readthedocs.io/en/latest/meta_settings.html#python

I noticed when actually setting a floating point number SublimeLinter complains that only strings, ints, and bytes are allowed:

```
TypeError: argument should be string, bytes or integer, not float
```

Is this a typo in the docs or am I misinterpreting it?

**Comment by brutus** [comment]
See also https://github.com/SublimeLinter/SublimeLinter3/issues/592

**Comment by braver** [comment]
Closing this in favour of #592
