### ISSUE TITLE
New linter: SublimeLinter-contrib-clang-tidy

### ISSUE THREAD

**Issue by rwols** [SublimeLinter/SublimeLinter3#602]
https://github.com/rwols/SublimeLinter-contrib-clang-tidy

provides an interface to [clang-tidy](http://clang.llvm.org/extra/clang-tidy/)

**Comment by groteworld** [comment]
It was perfect, I'm sorry it took me so long to upload

https://github.com/SublimeLinter/package_control_channel/commit/60ad240947727d06901909b220abbc1452cc78e1
Should show up within an hour in Package Control. Thanks Again!
