### ISSUE TITLE
New linter: SublimeLinter-contrib-credo

### ISSUE THREAD

**Issue by markalfred** [SublimeLinter/SublimeLinter3#604]
(not my package, but trying to help it move forward)

https://github.com/mintcore/SublimeLinter-contrib-credo

Adds interface to [Elixir's Credo](https://github.com/rrrene/credo) static analysis tool.

**Comment by groteworld** [comment]
There seems to be some [issue](https://github.com/mintcore/SublimeLinter-contrib-credo/issues/1) with this linter actually running. I really feel like this is breaking, also from readme the user has no idea how they should download `credo`. Once these have been resolved, please feel free to open this issue again or create a new one.

I look forward to it and my apologies for being slow to respond.
