### ISSUE TITLE
New linter: SublimeLinter-contrib-vale

### ISSUE THREAD

**Issue by admhlt** [SublimeLinter/SublimeLinter3#605]
https://github.com/admhlt/SublimeLinter-contrib-vale

I've created a linter to interface with [Vale](https://valelint.github.io/docs/), a linter for content and prose. It's been working pretty well for me locally but it would be good to get some more eyes on it.

**Comment by groteworld** [comment]
Sorry for the slow response!

Everything seems to be in order, please make a [release](https://github.com/admhlt/SublimeLinter-contrib-vale/releases) and I'll get it into package control.

**Comment by admhlt** [comment]
Now it's my turn to apologize 😅 

I've pushed a `v1.0.0` release, so everything should be good!

**Comment by groteworld** [comment]
https://github.com/SublimeLinter/package_control_channel/pull/49 Thanks again and welcome to the SL family! 😉
