### ISSUE TITLE
Allow Highlight Styling of Individual Warnings/Errors

### ISSUE THREAD

**Issue by pykong** [SublimeLinter/SublimeLinter3#609]
I like to be able to define individual highlighting styles for individual warnings/errors.

Taking python as an example, I like to have individual highlighting for warnings from MyPy.
Such type warnings represent their own class and hence it would be highly useful to visually differentiate them from formatting or other warnings types.

A different appearance could be achieved by defining a custom color and highlighting style.
Also whether a symbol in the Gutter is shown or not and if Sublime's capabilities allow it which one to display in the first place could be important for discerning different warnings/errors.

**Comment by FichteFoll** [comment]
Would also be useful to mark TODO comments in a different style and color, e.g. blue.

**Comment by braver** [comment]
@FichteFoll #666 will allow each linter to have its own color. So I guess it will depend on what’s highlighting your todo’s (I don’t have experience with that myself).

**Comment by FichteFoll** [comment]
Sounds nice. I was catching something that seemed related in #665 (or maybe it was #666), but the PRs have grown so much that I just couldn't bother going through the actual details. Instead, I made a related comment on the related issue and am glad to here that something like this is indeed being considered.

**Comment by braver** [comment]
Sure, it's going to be a pretty big update. What it entails I'll document later. In any case, if you're using Sublime​Linter-annotations to highlight TODO's etc, what you're proposing will be supported.
