### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter3#613]
This repository looks to be pretty dead? I'd love to see some action on the PR's and would definitely volunteer to clean up some of the issues and get it back on track a bit. 

Please also consider transferring to the Sublime Text group to get some more eyes on this and ensure its survival.

cc @groteworld

**Comment by groteworld** [comment]
Hi @braver 
yes this project is still maintained... just poorly 😉

We could *really* use some help troubleshooting issues, identifying feature request issues, and closing out dead issues. If you're interested, I'd love to get you access to SL3 to handle some issues. If you would like to make code changes though, I do request that you submit them through PR, until everyone is comfortable.

I'll find some time this morning to handle the new linter requests and punch out a couple PRs.

**Comment by braver** [comment]
@groteworld I don't expect to be committing code to this anytime soon. I'm not terrible at it, but mostly a UI/UX engineer and this thing hardly has any (or issues with it). I use the hell out of it though, so if me closing issues, responding to requests, checking reproducibility, etc. helps keep this thing on the road I'm definitely up for it.

**Comment by groteworld** [comment]
Check your permissions by closing this issue. Otherwise let me know if you can't

**Comment by braver** [comment]
@groteworld I can close this one because I opened it. I don't seem to be able to affect other issues though.

**Comment by groteworld** [comment]
Oh, duh! Ok try again.

**Comment by braver** [comment]
Jup, awesome. Thanks!

**Comment by groteworld** [comment]
🍻 Cheers!
