### ISSUE TITLE
Improve status bar messages

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter3#618]
- split into **count** and **message**
- disable either part
- also display **count** when zero
- configurable template for **count**

Example:

`Errors: 0, Warnings: 1, this is a linter error message `

Or

`e:1 w:2, this is a linter error message`

Consolidates issues #563, #542, #338, #324, #523

**Comment by pykong** [comment]
Assign that to me. Consider it done.

**Comment by braver** [comment]
Looking forward to the PR! GitGutter does this really well IMO, that's what I had in mind.

**Comment by pykong** [comment]
Thanks for the tip. I have a look into GitGutter.
I am going to start working on this issue once my other update has been successfully merged.

**Comment by pykong** [comment]
@braver Put the assign label on me.

**Comment by braver** [comment]
Can’t seem to do that, but it’s all yours!
