### ISSUE TITLE
Embedded Syntax Linting Not Working (js/css in html)

### ISSUE THREAD

**Issue by timkelty** [SublimeLinter/SublimeLinter3#622]
I have https://github.com/roadhump/SublimeLinter-eslint and  https://github.com/kungfusheep/SublimeLinter-contrib-stylelint working fine for js and css files.

However, I get no linting at all with embedded syntaxes, such as an html file with `script` or `style` tags.

SublimLinter 3.8.0+1

Here's my debug log when linting an HTML view with script and style tags:
```
SublimeLinter: twiglint output:
OK in /var/folders/fz/_qwtvm8j3357rhyq8zk0cvlh0000gn/T/SublimeLinter3-timkelty/text.html 
SublimeLinter: phpcs: text.html ['/Users/timkelty/.composer/vendor/bin/phpcs', '--report=checkstyle', '--standard=PSR2'] 
SublimeLinter: phpcs output:
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="3.0.2">
</checkstyle> 
SublimeLinter: eslint: text.html ['/Users/timkelty/Sites/coaster-2017/node_modules/.bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
```

**Comment by timkelty** [comment]
Note: I discovered the eslint and stylint both are working in .vue files, which also use embedded script/style tags.

So, it may be something specific with HTML?

The docs state that you include "fixed" syntaxes for html: http://www.sublimelinter.com/en/latest/usage.html?highlight=embedded#customized-syntax-definitions

But I noticed those don't seem to be in the repo any more - is that still true?

**Comment by braver** [comment]
@timkelty eslint in an HTML file works fine on my end. Your debug log also doesn't really tell me enough to figure out what's wrong (if anything). Could you share an example of a file where the embedded syntax isn't being linted?

**Comment by timkelty** [comment]
Here's a demo: https://github.com/timkelty/sublime-linter-demo

For me, I get no errors on the html file (should at least get "foo not defined")

I've tried it with and without the `eslint-plugin-html` plugin.

FWIW - at some random point when putting the demo together, my html file started linting my script tag. Then it stopped, and I couldn't get it back!

**Comment by timkelty** [comment]
I think I was battling a couple different variables:

1. I was using SublimeLinter-contrib-eslint_d (for speed), not SublimeLinter-contrib-eslint.
2. Using eslint-plugin-html seems disable all linting from html files. If I remove it (and am using eslint, not eslint_d), it works.

**Comment by braver** [comment]
The docs may say SL installs custom syntaxes but that [hasn't been true for a while](https://github.com/SublimeLinter/SublimeLinter3/commit/d98ea8c3ddee58286b3322129c232f9c7f905572). The joys of documenting code 🙄 

It seems your problem lies with `SublimeLinter-contrib-eslint_d` then. Best check in that repo for more info.

**Comment by timkelty** [comment]
Yep, I'll open an issue there.

It does seem however, that there issue if you are using `eslint-plugin-html`, even with SublimeLinter-eslint.

In this case, I'm using that plugin in my build/test process, not just in my editor, so I can't simply remove it.

Do you think this is an issue for SublimeLinter or SublimeLinter-eslint? It seems maybe that SublimeLinter-eslint needs to detect if you're using `eslint-plugin-html` and if so bail on the embedded script extraction routines?

**Comment by braver** [comment]
Sounds like something SL-eslint should deal with, not something SL itself would be involved in. In general this isn’t the best place to debug issues with specific linters, but of course if the issue is found to lie here you’re very welcome to open an issue with your findings.

**Comment by timkelty** [comment]
Thanks for your help - I'll open an issue over there.
