### ISSUE TITLE
SublimeLinter plugin for Elixir with credo

### ISSUE THREAD

**Issue by ocolot** [SublimeLinter/SublimeLinter3#628]
Hi there, 

Here is the link to repo I (quickly) created to use the great project credo for Elixir: https://github.com/ocolot/SublimeLinter-contrib-credo

I'd be glad to help others go faster though this process, if you find it good enough to publish it.

**Comment by groteworld** [comment]
Please make a release and I'll put it in Package Control. Thanks!

**Comment by groteworld** [comment]
Ok there is a PR waiting for this once a release has been made

**Comment by ocolot** [comment]
OK, great. I just created the tag 1.0.0 on the repo. Is this what you need?

**Comment by groteworld** [comment]
yup thanks!
