### ISSUE TITLE
Add linter for Markdown/CommonMark files (markdownlint)

### ISSUE THREAD

**Issue by jonlabelle** [SublimeLinter/SublimeLinter3#629]
Sublime Text linter for Markdown/CommonMark files. This linter wraps the node.js NPM package [Markdownlint](https://github.com/DavidAnson/markdownlint).

- **Repository:** <https://github.com/jonlabelle/SublimeLinter-contrib-markdownlint>
- **Tag:** <https://github.com/jonlabelle/SublimeLinter-contrib-markdownlint/tree/1.0.0>
- **SublimeLinter Package Control Pull Request:** <https://github.com/SublimeLinter/package_control_channel/pull/45>

Thanks
Jon L.

**Comment by groteworld** [comment]
Should show up within an hour in Package Control. Thanks Again!

https://github.com/SublimeLinter/package_control_channel/pull/45
