### ISSUE TITLE
[setup] Linter not working with pyflakes

### ISSUE THREAD

**Issue by michK** [SublimeLinter/SublimeLinter3#632]
I am running Ubuntu 14.04 with Sublime Text 3, SublimeLinter and pyflakes.

The linter doesn't work and when running in debug mode and restarting ST, among many other things, the following is printed in the console:

```
Traceback (most recent call last):
  File "/home/user/.config/sublime-text-3/Packages/SublimeLinter/lint/util.py", line 247, in generate_color_scheme_async
    scheme_text = sublime.load_resource(scheme)
  File "/opt/sublime_text_3/sublime.py", line 192, in load_resource
SublimeLinter: pyflakes: main.py <builtin> 
    raise IOError("resource not found")
OSError: resource not found
```

**Comment by braver** [comment]
Seems to work just fine here. Have you followed all the setup steps and looked in the SublimeLinter-pyflakes repo for more info and perhaps known issues that may be related to your setup?

**Comment by michK** [comment]
I followed [these](http://www.sublimelinter.com/en/latest/installation.html) instructions under **Installing via Package Control** for SublimeLinter, did `pip install pyflakes` and then installed pyflakes using [these](Plugin installation) instructions under **Plugin Installation**. So I think I installed it correctly.

I will check out the pyflakes repo now.

**Comment by braver** [comment]
@michK Did you also install https://packagecontrol.io/packages/SublimeLinter-pyflakes?

**Comment by michK** [comment]
@braver yes I did, but I notice now that I might not have set up the path to the linter executable properly. Will try to do that and report back.

**Comment by michK** [comment]
I noticed now that linter 'kind of' works.

In ST it seems to show errors and I can navigate through the errors, but it is not noticing #TODO, not sure if that is related to the error I quoted in the first message.

By the way, do you by any chance know where the linter executable is stored on a Linux system?

**Comment by braver** [comment]
@michK I wouldn't really know enough about Linux to tell you that. What does `which pyflakes` tell you?

**Comment by michK** [comment]
`which pyflakes` returns `/home/user/anaconda3/bin/pyflakes`, but `which linter` returns nothing, which is why I think the linter executable is the problem, although it's weird that it seems to 'kind of' work.

**Comment by braver** [comment]
Well, there is no `linter` program (related to this anyway), so I wouldn't expect that to return anything.

So, you're now just having an issue with `#TODO` not lighting up? That sounds more like a linter configuration thing. If you want help setting it up, I can recommend the Sublime Text forums or the Discord channel: lot's of python devs that can help you out. https://forum.sublimetext.com/t/sublime-text-discord-server/26063

**Comment by michK** [comment]
Have a look [here](http://www.sublimelinter.com/en/latest/troubleshooting.html) under **Finding a linter excecutable**, it says there should exist a program `linter`.

Thank you for the reference, will check it out.

**Comment by braver** [comment]
Yeah you kinda missed this part:

> replacing linter with the linter executable name

☺️

**Comment by michK** [comment]
🙃 Oops.

Ok, so it seems my issue is more related to the configuration.

Thanks for the help.
