### ISSUE TITLE
SublimeLinter plugin for Solidity

### ISSUE THREAD

**Issue by idrabenia** [SublimeLinter/SublimeLinter3#634]
**Description**: Sublime Text linter for Solidity files. It provides both security, style guide and best practice validation rules.

**Repository**: https://github.com/idrabenia/SublimeLinter-contrib-solhint

**Release**: https://github.com/idrabenia/SublimeLinter-contrib-solhint/releases/tag/v1.0.1

**Pull Request**: https://github.com/SublimeLinter/package_control_channel/pull/46

**Comment by groteworld** [comment]
Your PR has been merged!
Should show up within an hour in Package Control. Thanks Again!
