### ISSUE TITLE
New linter: SublimeLinter-contrib-iscc

### ISSUE THREAD

**Issue by idleberg** [SublimeLinter/SublimeLinter3#635]
I've released [SublimeLinter-contrib-iscc](https://github.com/idleberg/SublimeLinter-contrib-iscc) and submitted a [pull-request](https://github.com/SublimeLinter/package_control_channel/pull/43) a couple of weeks ago. I've only noticed this is the repository to announce new linters.

**Comment by groteworld** [comment]
Should this be marked in Package Control as a windows only plugin? Otherwise looks good, Thanks!

**Comment by groteworld** [comment]
has been merged thanks
