### ISSUE TITLE
New linter: SublimeLinter-contrib-yamllint

### ISSUE THREAD

**Issue by thomasmeeus** [SublimeLinter/SublimeLinter3#644]
Hi!
This is my first SublimeLinter plugin. It will use the [Python yamllint](https://github.com/adrienverge/yamllint) tool to extensively validate yaml-files. Some features over other yaml-linters:
- detects duplicate keys
- detects faulty use of whitespaces & indentation
- detects trailing whitespaces

For me it's very helpful when writing Puppet Hiera code. 
The plugin can be found here: https://github.com/thomasmeeus/SublimeLinter-contrib-yamllint. I tested in on ST3/OSX. Remarks are welcome, I hope it gets approved.

Thanks!

**Comment by groteworld** [comment]
Everything looked great!

Thanks for your contribution! 🍻
