### ISSUE TITLE
Too many superfluous console messages

### ISSUE THREAD

**Issue by gerardroche** [SublimeLinter/SublimeLinter3#645]
During startup SublimeLinter prints messages about loading linters. These should really only be printed if debug mode is enabled. Here is sample of the messages:

```
reloading plugin ...
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin SublimeLinter-flake8.linter
SublimeLinter: flake8 linter loaded 
reloading plugin SublimeLinter-php.linter
SublimeLinter: php linter loaded 
reloading plugin ...
```

The `SublimeLinter: flake8 linter loaded` and `SublimeLinter: php linter loaded` messages are redundant. ST is already telling us that those plugins are reloaded. If there is some value in those messages then they can be reserved for debug mode.

When the plugins are finished loading SublimeLinter prints:

```
SublimeLinter: debug mode: off 
```

This message can be omitted. Print it only if debug mode is enabled.

**Comment by groteworld** [comment]
I understand you want to make your startup console look not as busy, but it's going to be hard when you have this off the bat... 😉 
```
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
```

The "redundant" `SublimeLinter: flake8 linter loaded` is each linter stating a one time "I'm here and connected to the master plugin" message which is beneficial outside of full debugging. 

Lastly, the one I can agree with the most to remove, `SublimeLinter: debug mode: off` does seem silly, but you'd be surprised after years that when we ask for debug console pastes, that people will post this, with it blaring in their face that debug is `off`.

I'm sorry that it seems like a lot, but SublimeLinter is a beast, that needs to load many different, independent wheels. It's overall best to sometimes use the 'info' log level and be able to see that in the default console, leaving just the nitty gritty to the debug.

**Comment by gerardroche** [comment]
Those messages you posted are well formed. I don't think user laziness or stupidity is good reason to print the debug mode message, nor do I think the redundant messages are valuable outside debugging, wontfix is annoying, but whatever.

**Comment by groteworld** [comment]
I'm sorry, it's not meant to offend. This is a disagreement of opinion. Neither party can be fully right here. As the administrator to this stream of SublimeLinter, I have the choice to accept suggestion, but in this case, I believe the project itself is better rejecting it. If you have a need for this suggestion, then please feel free to fork SL for your own use and pull down changes that happen from the main stream. This is the beauty of open source and git.

As for the `wontfix` label, this is also not meant in a cruel or malicious way. It is simply a standard label that allow myself, maintainers, and our future selves to be able to quickly find features that were earlier passed on that may now fall into scope of the project.

**Comment by groteworld** [comment]
After looking around and consulting https://github.com/SublimeText/PackageDev/issues/134

Here is a compromise: https://github.com/SublimeLinter/SublimeLinter3/commit/6278e30747ee1b96717fd4029ce6e130d7bbab83

Thanks for your help.

**Comment by gerardroche** [comment]
I'm not offended. It takes a lot to offend me.

That change is not a compromise (at least in terms of the debug mode message), it's precisely what I wanted. 

Do the same with the other two messages.

There are also other messages. Those are not the only ones. For example when linter is activated it's prints a messages(this message seems to occur when you first open a python file) :

```
SublimeLinter: flake8 activated: /usr/bin/flake8 
```

**Comment by groteworld** [comment]
It’s a compromise to the effect that this is all I am willing to do right now towards the issue. 

Thanks again!
