### ISSUE TITLE
error_color not changing

### ISSUE THREAD

**Issue by jtlapp** [SublimeLinter/SublimeLinter3#647]
I thought I followed the docs, but I'm not getting any change. I just want to set a new error_color.

I opened the user settings via the Preferences menu and changed:
```
"error_color": "D02000",
```

to (for example):
```
"error_color": "ffffff",
```

Saving the user settings file and confirming that colors should be updated doesn't help. Closing and reopening Sublime doesn't help. Clearing the color scheme folder and reopening Sublime doesn't help. Using all-uppercase or all-lowercase hex doesn't help. Prefixing `#` doesn't help.

What should I be doing? Thanks for your help!

I'm using SublimeLinter v3.10.1 with Sublime 3.0 build 3143 on macOS 10.12.6.

(To be clear, the user settings file does indeed reflect my edits, and those edits survive reopening Sublime.)

**Comment by jtlapp** [comment]
It's also not using the error color that the Beehave color scheme provides.

Changing it in the default settings file also had no effect.

I must really misunderstand how this works, unless there's a bug.

**Comment by jtlapp** [comment]
I examined the color of the error message and found pixels at `#FF0000`. The defaults have it at `D02000`. I set it to something else. Is this not the error message whose color we're selecting?

<img width="308" alt="screen shot 2017-10-28 at 8 55 03 am" src="https://user-images.githubusercontent.com/138133/32135051-25cdb6d4-bbbe-11e7-9b8d-c4fbab4e822d.png">

Checking the [Behave theme](https://github.com/fnky/behave-theme/blob/master/Behave.tmTheme), it sets the error color to `EF4D44`, but again it renders `FF0000`.

**Comment by braver** [comment]
It seems you expect colors in the tooltips. The colors you set are only used for the inline highlighting, e.g. the underlines or outlines of errors in your code.

**Comment by jtlapp** [comment]
Drats. My eyes are having trouble reading the red text in the tooltip. Is there a way to change that? Should that be a feature request? Thanks!

**Comment by braver** [comment]
Hmmm, didn't think there were colors in the default tooltip theme. You might check that, and it can also be customised. We're already working on replacing the entire thing: #666
