### ISSUE TITLE
SublimeLinter-contrib-dmd new contribution

### ISSUE THREAD

**Issue by veelo** [SublimeLinter/SublimeLinter3#657]
Hi!

SublimeLinter-contrib-dmd uses the dmd reference compiler for the D programming language to show errors and warnings in D source code.

Please consider https://github.com/veelo/SublimeLinter-contrib-dmd for inclusion in Package Control.

Thanks,
Bastiaan.

**Comment by groteworld** [comment]
Please make a release and I'll put it in Package Control. Thanks!

**Comment by veelo** [comment]
Wow you're fast this time! Done.

**Comment by groteworld** [comment]
Depends on the positioning of the stars. 🌠 😉

**Comment by groteworld** [comment]
Should show up within an hour in Package Control. Thanks Again!

**Comment by veelo** [comment]
Thanks a lot!
