### ISSUE TITLE
SublimeLinter needs to support the new sublime-color-scheme format

### ISSUE THREAD

**Issue by aziz** [SublimeLinter/SublimeLinter3#658]
Sublime introduced a new color scheme format in json that I've started to use, but now sublime linter is throwing this error during the start up since it can not parse the json format 

```
  File "/Users/allen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/util.py", line 264, in generate_color_scheme_async
    plist = ElementTree.XML(scheme_text)
  File "./python3.3/xml/etree/ElementTree.py", line 1356, in XM
```

**Comment by groteworld** [comment]
Thanks for making an issue for this! We currently have a fix that is coming for this and hope to have it ready for release soon.

**Comment by pykong** [comment]
See #639

**Comment by groteworld** [comment]
Oh seems to be duplicate, I'll close this one then.
