### ISSUE TITLE
Improved goto next/previous error

### ISSUE THREAD

**Issue by gerardroche** [SublimeLinter/SublimeLinter3#659]
It would be great if the `sublimelinter_goto_error` command accept a `count` and `wrap` options. A `count` meaning jump to the nth change, and `wrap` (a boolean) that enabls and disables wrapping of errors i.e. the `wrap_find` setting.

Ultimately the new API would allow (where count defaults to 1 and wrap defaults to whatever the global setting git_gutter_next_prev_change_wrap is.

```
self.view.run_command('sublimelinter_goto_error', {'direction': 'next', 'count': 1, 'wrap': None})
self.view.run_command('sublimelinter_goto_error', {'direction': 'previous', 'count': 1, 'wrap': None})
```

*`wrap` set to `None` meaning default to the global `wrap_find` setting.*

# Reason

[NeoVintageous](https://github.com/NeoVintageous/NeoVintageous) provides Sublime Linter support for jumping forward and backwards through errors.

From the documentation:

Command | Description | Documentation | Dependency
------- | ----------- | ------------- | ----------
`[l` | Jump to `[count]` next error. | [unimpaired.vim](https://github.com/tpope/vim-unimpaired/blob/master/doc/unimpaired.txt) | [SublimeLinter](https://github.com/SublimeLinter/SublimeLinter3)
`]l` | Jump to `[count]` previous error.. | [unimpaired.vim](https://github.com/tpope/vim-unimpaired/blob/master/doc/unimpaired.txt) | [SublimeLinter](https://github.com/SublimeLinter/SublimeLinter3)

The commands allow you to jump to the next or prev change with `]l` and `[l`. 

The [relevant code](https://github.com/NeoVintageous/NeoVintageous/blob/7de75c46ba907a1b1c4a304415d1bb754683f617/lib/extras/unimpaired.py#L154) looks like this:

```
def _context_previous(view, count):
    for i in range(count):
        view.run_command('sublimelinter_goto_error', {
            'direction': 'previous'
        })


def _context_next(view, count):
    for i in range(count):
        view.run_command('sublimelinter_goto_error', {
            'direction': 'next'
})
```

The counts work by prefixing the commands with a number e.g. `3]l` jumps to the 3rd change from the cursor.

An issue when using counts is that wrapping the results is confusing e.g. imagine your at the 3rd last change and you hit `4]l`, if it wraps you don't know where you are in the document. Ideally you want it to stop at the end and display a status message.

You can disable wrapping via `find_wrap`, but that's a global setting and the user may not want to disable that globally. So an optional wrap argument to the commands would be useful.

Another issue is that SublimeLinter visually selects the error. In Vim emulation we don't don't want to enter visual mode, but if we try to clear the visual selection and try to jump again SL selects the current error again. It would be nice to also have an option not to visually select the error but rather just jump to the begin point of the error:

```
self.view.run_command('sublimelinter_goto_error', {'direction': 'next', 'count': 1, 'wrap': None, 'select': True})
self.view.run_command('sublimelinter_goto_error', {'direction': 'previous', 'count': 1, 'wrap': None, 'select': True})
```

The fact that if you clear the selection after a jump and try jump again is kind of a bug.

A similar API was implemented in GitGutter: https://github.com/jisaacks/GitGutter/issues/458

**Comment by FichteFoll** [comment]
SL uses the built-in find results navigation now.

**Comment by braver** [comment]
Indeed, SL4 renders this “won’t fix”
