### ISSUE TITLE
Please review Dockerfile linter plugin

### ISSUE THREAD

**Issue by prog1dev** [SublimeLinter/SublimeLinter3#667]
Hey guys!
[Here](https://github.com/prog1dev/SublimeLinter-contrib-dockerfilelint) is a plugin i wrote for linting `Dockerfile` with [dockerfilelint](https://www.npmjs.com/package/dockerfilelint) linter. 
Please review it for correctness and completeness.

**Comment by groteworld** [comment]
LGTM! Please make a release and I'll put it in Package Control. Thanks!

**Comment by prog1dev** [comment]
Done

**Comment by prog1dev** [comment]
@groteworld Done

**Comment by prog1dev** [comment]
cc @groteworld

**Comment by braver** [comment]
@prog1dev if you open a PR at https://github.com/SublimeLinter/package_control_channel I'll pull it

**Comment by prog1dev** [comment]
Done https://github.com/SublimeLinter/package_control_channel/pull/52

**Comment by prog1dev** [comment]
So how long does it take to register in Package Control? 
Thanks!

**Comment by braver** [comment]
I have no clue actually, I believe it’s a cronjob that runs a couple of times per hour

**Comment by groteworld** [comment]
It's something that happens on Package Controls side. It's typically fair to say any releases get seen by PC within an hour. Sorry for dropping the ball on this issue!
