### ISSUE TITLE
New linter contribution: php-ci-fixer 

### ISSUE THREAD

**Issue by jhoff** [SublimeLinter/SublimeLinter3#668]
https://github.com/jhoff/SublimeLinter-contrib-php-cs-fixer

php-cs-fixer is a great tool for finding and automatically fixing issues with php. This linter will highlight lines that would normally be changed automatically.

Thanks

**Comment by braver** [comment]
@jhoff Please make a release (1.0.0 or somesuch). You're also very welcome to make my work a bit easier and open a PR over at https://github.com/SublimeLinter/package_control_channel.

**Comment by jhoff** [comment]
@braver Tagged and Submitted a PR. Thanks.
