### ISSUE TITLE
(SublimeLinter3-next with Sublime​Linter-contrib-eslint and Sublime​Linter-jshint) Exception "SublimeLinter: error in SublimeLinter daemon" when opening any .js file

### ISSUE THREAD

**Issue by darkred** [SublimeLinter/SublimeLinter3#671]
Continuance from https://github.com/SublimeLinter/SublimeLinter3/pull/666#issuecomment-347706188 as per https://github.com/SublimeLinter/SublimeLinter3/pull/666#issuecomment-347790210

Note: I don't have this problem on the regular release of SublimeLinter.

STR:   
- _(Using ST3 3154 x64 (clean installation))_
- I download the ZIP for [this commit](https://github.com/SublimeLinter/SublimeLinter3/commit/667acf80d34616c136c96644a25b5899ba4b1436) or the [latest one](https://github.com/SublimeLinter/SublimeLinter3/commit/bf679bc6eeb439dfbad60925bd90ad6d263d7f64), 
Inside the resulting `SublimeLinter3-next.zip` there's a folder `SublimeLinter3-next` with the content. 
So, I copy it as `SublimeLinter` into `C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages`
- I open: Preferences | Package Settings | SublimeLinter  -> Settings
and I add to the right  panel (User) an empty JSON `{}`.
-  Then, as I restart ST, I get no errors in console.
-  Then i install Sublime​Linter-contrib-eslint 1.10.0 and Sublime​Linter-jshint 1.3.0 (both via Package Control) and restart ST: initially, still no errors in console.
- But, when opening a .js file (having either of them only enabled each time) 
I get the following exception: (this is while using the ZIP [from the former commit](https://github.com/SublimeLinter/SublimeLinter3/commit/667acf80d34616c136c96644a25b5899ba4b1436))

```
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublime_linter.py", line 263, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 1008, in lint_view
    callback(cls.get_view(vid), linters, hit_time)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublime_linter.py", line 316, in highlight
    highlights.draw(other_view)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\highlight.py", line 133, in draw
    all.draw(view)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\highlight.py", line 477, in draw
    icon = self.get_style("icon", style, error_type)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\highlight.py", line 184, in wrapper
    return persist.gutter_marks["icons"][error_type]
KeyError: 'warning'
 
SublimeLinter: -------------------- 
```

**Comment by braver** [comment]
Well, my settings are just this:

```json
{
    "linters": {
        "eslint": {}
    }, 
    "styles": [
        {
            "icon": "warning", 
            "mark_style": "squiggly_underline", 
            "priority": 1, 
            "scope": "region.yellowish", 
            "types": [
                "warning"
            ]
        }, 
        {
            "icon": "error", 
            "mark_style": "squiggly_underline", 
            "priority": 1, 
            "scope": "region.redish", 
            "types": [
                "error"
            ]
        }
    ]
}
```

... so that can't be it. I'm on a Mac though, so our setup is going to be pretty different other than perhaps the Sublime Text configuration.

Are you able to pass a .js file through eslint on the command line and get some feedback?

**Comment by darkred** [comment]
> Are you able to pass a .js file through eslint on the command line and get some feedback?

Yes, eslint via command line completes ok ([example screenshot](https://user-images.githubusercontent.com/723651/33396140-53a408aa-d550-11e7-8bba-1a8c3c8cbd13.jpg))

I use a global `.eslintrc.js` file  (in C:\Users\Kostas), the following : 

```json
module.exports = {
    "env": {
        "browser": true,
        "greasemonkey": true,
        "jquery": true,
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaVersion": 8,
        "sourceType": "script",
        "ecmaFeatures": {
            "globalReturn ": true,
            "impliedStrict": true,
        }
    },
    "rules": {
        "eqeqeq": "warn",
        "func-style": "off",
        "indent": ["warn","tab"],
        "linebreak-style": ["warn","unix"],
        "max-len": "off",
        "max-statements-per-line": "off",
        "new-cap": "off",
        "no-extra-semi": "warn",
        "no-inline-comments": "off",
        "no-magic-numbers": "off",
        "no-mixed-spaces-and-tabs": "warn",
        "no-multiple-empty-lines": "off",
        "no-console": "warn",
        "no-alert": "warn",
        "no-unused-labels": "warn",
        "no-unused-vars": ["warn", {"vars": "all", "args": "after-used"}],
        "no-useless-escape": "warn",
        "no-tabs": "off",
        "padded-blocks": "off",
        "quotes": ["warn", "single", { "allowTemplateLiterals": true }] ,
        "require-jsdoc": "off",
        "semi": ["warn","always"],
        "space-before-function-paren": "off",
        "unicode-bom": ["warn", "never"]

    }
};
```

**Comment by darkred** [comment]
And, @braver, if it wasn't clear, I've tried your settings, and the issue still occurs.

**Comment by pykong** [comment]
@darkred @braver This issue is not linter specific. 
Likely it is a minor logic bug in the icon fetcher.
```
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\highlight.py", line 184, in wrapper
    return persist.gutter_marks["icons"][error_type]
```
I am going to have a look into this. and hope to have it fixed by the weekend.

**Comment by pykong** [comment]
I can not reproduce that error any more on the most recent build.
The underlying code has undergone a major revision in the meantime.
I am closing this issue so far.

@darkred 
Our beta will be out soon.
If you still encounter that bug with the beta version, feel free to reopen it.
