### ISSUE TITLE
Inline settings not working

### ISSUE THREAD

**Issue by MarvinTeichmann** [SublimeLinter/SublimeLinter3#679]
I am trying to use [inline settings](http://sublimelinter.readthedocs.io/en/latest/settings.html#inline-overrides) to configure sublimelinter for a specific file. Unfortunately those settings are ignored in the newest SublimeLinter version.

Here a minimal example with debug output:

```
# [SublimeLinter flake8-ignore:+W391 flake8-max-line-length:120]


def myfunction():
    while(True):
        "This is a very long line in Python. It has more then 80 chars but less then 120."


```

> SublimeLinter: flake8: wanted executable is '/home/mifs/mttt2/.local/bin/flake8' 
> SublimeLinter: flake8: test.py ['/home/mifs/mttt2/.local/bin/flake8', '-'] 
> SublimeLinter: flake8 output:
> stdin:6:80: E501 line too long (90 > 79 characters)
> stdin:8:1: W391 blank line at end of file

Adding those options into the user settings directly will cause sublime linter to ignore both warnings.

**Comment by kaste** [comment]
SublimeLinter's inline overrides are really old code. Today, good linters should have this feature built in. Can't you just

```
# noqa: E501,W391
``` 

I'm in favor of actually removing this functionality from SublimeLinter completely bc a reference to the editor you use in your source code doesn't really scale.

**Comment by braver** [comment]
Totally agree, as I see it rIght now they’ll be going the way of the dodo in SL4. Probably made more sense 5 years ago.

**Comment by MarvinTeichmann** [comment]
> Can't you just # noqa: E501,W391

No, '# noqa: E501,W391' will just deactivate those checks for one line. If I have an entire file with loads of E501 violations this will not work.

> Today, good linters should have this feature built in. 

Afaik Flake8 doesn't and it is will not in near future. And flake8 is quite widely used. So imho it is still useful.

@braver: The inline settings are still in the documentation in a prominent position. So I would still consider it as a bug, as it does not work as documented. A possible fix would be to remove the corresponding sections in the Docu, of course.

**Comment by braver** [comment]
> So imho it is still useful.

Not on the editor level though. 

> The inline settings are still in the documentation in a prominent position.

Sure, always work to be done, we're getting to it.

**Comment by kaste** [comment]
@MarvinTeichmann Sorry I broke this. v3.0.2 https://github.com/SublimeLinter/SublimeLinter-flake8/releases/tag/3.0.2 hopefully should fix it. 

Please note that it is decided that this feature should go away with SL4. But you're using SL3. 😄

**Comment by MarvinTeichmann** [comment]
Thank you very much. Just wanted to emphasis that I still think this is very useful on editor level: I quite often have to work on dirty files from extern. Using this on a per file basis allows me to use basis linter functionality without interfering with my strict linter configuration used on my own files.

**Comment by braver** [comment]
Sure, but it's also kinda hard to implement well on the editor level. Also, what we're seeing is that the good use cases are for exactly what you're doing here: *not* to mirror all the configuration options that a linter already has, but to silence the warnings so you can properly read a "dirty file". We have a command for that now, called "Toggle Highlights".
Of course, if you want to develop additional functionality for SublimeLinter you're of course welcome to open a PR 😉
