### ISSUE TITLE
Showing outline everywhere!

### ISSUE THREAD

**Issue by iamchetanp** [SublimeLinter/SublimeLinter3#684]
When I save file. It shows errors and outline everywere in file which never go! Can you help me how can I disable that? I want to show error only on status bar and get rid from outline.

<img width="719" alt="screen shot 2017-12-09 at 5 27 40 pm" src="https://user-images.githubusercontent.com/16279742/33795379-46efd81a-dd06-11e7-8602-bfa2ddd71231.png">
.

**Comment by braver** [comment]
You can set the gutter theme and the highlight style both to “none” to disable them.

**Comment by iamchetanp** [comment]
This is my user setting. I can't find highlight style.

`{
    "user": {
        "debug": false,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "none",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {
            "phpcs": {
                "@disable": false,
                "args": [],
                "excludes": [],
                "standard": "WordPress"
            },
            "phpcsfixer": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "summitlinter": {
                "@disable": false,
                "args": [],
                "excludes": [],
                "globals": "",
                "ignore": "channel",
                "limit": null,
                "only": ""
            }
        },
        "mark_style": "none",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": false,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "javascript (babel)": "javascript",
            "magicpython": "python",
            "php": "html",
            "python django": "python",
            "pythonimproved": "python"
        },
        "tooltip_fontsize": "1rem",
        "tooltip_theme": "Packages/SublimeLinter/tooltip-themes/Default/Default.tooltip-theme",
        "tooltip_theme_excludes": [],
        "tooltips": false,
        "warning_color": "DDB700",
        "wrap_find": true
    }
}`

**Comment by braver** [comment]
Sorry, it’s called “mark_style”

**Comment by iamchetanp** [comment]
Yes. That's already none.

**Comment by iamchetanp** [comment]
Any suggestion to fix this issue?

**Comment by braver** [comment]
All I can think of is clearing all caches, check for interfering plugins, change color schemes, basically reset and debug your entries setup.

**Comment by jvavrek** [comment]
I had to wrap it in "styles":
```
"styles": [
	{"mark_style": "none"}
]
```
