### ISSUE TITLE
Add Contributors file

### ISSUE THREAD

**Issue by pykong** [SublimeLinter/SublimeLinter3#686]
In order to attract new contributors, we should honor their work in a dedicated file.
Such is common practice with many other open source projects.

**Comment by braver** [comment]
I don’t necessarily agree. Who would read that file when GitHub already lists the contributors?

**Comment by pykong** [comment]
OK. Let's keep stick to the status quo then.

**Comment by braver** [comment]
Ha, if it even smells like maintenance I’m scared of it 😉
