### ISSUE TITLE
[pre] Explain settings migration

### ISSUE THREAD

**Issue by FichteFoll** [SublimeLinter/SublimeLinter3#690]
There should be a word or two on how to migrate your settings, imo. Either within the update message itself or as a reference to some online docs.

What I discovered so far:
- The `user` dict is to be flattened
- `mark_style`, the tooltip stuff, `*_color`, `gutter_theme_excludes`, `show_errors_on_save`, `passive_warnings` were removed (or at least they don't occur in the default anymore)
- `@python` still exists, but is not in the default file
- `linters` is probably still where linter settings need to go, but that's also not in the default file

There should be a reference of each recognized setting in the default file, along with a nice comment explaining what it is used for. This is especially beneficial for PackageDev users, since they get highlighting of such "unrecognized" setting names and helpful tooltips for recognized ones with documentation from the accompanying comment.

See also https://github.com/SublimeText/PackageDev/wiki/Settings.

**Comment by braver** [comment]
fixed in d2944a0839701e498d9cea5ba6f9b49b79752589
