### ISSUE TITLE
Remove support for linter configuration that isn't @disable or args

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter3#693]
There are too many ways to get the same effect. Linter config options like `max-line-length` put a mapping in between the user and the tool that doesn't need to be there. It's simply a shorthand for a command line argument that the user probably already knows about. Mappings like these make SublimeLinter harder to understand, harder to use and harder to maintain.

**Comment by FichteFoll** [comment]
If `executable` winds up as being implemented in the core linter, it should obviously be excluded from this as well. (#653)

**Comment by braver** [comment]
Well, after a short survey there doesn’t seem to be that many settings out there that are really problematic. The “shorthand” stuff is something to discourage, but I’m not going to waste too much energy on this.

**Comment by FichteFoll** [comment]
I'm not sure I understand this sentiment.

**Comment by braver** [comment]
Well, it’s a bit of a process for me, and it all comes down to simplifying settings for everyone. Most linter settings are actually useful. At the same time, having any settings at all for a fully configurable linter like Flake8 just confuses people and they should all go. So I don’t think I can force anything from this repo, but will continue to look into the other issue about settings and work on existing plugins to reduce the overload.

**Comment by FichteFoll** [comment]
The thing is that many of the options available for linters are only specified that way in order to allow for inline overrides. There is no benefit from those otherwise. So this kind of depends on removing support for inline overrides altogether before they can be purged from the linters's options.

**Comment by braver** [comment]
Well, there is stuff like the 'stric' setting in SublimeLinter-json where I can see its usefulness as a global or project setting.
