### ISSUE TITLE
[beta] Remove support for inline settings/overrides

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter3#694]
Times have changed the past couple of years and linters are much more mature. Inline settings, per directory settings, etc., are usually supported right now. Changing such settings for a specific editing environment is a bad idea. 

http://www.sublimelinter.com/en/latest/settings.html#inline-settings

Inline overrides should be supported by the linter itself. Using this configuration (e.g. flake8's `#noqa` comments) ensures interop between editors and ensure that SL doesn't hide errors that will show up in command line usage or usage in CI or other automated environments.

Project settings aren't loaded when a single file is opened that is inside that project. A linter shouldn't report different errors depending on how the file was opened. `.sublimelinterrc` files offer the same features, but much are more flexible and more reliable at the same time. And again, CI and other editors can’t read Sublime project configuration, while most linters already provide project configuration features themselves (e.g. setup.cfg).

**Comment by braver** [comment]
Plugins supplying inline settings/overrides:

- pep8
- pylint
- flake​8
- pyflakes
- pydocstyle
- flow
- cpplint
- cppcheck
- bandit
- csslint
- gjslint
- shellcheck
- luacheck
- mdl
- dennis
- gotype
- glua
- scalac
- epcomp
- frosted
- coffee-jshint
- java
- mypy
- bashate
- cmakelint
- scss-lint
- ansible-lint

**Comment by FichteFoll** [comment]
Just for clarifiaction, if we remove inline setting override support, we can drop just *any* config that would end up at the command line as well. In that case, probably every linter needs to be revised and have those removed.

**Comment by braver** [comment]
I’m not sure what you mean by 

>  just any config that would end up at the command line

**Comment by FichteFoll** [comment]
Most options of linters end up at the command line more or less, it seems like, but some are handled or modified by plugin code directly. The rust linter has an option for using cargo over rustc for example.

**Comment by braver** [comment]
Oh, sure. Those settings are useful, but I don’t see the use case to have them at the file level.

I guess it depends on the specific linter, but running Flake8 with command line parameters isn’t optimal. Interop is much better if you use a config file. So for a lot of linters all these setting in SL just confuse people.

**Comment by FichteFoll** [comment]
Agreed. Note that you can specify a config file to be used via command line too.

**Comment by braver** [comment]
Yeah I noticed that use case yesterday, so there is an argument to be made to keep the args around.

**Comment by braver** [comment]
4.0.0-rc.15 does away with inline settings, inline overrides, shebang settings and sublimelinterrc settings. Linter specific settings can still be set in sublime-project configuration.
