### ISSUE TITLE
About the path setting

### ISSUE THREAD

**Issue by puhaung** [SublimeLinter/SublimeLinter3#697]
Hi dear all:
      I want to use SublimeLinter for verify Java grammar. But for the linter configuration there have some problem, who can help me.

     I used win 7 system.  I read the operation from http://sublimelinter.readthedocs.io/en/latest/troubleshooting.html#debugging-path-problems

     I have one doubt about which path I need to configure in system environment variable directly.

    It wirte as bellow:
    Select the parent directory of the linter executable and click OK.

    I configured two paths, but it still not work.
1:C:\Users\huangpu\AppData\Roaming\Sublime Text 3\Packages\User\linters
2:C:\Users\huangpu\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter

   I don't know which is the linter executable directory.

**Comment by braver** [comment]
Those 2 are paths to SublimeLinter packages. What you need to configure is the path to the java grammar linter (I don't know anything about Java), which is more likely to be in a directory like c:\Program Files\Java.
