### ISSUE TITLE
rubocop linter issue

### ISSUE THREAD

**Issue by ckhall** [SublimeLinter/SublimeLinter3#698]
Don't know who or where to ask so forgive me if I'm not following protocol here.

Any chance this can get looked at and merged?  https://github.com/SublimeLinter/SublimeLinter-rubocop/pull/47

Been sitting around for a while. Thanks!

**Comment by braver** [comment]
I don’t have any way to test this but if you’re confident it’s a good change that doesn’t break too many people’s setup, I’ll merge and release it. So confirm that and I’ll push the button.

**Comment by ckhall** [comment]
I've been using this locally since i first created the PR with no issues.

**Comment by ckhall** [comment]
others are welcome to download from my fork and test for themselves if you need more 3rd party approvals.

**Comment by braver** [comment]
Good enough for me. Want to have access to the repo and do the release yourself?

**Comment by ckhall** [comment]
@braver if you don't mind dealing with it, I'd appreciate it.
