### ISSUE TITLE
virtualenv support

### ISSUE THREAD

**Issue by ajkavanagh** [SublimeLinter/SublimeLinter3#70]
I work on both Python 2 and Python 3 projects and have various versions of them installed on my system.
- My system is OS X and I use homebrew to install Python 2 and 3.
- I also use virtualenvs to separate various Python 2 and 3 configurations.
- I want to have 'sublimelinter2' 'sublimelinter3' virtualenvs with the modules installed for python 2 & 3.
- I'd like to tell SublimeLinter3 to use these globally and on a per project basis.

Essentially, at a global level I'd like SublimeLinter3 to use a globally configured virtualenv for the modules as a minimum.  I don't want to mess with the system python or libraries at all.

Thanks.

**Comment by davis** [comment]
+1

**Comment by darvid** [comment]
I've been able to get pylint working in virtualenv with a quick hack to SL3 and some minor configuration. Here's a quick run-through:

1. This assumes that [Anaconda](http://damnwidget.github.io/anaconda/) for ST3 is present, or at least that the  ``python_interpreter`` setting is present in your Sublime project settings file. (see the [Anaconda docs](http://damnwidget.github.io/anaconda/anaconda_settings/) for more information)
1. Apply these changes to util.py: 335e451b090d5f7c67a28adea0c1db14b8f0dd3b
2. Set ``init-hook`` in **.pylintrc** to this (adapted from [this blog post](http://blog.ufsoft.org/2012/12/27/pylint-+-virtualenv/)):

```ini
init-hook="
    import sys, os
    ve_dir = (
        os.environ['VIRTUAL_ENV'] if 'VIRTUAL_ENV'in os.environ
        else os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..')))
    activate_this = os.path.join(os.path.join(ve_dir, 'bin'), 'activate_this.py')
    activate_this = (
        activate_this if os.path.exists(activate_this)
        else os.path.join(os.path.join(ve_dir, 'Scripts'), 'activate_this.py'))
    if not os.path.exists(activate_this): sys.exit(0)
    ve_dir in sys.path or sys.path.insert(0, ve_dir)
    execfile(activate_this, dict(__file__=activate_this))
    "
```

This is probably not the most ideal way to fix this issue, but some benefits are:

* No additional configuration needed (in terms of ST project settings at least) if you're using Anaconda as well as SL3; shared setting for ``python_interpreter``
* No SL3 specific logic to run the virtualenv's activate_this.py file, which means it won't work unless you configure your **.pylintrc** file. But IMO, you should be doing that anyway if you intend on being able to use **pylint** from the command line, or for other users who may not be using Sublime.

I doubt this is PR material, but if it is or has the potential to be I can make one.

**Comment by rgant** [comment]
I've made a fork of SublimeLinter-pylint which works with pyenv (and probably virtualenvwrapper) to pylint the file with the venv's pylint and site_packages. It's very very hacky, but might work for those that have advanced virtualenvs that detect the correct python based on paths.

https://github.com/rgant/SublimeLinter-pylint

**Comment by muodov** [comment]
How about allowing to explicitly specify python version in the source code? Say, put `# pyver: v3.5` somewhere in the top, and then choose the python binary path based on that?

**Comment by ubombi** [comment]
IMO the easiest way: 
```
#!/usr/bin/bash
. /path/to/env/bin/activate
subl subl --project /path/to.sublime-project
```

**Comment by jt-wang** [comment]
I find a work-around.
Just add your `virtualenv` path to  `SublimeLineter.sublime-settings`

```json
        "paths": {
            "linux": [],
            "osx": [
                "/Users/jt-wang/n/bin/",
                "/Users/jt-wang/.pyenv/versions/py3/bin/"
            ],
            "windows": []
        },
```

**Comment by rgant** [comment]
I think that only works if you have a single virtualenv @jt-wang.

**Comment by jt-wang** [comment]
@rgant That's true. Do you think it's possible to override the config in each  `.sublime-project` settings for different project?

**Comment by rgant** [comment]
@jt-wang According to the documentation, 'paths' is not supported in the project settings because it is not a meta-setting or a linter setting.

http://www.sublimelinter.com/en/latest/settings.html#project-settings

> Note
> 
> Only meta-settings and linter settings are recognized in project settings.

I recall aparajita stating in another issue that supporting per-project paths would be difficult because of the way SublimeLinter initalizes all the linters on SublimeText launch. This is why I [forked sublimelinter](https://github.com/rgant/SublimeLinter-pylint) to support pyenv.

**Comment by kiddick** [comment]
@rgant why fork instead of pull request?

**Comment by rgant** [comment]
@kiddick My fork lacks any tests and is very specific to my environment using pyenv. I.e. it is a hack. I haven't made the time to test other python virtualenv setups to see if my changes would be compatible. I basically disable some safety checks that aparajita added to make sure that the pylint is compatible with the linter. Since I know my environment is, I can just turn off those checks.

**Comment by AndrewPashkin** [comment]
@rgant 
> I think that only works if you have a single virtualenv @jt-wang.

What about using `.sublimelinterrc`?

**Comment by rgant** [comment]
I haven't tried it, but I think it's the same problem with per-project
settings not supporting paths. SublimeLinter only initializes the linter
paths when sublime text launches. But give it a shot and let us know!

**Comment by posita** [comment]
This isn't fixed. `SublimeLinter-pylint` does not use the setting from `.sublimelinterrc` (although `SublimeLinter-flake8` seems to work).
