### ISSUE TITLE
[next] Panel flickers when typing *anywhere*

### ISSUE THREAD

**Issue by FichteFoll** [SublimeLinter/SublimeLinter3#700]
When typing something, the errors in the panel flicker, presumably when the view is re-linted.

Now, the interesting part is that this also happens when typing in the **Command Palette**. I've verified (in the console, with debug prints) that no linting happens when I type into the command palette panel.

I recorded a video of this (does not play in FireFox). You can see the flicker happening at ~0:14. It happened a few additional times but those weren't picked up in the video. It's also inconsistent.

https://x0.at/s3c.mp4

**Comment by deathaxe** [comment]
Maybe caused by updating the panel by running three separate text commands, which causes the panel to be repainted 3 times?

https://github.com/SublimeLinter/SublimeLinter3/blob/98708947ead39facb74edfc37288476ac055d3f9/panel/panel.py#L24-L29

**Comment by FichteFoll** [comment]
Hm indeed. It might be smart to bundle this into a single TextCommand. I'll test if that helps.
