### ISSUE TITLE
[next] Diagnostics panel renders <0x0d> at the end of each line

### ISSUE THREAD

**Issue by deathaxe** [SublimeLinter/SublimeLinter3#703]
- ST 3156 x64
- Win 10 x64 1709
- SL 4.0 beta
- pylint

![screenshot](https://user-images.githubusercontent.com/16542113/34069900-344e2abe-e25a-11e7-8cf7-a6f26b6b8b4b.png)

**Comment by braver** [comment]
Of course pylint doesn't want to cooperate on my system. Looks like the pylint plugin is in need of some attention too.... why are there so many linters for python?

Could it be that it is picking up a windows line ending here and the regex in the pylint plugin needs to be adjusted? 
https://github.com/SublimeLinter/SublimeLinter-pylint/blob/master/linter.py#L34

**Comment by deathaxe** [comment]
Looks like the following regex would fix it.

```
    regex = (
        r'^(?P<line>\d+):(?P<col>\d+):'
        r'(?P<code>(?:(?P<error>[FE])|(?P<warning>[CIWR]))\d+): '
        r'(?P<message>.*?)(?:\r?$)'
    )
```

**Comment by braver** [comment]
Works for me: https://github.com/SublimeLinter/SublimeLinter-pylint/commit/37c45b088b1074e2705576da475b3678e39e1b17

**Comment by FichteFoll** [comment]
Why not run execute linters with the `universal_newline` flag instead and specify the enconding along with the Popen call instead of manually decoding everywhere (basically everywhere that `util.run_shell_command` is run and in `util.combine_output`).

This would probably need some testing, but would be the most proper way to handle the situation.

**Comment by braver** [comment]
Ok, sounds like it would be cleaner. If you put that in an issue we can come back to it later.

**Comment by kaste** [comment]
Okay this is not Twitter, but @deathaxe what font? 😍  Need a new one for Windows 10.

**Comment by braver** [comment]
@kaste looks like Fira Code (or Fira Mono) to me:
http://app.programmingfonts.org/#firacode
