### ISSUE TITLE
Stop changing my color_scheme on my settings file

### ISSUE THREAD

**Issue by evandrocoan** [SublimeLinter/SublimeLinter3#707]
If you delete this line:
```json
	"color_scheme": "Packages/User/SublimeLinter/Monokai (SL).tmTheme",
```
In a few seconds, it jumps back to my user settings file:
```json
	"color_scheme": "Packages/User/SublimeLinter/Monokai (SL).tmTheme",
```

ColorHighlither also need to add colors to my color scheme file, however it is not violating my settings file changing the color scheme on the file system.

**Comment by braver** [comment]
You can use SL4, which we’re beta testing right now, it doesn’t do that anymore: https://github.com/SublimeLinter/SublimeLinter3#sublimelinter-4-beta
