### ISSUE TITLE
[beta] Panel should be updated when a view with lint errors has been closed

### ISSUE THREAD

**Issue by FichteFoll** [SublimeLinter/SublimeLinter3#708]
Title, basically. When a view with lint errors is closed, the panel should be updated and have the closed view removed.

**Comment by braver** [comment]
@pykong sublime_linter.py line 156: `on_pre_close_async` should be `on_pre_close`, the contents of that method should be fixed and a panel update should be added.

**Comment by pykong** [comment]
Fixed by 157b36fa4747a088c270df2bf6b45eaca3a51779
