### ISSUE TITLE
[beta] Show some indicator whether lint processes are currently active

### ISSUE THREAD

**Issue by FichteFoll** [SublimeLinter/SublimeLinter3#709]
In the panel or status bar, but panel seems to be ideal. Some linters take a little longer to run (e.g. mypy) and it would be useful to know whether there are still some that haven't finished yet instead of assuming there are no more issues with your code.

**Comment by pykong** [comment]
We could borrow the busy indicator from PackageControl.
I think it is a good one.

**Comment by FichteFoll** [comment]
Might make sense to show it in the panel directly, if it is open. Maybe inside a phantom, which doesn't require updating contents of the entire panel.

I'm not sure whether you need to see that lintings is still in progress when that is closed, to be honest.
