### ISSUE TITLE
[beta] Define a namedtuple type to be returned from the split_match plugin API

### ISSUE THREAD

**Issue by FichteFoll** [SublimeLinter/SublimeLinter3#711]
The current interface expects a 7-tuple, which is quite messy. Defining a namedtuple class (with default values) somewhere in the linter module that plugins can instantiate with named kwargs would improve readability significantly.

Additionally, this change would be completely backwards-compatible since you can index namedtuples just like normal tuples in addition to attribute names. (To always work with those internally, a normal tuple could be converted internally using the `*` unpacking operator.)

**Comment by pykong** [comment]
I have opened a PR for the implementation of this enhancement request.
https://github.com/SublimeLinter/SublimeLinter3/pull/732

Maybe you want to have a look into it.
