### ISSUE TITLE
[beta] Cannot jump to untitled view from panel

### ISSUE THREAD

**Issue by braver** [SublimeLinter/SublimeLinter3#716]
> If you have errors in an yet untitled view, you cannot jump into them. Instead, a new, empty scratch view will open.

Seen by @kaste in #715

**Comment by braver** [comment]
Also, the common_path stuff messes up the path for "untitled"

**Comment by braver** [comment]
Fixed. Apparently ST recognises `<untitled {}>` with `{}` being the `view.buffer_id()`

**Comment by FichteFoll** [comment]
That's quite interesting, actually.

**Comment by braver** [comment]
It is. I noticed the formatting in the find results panel and figured it had to work jus like the other panels. I found a comment on the forum by KingKeith who confirmed that and specified the view.buffer_id part, apparently he had the info from JP himself. Gotta love undocumented nooks and crannies like this.
