### ISSUE TITLE
[beta] Linter `@disable` setting overridden

### ISSUE THREAD

**Issue by willrowe** [SublimeLinter/SublimeLinter3#719]
The change made in #699 that specifies the global meta setting `@disable` revealed that the settings are not being merged in the proper order. If any individual linter has `@disable` set to `true`, it will still be enabled if the global `@disable` setting is set to `false`. The only way to allow the linter to be disabled is to omit the global `@disable` setting.

I believe the issue lies in this code:
https://github.com/SublimeLinter/SublimeLinter3/blob/6de300a2f12751670f50665c10dfa1f6d82e75ac/lint/linter.py#L490-L492

I fixed it by adding this after:
```python
meta.update(self.meta_settings(self.settings()))
```
That essentially merges the linter meta settings on top of any global meta settings. I'm not sure if that messes with anything else though, but I thought I would report the bug in the merge order of these settings.

**Comment by pykong** [comment]
@willrowe Nice catch. Thanks for letting us know.

**Comment by braver** [comment]
Actually, according to the docs this is how it's supposed to work:

> When used globally, they are applied to every linter and override a linter meta setting

Which is super weird and counter-intuitive IMO, why should this go *against* the settings cascade? 

I'm testing some stuff and run into project settings possibly not working. Not sure how I feel about that. Anyway @willrowe this is not actually a bug but it does make me think we should have a good at this. Your suggested change looks good, but we'll let you know how we fare.

**Comment by willrowe** [comment]
Good point.

When first looking at it, I expected that the global `@disable` setting would do the following:
- If set to `true`, it would enable any linting. Any individual linter settings could then be disabled as needed.
- If set to `false`, it would disable all linting. This would override all individual linter settings.

The real issue here is that I was interpreting it as a global setting for the SublimeLinter plugin itself and not as an override for the individual linter settings themselves. Just a shortcut to disabling the package itself.

If it really is meant to be an override, then it I think it should be commented out by default in the settings. I'm not sure what the benefit of being able to override the `@disable` setting for all linters is, but it definitely leads to unexpected results when trying to disable individual linters.

**Comment by FichteFoll** [comment]
Maybe introduce a third state with `null` meaning "don't care" or "inherit".

**Comment by braver** [comment]
4.0.0-rc.15 does away with the concept of meta settings. You can now specify "disable" only per linter (note that the `@` is gone from the setting name).

**Comment by willrowe** [comment]
Thanks for looking into this, the solution you came up with makes a lot more sense.

**Comment by braver** [comment]
Thanks for bringing it up and putting me on the right track!
