### ISSUE TITLE
[beta] Inside the hover messages, the error count is the line error count

### ISSUE THREAD

**Issue by darkred** [SublimeLinter/SublimeLinter3#720]
_(Using SublimeLinter 4.0.0-rc.11 and Sublime​Linter-contrib-eslint 1.10.0
in ST3 3156 x64 (clean installation))_

Based on [4.0.0-rc.1.txt](https://github.com/SublimeLinter/SublimeLinter3/blob/next/messages/4.0.0-rc.1.txt) in the new version:

> - **Hover over an error to view the message.**
> - Hover over the gutter to view all error messages for that line.

But, currently, inside the hover message, the error count is the line error count (instead of the current position error count), which I find it very confusing.

For example. in the following code line 4 has 2 errors, and hovering hovering over the gutter shows '2 errors' as expected:
![2017-12-19_203431](https://user-images.githubusercontent.com/723651/34173261-8a199abe-e4fd-11e7-9cd1-45668c3e7a7a.jpg)

But. hovering on either error position, the count in the message is also '2 errors' 
(although on each position there's only 1 error): 
![2017-12-19_203348](https://user-images.githubusercontent.com/723651/34173262-8a4d26f4-e4fd-11e7-8ed9-1e10ea684657.jpg)

IMHO the '2 errors' count should appear only on the gutter - the hover message should display the error count for the **current position** , i.e. in this case it would be '1 error' for each position.

**Comment by braver** [comment]
Jup, that's a bug. We should probably just remove the count from the region popup.

**Comment by FichteFoll** [comment]
Don't we want the error type (and color) to be displayed for the inline popup as well?

Tbh I find the logic at this point kind of weird as I can't easily predict when the `line_dict` will have what kind of contents, so I'd rather have you work on the logic on implementing that instead of submitting a PR.
