### ISSUE TITLE
[beta] Feature request: replace the "W: y, E: y" in the status bar with either two symbols or the full words 'warnings' and 'errors'

### ISSUE THREAD

**Issue by darkred** [SublimeLinter/SublimeLinter3#724]
_(Using SublimeLinter 4.0.0-rc.12 and Sublime​Linter-contrib-eslint 1.10.0
in ST3 3156 x64 )_

In the new version, the warning and errors are displayed in the status bar like this:
![2017-12-20_005311](https://user-images.githubusercontent.com/723651/34182904-c6f55bda-e520-11e7-9472-6daf348397d5.jpg)

I find that using the initials "W" and "E" for referring to warnings and errors is not really self-explanatory nor practical or easily distinguishable.
Additionally, I believe that errors should appear before warnings, as they are more important.

So, I'd suggest: 
- either replace W and E with two symbols similar to those of VSCode with the ESLint extension, 
_i.e. a circled X symbol for errors, and an exclamation inside a triangle symbol, for warnings,_  
![2017-12-20_003232](https://user-images.githubusercontent.com/723651/34182356-872f116e-e51e-11e7-81c8-0b73eb4f937a.jpg)
- or, just use the full words, "errors" and "warnings.
_For reference, in SL3 it shows just the sum, "4 errors":_
![2017-12-20_003332](https://user-images.githubusercontent.com/723651/34182368-9b2ea53a-e51e-11e7-9285-f9d4a08cfe91.jpg)

I'd definitely prefer the former one.

Thank you

**Comment by braver** [comment]
For icons all we have to work with are some Unicode glyphs and they usually don’t look clear enough at small sizes. We have zero control over the font or the size, so it just doesn’t work.

The full text is a bit long, a lot of plugins want to put something in the status bar. 

This is a compromise, and not a terrible one IMO. I’m not against having some options here, but I like to keep configurability low. As such it’s not a priority.

**Comment by FichteFoll** [comment]
Just for the record, Unicode glyphs like that usually look terrible in my status bar.

**Comment by braver** [comment]
Yeah, we tried the statusbar with glyphs for a while, it just looked scrambled up. 

I like the template setting that GitGutter offers. If we were to enhance the statusbar messages in any I think that would be the way to go.

**Comment by pykong** [comment]
Can we do HTML/phantom stuff in the status bar?
If so, I will implement it for us.

**Comment by braver** [comment]
> Can we do HTML/phantom stuff in the status bar?

Nope, no images or anything, just text. Which is ok, but something like the GitGutter statusbar template feature would at least allow someone to chose between `E` or `error` or a glyph of their choosing, or whatever. Adding configurability for things like is very low priority for though now.

**Comment by pykong** [comment]
OK. This I thought to be.
I do not like to have such configurability at all. We really shouldn't undo all the good cleaning and simplification we have done.

Better we wait/hope for native icon support to the status bar, in case we can still change things.
