### ISSUE TITLE
[beta] Errors on line 1 are not shown

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter3#730]
If I have errors on the first line of my file, nor errors are shown::

![image](https://user-images.githubusercontent.com/8558/34225419-b73c152a-e5c6-11e7-97c9-cd4b9b9546ff.png)

![image](https://user-images.githubusercontent.com/8558/34225446-c8eb385a-e5c6-11e7-926c-adc98b8e9c9c.png)

No gutter icons, and underlines or whatever as well ❓

**Comment by pykong** [comment]
@kaste thank you for reporting. I will have a look into it.
