### ISSUE TITLE
[beta] solid_underline does not mark whitespace

### ISSUE THREAD

**Issue by Gliptal** [SublimeLinter/SublimeLinter3#737]
As per title, any error regarding whitespace isn't marked by the solid_underline option (but is by other options e.g. outline).

![solid_underline](https://i.imgur.com/CPBH8ct.png)

![outline](https://i.imgur.com/hYdF8mg.png)

Also, two questions: 

- What are the name of the regions that now have to be protected for SublimeLinter to take precedence over GitGutter?

- How do I specify an hex/rgb color for the scope(s) in the styles options?

**Comment by pykong** [comment]
That is a core issue not a problem specific to SublimeLinter.

**Comment by Gliptal** [comment]
Thanks, I'll revert to outline for the time being then. I thought it used to work in SL3, but I must have been mistaken.

**Comment by FichteFoll** [comment]
Feel free to upvote the upstream issue: https://github.com/SublimeTextIssues/Core/issues/137

**Comment by braver** [comment]
Nothing we can do here.

**Comment by Gliptal** [comment]
@FichteFoll Yep I digged around and I see now how I should be handling custom values. Thanks.
