### ISSUE TITLE
[beta] incomplete error messages in popups

### ISSUE THREAD

**Issue by Gliptal** [SublimeLinter/SublimeLinter3#738]
See this example:

![Imgur](https://i.imgur.com/8Xy1K9x.png)

Possibly related to the presence of a single quote char?

**Comment by FichteFoll** [comment]
I thought this had been fixed already?

**Comment by pykong** [comment]
We `html escpape` all error messages, makes me wonder how this bug comes into being then.

**Comment by Gliptal** [comment]
@FichteFoll I'm on the SL available through package control, wouldn't know how to check the version. On ST 3143 if that helps.

**Comment by FichteFoll** [comment]
You can check with the "Package Control: List  Packages" command. There have definitely been a few releases since that commit.

**Comment by Gliptal** [comment]
Turns out it's 4.0.0-rc.9

**Comment by braver** [comment]
Release candidates are tagged after I test new contributions, tagged versions should propagate through package control within a few hours. And updates via package control are only installed on restart. So, we’re pushing updates out regularly, but they might not land on your end immediately.

I really appreciate everyone who takes the time to have a look and report possible issues though. 👍🏻
