### ISSUE TITLE
[beta] SublimeLinter-contrib-mypy not working

### ISSUE THREAD

**Issue by pykong** [SublimeLinter/SublimeLinter3#741]
Trying to run `SublimeLinter-contrib-mypy` with `4.0.0-rc.14` resulting in an exception (shown below).
Irrespective if I set `@python` to `null` or `3`, the error persists.

**traceback:**
```
SublimeLinter: Traceback (most recent call last):
...
  File "/home/user/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 1068, in get_cmd
    if '@python' in which:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by kaste** [comment]
Hooray, I introduced a bug.

I've just checked the other python based linters again, after knowing this code path. And I still think all the others should work and forward/backward compatible. 

So the story for `mypy` was always a bit different bc they try to circumvent bugs in SL3 (same as `gcc`). `gcc` published today a forward/backward compatible version of their plugin, and I think it would be okay to ask `mypy` to do the same.

**Comment by braver** [comment]
Sounds good. @kaste want me to open an issue over at mypy?

**Comment by kaste** [comment]
I want to checkout the code to see what the easiest forward compatible change could be.

**Comment by kaste** [comment]
The smallest possible change to get it running is

```
$ git diff
diff --git a/linter.py b/linter.py
index 84fcab7..dd67511 100644
--- a/linter.py
+++ b/linter.py
@@ -15,7 +15,7 @@ import os
 import shutil
 import tempfile

-from SublimeLinter.lint import PythonLinter, util, highlight, persist
+from SublimeLinter.lint import Linter, util, highlight, persist

 TMPDIR_PREFIX = "SublimeLinter-contrib-mypy-"

@@ -25,7 +25,7 @@ TMPDIR_PREFIX = "SublimeLinter-contrib-mypy-"
 tmpdirs = {}  # type: Dict[str, tempfile.TemporaryDirectory]


-class Mypy(PythonLinter):
+class Mypy(Linter):
     """Provides an interface to mypy."""

     syntax = 'python'
```

That is instead of subclassing `PythonLinter` just use the base `Linter`. Why? `mypy` actually tries its best to not use the PythonLinter (similar to `flake8`). Since their cmd isn't even `mypy@python` the so-called meta-setting `@python` is never triggered, thus it always uses the one and only global `mypy` executable in PATH. 

To get that behavior it is better to just use the base Linter.

**Comment by kaste** [comment]
Made a PR https://github.com/fredcallaway/SublimeLinter-contrib-mypy/pull/15

**Comment by braver** [comment]
No need to track this here.
